import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";

export default async function EstimateSpatialTracePage({params}:{params:Promise<{estimateId:string}>}){
  const {estimateId}=await params;
  const ctx=await requireTenantContext();
  const estimate=await db.costEstimate.findFirst({where:{id:estimateId,accountId:ctx.account.id},include:{project:true}}); if(!estimate) notFound();
  const rows=await db.$queryRawUnsafe<Array<{estimateLineId:string;lineDescription:string;quantityBasis:number|null;spatialObjectId:string;objectName:string;objectType:string;measurement:number|null;quantity:number;unit:string;confidence:number|null;verifiedAt:Date|null;drawingRevisionId:string;sheetNumber:string;sheetTitle:string|null;revision:string;layerName:string|null;calibrationId:string|null}>>(`SELECT l."estimateLineId",i."description" AS "lineDescription",l."quantityBasis",o."id" AS "spatialObjectId",o."name" AS "objectName",o."objectType",o."measurement",o."quantity",o."unit",o."confidence",o."verifiedAt",o."drawingRevisionId",r."sheetNumber",r."sheetTitle",r."revision",dl."name" AS "layerName",o."calibrationId" FROM "SpatialEstimateLink" l JOIN "EstimateLineItem" i ON i."id"=l."estimateLineId" JOIN "SpatialTakeoffObject" o ON o."id"=l."spatialObjectId" JOIN "DrawingRevision" r ON r."id"=o."drawingRevisionId" LEFT JOIN "DrawingLayer" dl ON dl."id"=o."layerId" WHERE l."accountId"=$1 AND i."estimateId"=$2 ORDER BY r."sheetNumber",o."createdAt"`,ctx.account.id,estimateId);
  const projectId=estimate.projectId;
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Bidirectional Provenance</p><h1 className="stratum-sheet-title">EST-{String(estimate.number).padStart(4,"0")} Spatial Trace</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Every linked estimate line is traced back to its drawing sheet, revision, layer, takeoff object, verification state, measurement basis, and calibration provenance.</p></div><div className="flex flex-wrap gap-2">{projectId&&<Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link>}<Link href={`/costing/estimates/${estimateId}`} className="btn-secondary">Estimate</Link></div></div></section>
    <section className="grid gap-3 sm:grid-cols-3"><div className="stratum-sheet"><div className="cat">Linked takeoff objects</div><div className="mt-2 text-2xl font-semibold text-[#DCEBF5]">{new Set(rows.map(r=>r.spatialObjectId)).size}</div></div><div className="stratum-sheet"><div className="cat">Linked estimate lines</div><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{new Set(rows.map(r=>r.estimateLineId)).size}</div></div><div className="stratum-sheet"><div className="cat">Verified</div><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{rows.filter(r=>r.verifiedAt).length}</div></div></section>
    <section className="stratum-sheet">{rows.length===0?<div className="empty-state">No drawing takeoff objects are linked to this estimate yet.</div>:<div className="table-scroll"><table className="min-w-[1150px]"><thead><tr><th>Estimate line</th><th>Drawing source</th><th>Layer</th><th>Object</th><th className="num">Measurement</th><th>QA</th><th>Calibration</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.estimateLineId}-${r.spatialObjectId}`}><td className="desc-cell">{r.lineDescription}<span className="cat">Basis {r.quantityBasis??"—"}</span></td><td>{r.sheetNumber} · R{r.revision}<span className="cat">{r.sheetTitle||"Untitled"}</span></td><td>{r.layerName||"—"}</td><td>{r.objectName}<span className="cat">{r.objectType}</span></td><td className="num text-[#6FD6C9]">{r.objectType==="COUNT"?r.quantity:(r.measurement??r.quantity)} {r.unit}</td><td>{r.verifiedAt?<span className="text-[#6FD6C9]">Verified</span>:<span className="text-[#E0954F]">Unverified</span>}<span className="cat">{r.confidence==null?"No confidence":`${Math.round(r.confidence*100)}% confidence`}</span></td><td>{r.calibrationId?<span className="text-[#6FD6C9]">Snapshot retained</span>:r.objectType==="COUNT"?<span className="text-[#9CB2C2]">Not required</span>:<span className="text-[#E0954F]">Manual basis</span>}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
