import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getPlanRoom } from "@/lib/plan-room";
import { approveDrawingIngestionAction, queueDrawingIngestionAction } from "./actions";

type RevisionRow={id:string;documentId:string;revision:string;issuedAt:Date|null;externalUrl:string|null};
type IngestionRow={id:string;documentId:string;documentRevisionId:string|null;status:string;discipline:string;detectedSheetNumber:string|null;detectedSheetTitle:string|null;detectedRevision:string|null;pageNumber:number|null;drawingSetId:string|null;drawingRevisionId:string|null;confidence:number|null;errorMessage:string|null;createdAt:Date;updatedAt:Date};
type SetRow={id:string;name:string;discipline:string};

export default async function DrawingIngestionPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params; const ctx=await requireTenantContext();
  const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}}); if(!project)notFound();
  const [{documents},revisions,items,sets]=await Promise.all([
    getPlanRoom(projectId,ctx.account.id),
    db.$queryRawUnsafe<RevisionRow[]>(`SELECT r."id",r."documentId",r."revision",r."issuedAt",r."externalUrl" FROM "ProjectDocumentRevision" r JOIN "ProjectDocument" d ON d."id"=r."documentId" WHERE d."projectId"=$1 AND r."accountId"=$2 ORDER BY r."createdAt" DESC`,projectId,ctx.account.id),
    db.$queryRawUnsafe<IngestionRow[]>(`SELECT * FROM "PlanRoomDrawingIngestion" WHERE "projectId"=$1 AND "accountId"=$2 ORDER BY CASE "status" WHEN 'REVIEW' THEN 0 WHEN 'QUEUED' THEN 1 WHEN 'FAILED' THEN 2 ELSE 3 END,"updatedAt" DESC`,projectId,ctx.account.id),
    db.$queryRawUnsafe<SetRow[]>(`SELECT "id","name","discipline" FROM "DrawingSet" WHERE "projectId"=$1 AND "accountId"=$2 ORDER BY "name"`,projectId,ctx.account.id),
  ]);
  const docs=documents.filter(d=>["ELECTRICAL","ARCHITECTURAL","MECHANICAL","PLUMBING","CIVIL","STRUCTURAL","GENERAL","AS_BUILT","ADDENDUM"].includes(d.documentType));
  const pending=items.filter(i=>i.status!=="INGESTED"); const ingested=items.filter(i=>i.status==="INGESTED");
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Digital Plan Room · Drawing Ingestion</p><h1 className="stratum-sheet-title">{project.name} Drawing Intake</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Convert managed Plan Room documents into drawing sheets without losing source provenance. Detection proposes metadata only; a reviewer confirms sheet number, title, discipline, revision and page before the drawing enters the Spatial Viewer.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/drawings/viewer`} className="btn">Spatial Viewer</Link><Link href={`/projects/${projectId}/plan-room`} className="btn-secondary">Plan Room</Link></div></div></section>

    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Queue Plan Room page</h2><p className="cat mt-1">Choose the exact document revision whenever available. Multi-page PDFs are queued one page at a time so every drawing sheet retains a precise source page.</p>{docs.length===0?<div className="empty-state mt-3">Register a drawing-capable document in the Plan Room first.</div>:<form action={queueDrawingIngestionAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-4"><select name="documentId" required><option value="">Plan Room document</option>{docs.map(d=><option key={d.id} value={d.id}>{d.name} · {d.documentType}</option>)}</select><select name="documentRevisionId"><option value="">Current document / no revision record</option>{revisions.map(r=>{const d=documents.find(x=>x.id===r.documentId);return <option key={r.id} value={r.id}>{d?.name||"Document"} · Rev {r.revision}</option>;})}</select><input name="pageNumber" type="number" min="1" defaultValue="1" placeholder="PDF page"/><button className="btn">Detect & queue</button></form>}</section>

    <section className="stratum-sheet"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Review queue</h2><p className="cat">{pending.length} pending · {ingested.length} ingested</p></div></div>{pending.length===0?<div className="empty-state mt-3">No drawing pages need review.</div>:<div className="mt-3 space-y-3">{pending.map(i=>{const d=documents.find(x=>x.id===i.documentId);const r=revisions.find(x=>x.id===i.documentRevisionId);return <div key={i.id} className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-sm font-semibold text-[#DCEBF5]">{d?.name||"Plan Room document"}</div><div className="cat">Source {r?`Rev ${r.revision}`:"document current"} · page {i.pageNumber??1} · detector confidence {i.confidence==null?"—":`${Math.round(i.confidence*100)}%`}</div></div><span className="tag REF">{i.status}</span></div><form action={approveDrawingIngestionAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-6"><input type="hidden" name="ingestionId" value={i.id}/><input name="sheetNumber" required defaultValue={i.detectedSheetNumber??""} placeholder="E-101"/><input name="sheetTitle" defaultValue={i.detectedSheetTitle??""} placeholder="Power Plan - Level 1"/><input name="revision" defaultValue={i.detectedRevision??r?.revision??"0"} placeholder="Revision"/><select name="discipline" defaultValue={i.discipline}><option>ELECTRICAL</option><option>ARCHITECTURAL</option><option>MECHANICAL</option><option>PLUMBING</option><option>CIVIL</option><option>STRUCTURAL</option><option>GENERAL</option></select><select name="drawingSetId"><option value="">Auto: discipline Plan Room set</option>{sets.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="btn">Approve to Drawings</button></form>{i.errorMessage&&<div className="mt-2 text-xs text-rose-300">{i.errorMessage}</div>}</div>;})}</div>}</section>

    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Ingested drawing sources</h2>{ingested.length===0?<div className="empty-state mt-3">No Plan Room pages have been ingested yet.</div>:<div className="table-scroll mt-3"><table className="min-w-[900px]"><thead><tr><th>Source</th><th>Sheet</th><th>Discipline</th><th>Page</th><th>Drawing</th></tr></thead><tbody>{ingested.map(i=>{const d=documents.find(x=>x.id===i.documentId);return <tr key={i.id}><td>{d?.name||"Document"}</td><td>{i.detectedSheetNumber||"—"} · R{i.detectedRevision||"0"}</td><td>{i.discipline}</td><td>{i.pageNumber??1}</td><td>{i.drawingRevisionId?<Link href={`/projects/${projectId}/drawings/viewer?revisionId=${encodeURIComponent(i.drawingRevisionId)}`} className="text-[#6FD6C9]">Open exact sheet</Link>:"—"}</td></tr>;})}</tbody></table></div>}</section>
  </div>;
}
