import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import { matchSpatialRevisions } from "@/lib/revision-matching";
import { applySpatialCommercialDeltaAction } from "./actions";

function measure(o:{objectType:string;quantity:number;measurement:number|null}){return o.objectType==="COUNT"?o.quantity:(o.measurement??o.quantity);}

export default async function CommercialReviewPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const {revisions,objects,layers}=await getDrawingWorkspace(projectId,ctx.account.id);
  const links=await db.$queryRawUnsafe<Array<{spatialObjectId:string;estimateLineId:string;estimateId:string;quantityBasis:number|null;lineQuantity:number;description:string;materialCost:number;laborHoursPerUnit:number;laborRate:number;estimateNumber:number;estimateStatus:string}>>(`SELECT l."spatialObjectId",l."estimateLineId",ce."id" AS "estimateId",l."quantityBasis",eli."quantity" AS "lineQuantity",eli."description",eli."materialCost",eli."laborHoursPerUnit",ce."laborRate",ce."number" AS "estimateNumber",ce."status" AS "estimateStatus" FROM "SpatialEstimateLink" l JOIN "EstimateLineItem" eli ON eli."id"=l."estimateLineId" JOIN "CostEstimate" ce ON ce."id"=eli."estimateId" WHERE l."accountId"=$1 AND ce."projectId"=$2`,ctx.account.id,projectId);
  const linksByObject=new Map<string,typeof links>();for(const l of links)linksByObject.set(l.spatialObjectId,[...(linksByObject.get(l.spatialObjectId)||[]),l]);
  const groups=new Map<string,typeof revisions>();for(const r of revisions){const k=`${r.drawingSetId}|${r.sheetNumber}`;groups.set(k,[...(groups.get(k)||[]),r]);}
  const rows:Array<{previous:any;current:any|null;classification:string;confidence:number;link:(typeof links)[number];oldBasis:number;targetBasis:number;newLineQty:number;materialDelta:number;laborCostDelta:number;sheet:string;revision:string;layer:string}> = [];
  for(const group of groups.values()){if(group.length<2)continue;const sorted=[...group].sort((a,b)=>(a.issuedAt?.getTime()||a.createdAt.getTime())-(b.issuedAt?.getTime()||b.createdAt.getTime()));const previousRev=sorted.at(-2)!,currentRev=sorted.at(-1)!;const previousObjects=objects.filter(o=>o.drawingRevisionId===previousRev.id),currentObjects=objects.filter(o=>o.drawingRevisionId===currentRev.id);const matched=matchSpatialRevisions(previousObjects,currentObjects);
    for(const m of matched.matches.filter(x=>x.classification==="RESIZED"||x.classification==="MOVED_RESIZED")){for(const link of linksByObject.get(m.previous.id)||[]){const oldBasis=link.quantityBasis??measure(m.previous),targetBasis=measure(m.current);if(!(oldBasis>0))continue;const newLineQty=link.lineQuantity*(targetBasis/oldBasis),qtyDelta=newLineQty-link.lineQuantity;rows.push({previous:m.previous,current:m.current,classification:m.classification,confidence:m.confidence,link,oldBasis,targetBasis,newLineQty,materialDelta:qtyDelta*link.materialCost,laborCostDelta:qtyDelta*link.laborHoursPerUnit*link.laborRate,sheet:currentRev.sheetNumber,revision:`${previousRev.revision} → ${currentRev.revision}`,layer:layers.find(x=>x.id===m.current.layerId)?.name||"—"});}}
    for(const removed of matched.removed){for(const link of linksByObject.get(removed.id)||[]){const oldBasis=link.quantityBasis??measure(removed);if(!(oldBasis>0))continue;const newLineQty=0,qtyDelta=-link.lineQuantity;rows.push({previous:removed,current:null,classification:"REMOVED",confidence:1,link,oldBasis,targetBasis:0,newLineQty,materialDelta:qtyDelta*link.materialCost,laborCostDelta:qtyDelta*link.laborHoursPerUnit*link.laborRate,sheet:currentRev.sheetNumber,revision:`${previousRev.revision} → ${currentRev.revision}`,layer:layers.find(x=>x.id===removed.layerId)?.name||"—"});}}
  }
  const editable=rows.filter(r=>r.link.estimateStatus==="DRAFT"||r.link.estimateStatus==="REVIEW"),controlled=rows.length-editable.length,totalMaterial=rows.reduce((n,r)=>n+r.materialDelta,0),totalLabor=rows.reduce((n,r)=>n+r.laborCostDelta,0);
  return <div className="space-y-5"><section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Commercial Change Gate</p><h1 className="stratum-sheet-title">{project.name} Drawing Impact Review</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Drawing deltas never modify pricing automatically. Verified matched scope can be explicitly propagated only into editable DRAFT/REVIEW estimates. Controlled commercial snapshots require a new estimate revision.</p></div><div className="flex gap-2"><Link href={`/projects/${projectId}/drawings/revision-delta`} className="btn-secondary">Revision Delta</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link></div></div></section>
    <section className="grid gap-3 md:grid-cols-4"><div className="stratum-sheet"><div className="cat">Actionable changes</div><div className="mt-2 text-2xl font-semibold text-[#DCEBF5]">{rows.length}</div></div><div className="stratum-sheet"><div className="cat">Editable</div><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{editable.length}</div></div><div className="stratum-sheet"><div className="cat">Controlled</div><div className="mt-2 text-2xl font-semibold text-[#E0954F]">{controlled}</div></div><div className="stratum-sheet"><div className="cat">Indicative direct Δ</div><div className="mt-2 font-mono text-lg text-[#DCEBF5]">${(totalMaterial+totalLabor).toFixed(2)}</div><div className="cat">Material ${totalMaterial.toFixed(2)} · labor ${totalLabor.toFixed(2)}</div></div></section>
    <section className="stratum-sheet">{rows.length===0?<div className="empty-state">No linked resized or removed drawing scope currently requires commercial review.</div>:<div className="table-scroll"><table className="min-w-[1450px]"><thead><tr><th>Change</th><th>Sheet</th><th>Object</th><th>Layer</th><th>Estimate line</th><th>Status</th><th className="num">Basis</th><th className="num">Line qty</th><th className="num">Material Δ</th><th className="num">Labor Δ</th><th>Review</th></tr></thead><tbody>{rows.map((r,i)=>{const editableStatus=r.link.estimateStatus==="DRAFT"||r.link.estimateStatus==="REVIEW";const verified=r.current?!!r.current.verifiedAt:true;return <tr key={`${r.previous.id}-${r.link.estimateLineId}-${i}`}><td><span className={r.classification==="REMOVED"?"text-rose-400":"text-amber-300"}>{r.classification.replace("_"," + ")}</span><div className="cat">Match {Math.round(r.confidence*100)}%</div></td><td>{r.sheet}<div className="cat">Rev {r.revision}</div></td><td>{r.current?.name||r.previous.name}</td><td>{r.layer}</td><td><Link href={`/costing/estimates/${r.link.estimateId}/spatial`} className="text-[#6FD6C9]">EST-{String(r.link.estimateNumber).padStart(4,"0")}</Link><div className="max-w-[260px] truncate text-xs text-[#9CB2C2]">{r.link.description}</div></td><td>{r.link.estimateStatus}</td><td className="num">{r.oldBasis.toFixed(2)} → {r.targetBasis.toFixed(2)}</td><td className="num">{r.link.lineQuantity.toFixed(2)} → {r.newLineQty.toFixed(2)}</td><td className={`num ${r.materialDelta>=0?"text-[#E0954F]":"text-[#6FD6C9]"}`}>{r.materialDelta>=0?"+":""}${r.materialDelta.toFixed(2)}</td><td className={`num ${r.laborCostDelta>=0?"text-[#E0954F]":"text-[#6FD6C9]"}`}>{r.laborCostDelta>=0?"+":""}${r.laborCostDelta.toFixed(2)}</td><td>{!editableStatus?<span className="cat">Create estimate revision</span>:!verified?<span className="cat">Verify current takeoff first</span>:<form action={applySpatialCommercialDeltaAction.bind(null,projectId)}><input type="hidden" name="previousObjectId" value={r.previous.id}/><input type="hidden" name="currentObjectId" value={r.current?.id||""}/><input type="hidden" name="estimateLineId" value={r.link.estimateLineId}/><button className="btn small">Apply reviewed delta</button></form>}</td></tr>})}</tbody></table></div>}</section></div>;
}
