import Link from "next/link";
import { notFound } from "next/navigation";

const tools: Record<string,{label:string;gap:string;uses:string[];launch:{href:string;label:string}[]}> = {
  "revision-impact": { label:"Revision Impact", gap:"Moves beyond visual drawing comparison into commercial impact analysis.", uses:["Projects and takeoff","RFIs/RFQs","Estimates","Supplier quotes and job-cost history"], launch:[{href:"/projects",label:"Choose a project"},{href:"/costing/estimates",label:"Open estimates"}] },
  "scope-gap": { label:"Scope Gap Detection", gap:"Turns document review into an actionable completeness and risk check.", uses:["Project takeoff","Estimate line items","RFIs","RFQs and supplier scope"], launch:[{href:"/projects",label:"Choose a project"},{href:"/costing/estimates",label:"Review an estimate"}] },
  "estimate-health": { label:"Estimate Health", gap:"Adds bid-risk and estimate-readiness intelligence to estimating workflows.", uses:["Estimate lines/adders","Cost library","Supplier quote freshness","RFI status and historical actuals"], launch:[{href:"/costing/estimates",label:"Choose an estimate"},{href:"/costing/items",label:"Review cost library"}] },
  "bid-leveling": { label:"Bid Leveling", gap:"Removes the spreadsheet-heavy handoff between quote collection and award decisions.", uses:["Supplier quotes","RFQs","Exclusions/alternates","Lead time and pricing"], launch:[{href:"/costing/quotes",label:"Open supplier quotes"},{href:"/suppliers",label:"Open suppliers"}] },
  "procurement-risk": { label:"Procurement Risk", gap:"Connects pricing and procurement timing to project commercial risk.", uses:["RFQ status","Quote expiration","Supplier dependencies","Project schedules and estimate exposure"], launch:[{href:"/suppliers",label:"Open suppliers"},{href:"/projects",label:"Choose a project"}] },
  "historical-benchmark": { label:"Historical Benchmark", gap:"Closes the loop from estimate to actuals so future estimates learn from project history.", uses:["Job-cost actuals","Cost library","Estimate assumptions","Supplier history"], launch:[{href:"/costing/job-costs",label:"Open job costs"},{href:"/costing/estimates",label:"Compare estimates"}] },
  "progress-intelligence": { label:"Progress Intelligence", gap:"Bridges takeoff quantities with production, cost variance and forecast-to-complete workflows.", uses:["Estimated quantity","Installed/actual quantity","Labor actuals","Material actuals"], launch:[{href:"/costing/job-costs",label:"Open job costs"},{href:"/projects",label:"Choose a project"}] },
};

export default async function EdgeToolPage({params}:{params:Promise<{tool:string}>}){
  const {tool}=await params; const data=tools[tool]; if(!data) notFound();
  return <div className="space-y-5"><Link href="/edge" className="font-mono text-[10px] uppercase tracking-[.08em] text-[#6FD6C9]">← STRATUM Edge</Link><section className="stratum-sheet"><div className="font-mono text-[10px] uppercase tracking-[.12em] text-[#E0954F]">STRATUM Edge</div><h1 className="mt-2 text-2xl font-semibold text-[#DCEBF5]">{data.label}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#9FB6C7]">{data.gap}</p></section><div className="grid gap-4 lg:grid-cols-2"><section className="stratum-sheet"><h2 className="font-mono text-[11px] uppercase tracking-[.08em] text-[#6FD6C9]">What this uses</h2><div className="mt-3 space-y-2">{data.uses.map((v)=><div key={v} className="border border-[#1C3A57] px-3 py-2 text-sm text-[#DCEBF5]">{v}</div>)}</div></section><section className="stratum-sheet"><h2 className="font-mono text-[11px] uppercase tracking-[.08em] text-[#6FD6C9]">Continue to the source workspace</h2><p className="mt-2 text-sm text-[#9FB6C7]">Choose the record set you want STRATUM Edge to work from. These links are intentionally explicit so there is no ambiguous jump.</p><div className="mt-4 flex flex-wrap gap-2">{data.launch.map((x)=><Link key={x.href+x.label} href={x.href} className="border border-[#C97C3D] px-3 py-2 text-xs font-semibold text-[#E0954F] hover:bg-[#C97C3D] hover:text-[#0A1A2B]">{x.label} →</Link>)}</div></section></div><section className="stratum-sheet"><div className="font-mono text-[10px] uppercase tracking-[.08em] text-[#6D8AA0]">Lifecycle</div><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-[#DCEBF5]"><span>STRATUM Edge Scan</span><b>→</b><span>Finding</span><b>→</b><span>Recommendation</span><b>→</b><span>Action</span><b>→</b><span className="text-[#6FD6C9]">STRATUM Edge Verified</span></div></section></div>;
}
