import { randomUUID } from "crypto";
import { db } from "@/lib/db";

export type RealityCaptureSpaceRow={id:string;projectId:string;accountId:string;provider:string;name:string;modelId:string|null;externalUrl:string;embedUrl:string|null;capturedAt:Date|null;status:string;description:string|null;createdAt:Date;updatedAt:Date};
export type SpatialAnnotationRow={id:string;projectId:string;accountId:string;contextType:string;drawingRevisionId:string|null;realityCaptureSpaceId:string|null;spatialObjectId:string|null;annotationType:string;title:string;body:string|null;status:string;priority:string;geometryJson:unknown;matterportPoseJson:unknown;assignedToId:string|null;dueAt:Date|null;linkedEntityType:string|null;linkedEntityId:string|null;createdById:string|null;resolvedById:string|null;resolvedAt:Date|null;createdAt:Date;updatedAt:Date};

export async function getRealityCaptureSpaces(projectId:string,accountId:string){return db.$queryRawUnsafe<RealityCaptureSpaceRow[]>(`SELECT * FROM "RealityCaptureSpace" WHERE "projectId"=$1 AND "accountId"=$2 ORDER BY "capturedAt" DESC NULLS LAST,"createdAt" DESC`,projectId,accountId);}
export async function getSpatialAnnotations(projectId:string,accountId:string){return db.$queryRawUnsafe<SpatialAnnotationRow[]>(`SELECT * FROM "SpatialAnnotation" WHERE "projectId"=$1 AND "accountId"=$2 ORDER BY CASE "status" WHEN 'OPEN' THEN 0 WHEN 'IN_REVIEW' THEN 1 ELSE 2 END, CASE "priority" WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,"updatedAt" DESC`,projectId,accountId);}

export async function createRealityCaptureSpace(input:{projectId:string;accountId:string;provider?:string;name:string;modelId?:string|null;externalUrl:string;embedUrl?:string|null;capturedAt?:Date|null;description?:string|null;createdById?:string|null}){const id=randomUUID();await db.$executeRawUnsafe(`INSERT INTO "RealityCaptureSpace" ("id","projectId","accountId","provider","name","modelId","externalUrl","embedUrl","capturedAt","description","createdById","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,CURRENT_TIMESTAMP)`,id,input.projectId,input.accountId,input.provider||"MATTERPORT",input.name,input.modelId??null,input.externalUrl,input.embedUrl??null,input.capturedAt??null,input.description??null,input.createdById??null);return id;}

export async function createSpatialAnnotation(input:{projectId:string;accountId:string;contextType:string;drawingRevisionId?:string|null;realityCaptureSpaceId?:string|null;spatialObjectId?:string|null;annotationType?:string;title:string;body?:string|null;priority?:string;geometryJson?:unknown;matterportPoseJson?:unknown;linkedEntityType?:string|null;linkedEntityId?:string|null;createdById?:string|null}){const id=randomUUID();await db.$executeRawUnsafe(`INSERT INTO "SpatialAnnotation" ("id","projectId","accountId","contextType","drawingRevisionId","realityCaptureSpaceId","spatialObjectId","annotationType","title","body","priority","geometryJson","matterportPoseJson","linkedEntityType","linkedEntityId","createdById","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14,$15,$16,CURRENT_TIMESTAMP)`,id,input.projectId,input.accountId,input.contextType,input.drawingRevisionId??null,input.realityCaptureSpaceId??null,input.spatialObjectId??null,input.annotationType||"NOTE",input.title,input.body??null,input.priority||"NORMAL",JSON.stringify(input.geometryJson??null),JSON.stringify(input.matterportPoseJson??null),input.linkedEntityType??null,input.linkedEntityId??null,input.createdById??null);return id;}

export async function updateAnnotationState(input:{annotationId:string;accountId:string;userId:string;status:string;reason?:string|null}){const rows=await db.$queryRawUnsafe<SpatialAnnotationRow[]>(`SELECT * FROM "SpatialAnnotation" WHERE "id"=$1 AND "accountId"=$2`,input.annotationId,input.accountId);const a=rows[0];if(!a)throw new Error("Annotation not found.");await db.$transaction(async tx=>{await tx.$executeRawUnsafe(`INSERT INTO "SpatialAnnotationRevision" ("id","annotationId","accountId","title","body","status","priority","geometryJson","matterportPoseJson","reason","editedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10,$11)`,randomUUID(),a.id,input.accountId,a.title,a.body,a.status,a.priority,JSON.stringify(a.geometryJson??null),JSON.stringify(a.matterportPoseJson??null),input.reason??`Status changed to ${input.status}`,input.userId);await tx.$executeRawUnsafe(`UPDATE "SpatialAnnotation" SET "status"=$1,"resolvedById"=CASE WHEN $1='RESOLVED' THEN $2 ELSE NULL END,"resolvedAt"=CASE WHEN $1='RESOLVED' THEN CURRENT_TIMESTAMP ELSE NULL END,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=$3 AND "accountId"=$4`,input.status,input.userId,a.id,input.accountId);});}
