import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import { verifyTakeoffObjectAction } from "../actions";
import { setDrawingRevisionReviewAction } from "./actions";

type ReviewState={id:string;reviewStatus:string;reviewedAt:Date|null;reviewedById:string|null;reviewNote:string|null;reviewerName:string|null;metadataReviewCount:number};

export default async function DrawingReviewPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params;
  const ctx=await requireTenantContext();
  const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}}); if(!project) notFound();
  const [{revisions,layers,objects},reviewStates]=await Promise.all([
    getDrawingWorkspace(projectId,ctx.account.id),
    db.$queryRawUnsafe<ReviewState[]>(`SELECT r."id",r."reviewStatus",r."reviewedAt",r."reviewedById",r."reviewNote",u."name" AS "reviewerName",(SELECT COUNT(*)::int FROM "DrawingMetadataRevision" mr WHERE mr."drawingRevisionId"=r."id" AND mr."accountId"=$1) AS "metadataReviewCount" FROM "DrawingRevision" r JOIN "DrawingSet" ds ON ds."id"=r."drawingSetId" LEFT JOIN "User" u ON u."id"=r."reviewedById" WHERE r."accountId"=$1 AND ds."projectId"=$2 ORDER BY r."createdAt" DESC`,ctx.account.id,projectId),
  ]);
  const stateByRevision=new Map(reviewStates.map(r=>[r.id,r]));
  const review=objects.filter(o=>!o.verifiedAt||(o.confidence??0)<.8||((o.objectType==="LINEAR"||o.objectType==="AREA")&&!o.calibrationId));
  const critical=review.filter(o=>((o.objectType==="LINEAR"||o.objectType==="AREA")&&!o.calibrationId)||(o.confidence??0)<.7);
  const blockerCount=(revisionId:string)=>objects.filter(o=>o.drawingRevisionId===revisionId&&(!o.verifiedAt||(o.confidence??0)<.8||((o.objectType==="LINEAR"||o.objectType==="AREA")&&!o.calibrationId))).length;
  const accepted=reviewStates.filter(r=>r.reviewStatus==="ACCEPTED").length;
  const rejected=reviewStates.filter(r=>r.reviewStatus==="REJECTED").length;
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Drawing QA</p><h1 className="stratum-sheet-title">{project.name} Review Queue</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Takeoff objects are verified individually, while each drawing revision also carries a controlled acceptance decision. A revision cannot be accepted while unverified, low-confidence, or uncalibrated measured scope remains.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/drawings/revision-delta`} className="btn-secondary">Revision Delta</Link><Link href={`/projects/${projectId}/drawings/calibration`} className="btn-secondary">Calibration</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}/drawings`} className="btn-secondary">Workspace</Link></div></div></section>
    <section className="grid gap-3 sm:grid-cols-5"><div className="stratum-sheet"><div className="cat">Takeoff review</div><div className="mt-2 text-2xl font-semibold text-[#DCEBF5]">{review.length}</div></div><div className="stratum-sheet"><div className="cat">Critical</div><div className="mt-2 text-2xl font-semibold text-[#E0954F]">{critical.length}</div></div><div className="stratum-sheet"><div className="cat">Verified objects</div><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{objects.filter(o=>o.verifiedAt).length}</div></div><div className="stratum-sheet"><div className="cat">Accepted revisions</div><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{accepted}</div></div><div className="stratum-sheet"><div className="cat">Rejected revisions</div><div className="mt-2 text-2xl font-semibold text-[#E0954F]">{rejected}</div></div></section>

    <section className="stratum-sheet"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Drawing revision acceptance</h2><p className="cat mt-1">Formal revision decision is separate from individual takeoff verification.</p></div></div><div className="table-scroll mt-3"><table className="min-w-[1200px]"><thead><tr><th>Sheet</th><th>Revision</th><th>Status</th><th>QA blockers</th><th>Metadata reviews</th><th>Reviewed by</th><th>Review note</th><th>Decision</th></tr></thead><tbody>{revisions.map(rev=>{const state=stateByRevision.get(rev.id);const status=state?.reviewStatus||"PENDING";const blockers=blockerCount(rev.id);return <tr key={rev.id}><td className="desc-cell">{rev.sheetNumber}<span className="cat">{rev.sheetTitle||"Untitled"}</span></td><td>R{rev.revision}</td><td><span className={status==="ACCEPTED"?"text-[#6FD6C9]":status==="REJECTED"?"text-[#E0954F]":"text-[#9CB2C2]"}>{status}</span></td><td><span className={blockers?"text-[#E0954F]":"text-[#6FD6C9]"}>{blockers}</span></td><td>{state?.metadataReviewCount??0}</td><td>{state?.reviewerName||state?.reviewedById||"—"}{state?.reviewedAt?<span className="cat">{new Date(state.reviewedAt).toLocaleString()}</span>:null}</td><td className="desc-cell">{state?.reviewNote||"—"}</td><td><div className="grid min-w-[260px] gap-2"><form action={setDrawingRevisionReviewAction.bind(null,projectId)} className="flex gap-2"><input type="hidden" name="revisionId" value={rev.id}/><input type="hidden" name="status" value="ACCEPTED"/><input name="note" placeholder="Acceptance note (optional)" className="min-h-10 flex-1"/><button className="btn small" disabled={blockers>0}>Accept</button></form><form action={setDrawingRevisionReviewAction.bind(null,projectId)} className="flex gap-2"><input type="hidden" name="revisionId" value={rev.id}/><input type="hidden" name="status" value="REJECTED"/><input name="note" required placeholder="Reason for rejection" className="min-h-10 flex-1"/><button className="btn-secondary small">Reject</button></form>{status!=="PENDING"&&<form action={setDrawingRevisionReviewAction.bind(null,projectId)}><input type="hidden" name="revisionId" value={rev.id}/><input type="hidden" name="status" value="PENDING"/><button className="btn-secondary small w-full">Reset to pending</button></form>}</div></td></tr>})}{revisions.length===0&&<tr><td colSpan={8} className="text-center text-[#6D8AA0]">No drawing revisions registered.</td></tr>}</tbody></table></div></section>

    <section className="stratum-sheet"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Takeoff object QA</h2><p className="cat mt-1">Resolve these items before accepting their drawing revision.</p></div>{review.length===0?<div className="empty-state mt-3">No takeoff objects currently require review.</div>:<div className="table-scroll mt-3"><table className="min-w-[1050px]"><thead><tr><th>Object</th><th>Sheet</th><th>Layer</th><th>Type</th><th>Measurement</th><th>Confidence</th><th>Reason</th><th>Action</th></tr></thead><tbody>{review.map(o=>{const rev=revisions.find(r=>r.id===o.drawingRevisionId);const layer=layers.find(l=>l.id===o.layerId);const reasons:string[]=[];if(!o.verifiedAt)reasons.push("Unverified");if((o.confidence??0)<.8)reasons.push("Low confidence");if((o.objectType==="LINEAR"||o.objectType==="AREA")&&!o.calibrationId)reasons.push("No calibration snapshot");return <tr key={o.id}><td className="desc-cell">{o.name}<span className="cat">{o.description||o.source}</span></td><td>{rev?`${rev.sheetNumber} · R${rev.revision}`:"—"}</td><td>{layer?.name||"—"}</td><td>{o.objectType}</td><td className="num">{o.objectType==="COUNT"?o.quantity:(o.measurement??o.quantity)} {o.unit}</td><td>{o.confidence==null?"—":`${Math.round(o.confidence*100)}%`}</td><td><span className={reasons.some(r=>r.includes("No calibration")||r.includes("Low"))?"text-[#E0954F]":"text-[#9CB2C2]"}>{reasons.join(" · ")}</span></td><td>{o.verifiedAt?<span className="text-xs text-[#6FD6C9]">Verified</span>:<form action={verifyTakeoffObjectAction.bind(null,projectId)}><input type="hidden" name="objectId" value={o.id}/><button className="btn small">Verify</button></form>}</td></tr>})}</tbody></table></div>}</section>
  </div>;
}
