"use server";

import { randomUUID } from "crypto";
import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { logAction } from "@/lib/audit";
import { requireAccountRole } from "@/lib/session";
import { createRealityCaptureSpace } from "@/lib/spatial-context";

const s=(fd:FormData,k:string)=>String(fd.get(k)??"").trim();
function normalizeMatterport(url:string){try{const u=new URL(url);const modelId=u.searchParams.get("m")||u.pathname.split("/").filter(Boolean).pop()||null;return{modelId,embedUrl:u.toString()};}catch{return{modelId:null,embedUrl:url};}}
export async function registerRealityCaptureAction(projectId:string,formData:FormData){const ctx=await requireAccountRole("MEMBER");const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)throw new Error("Project not found in this account.");const name=s(formData,"name"),externalUrl=s(formData,"externalUrl"),provider=s(formData,"provider")||"MATTERPORT";if(!name||!externalUrl)throw new Error("Name and capture URL are required.");const normalized=provider==="MATTERPORT"?normalizeMatterport(externalUrl):{modelId:null,embedUrl:externalUrl};const id=await createRealityCaptureSpace({projectId,accountId:ctx.account.id,provider,name,modelId:normalized.modelId,externalUrl,embedUrl:normalized.embedUrl,capturedAt:s(formData,"capturedAt")?new Date(`${s(formData,"capturedAt")}T12:00:00`):null,description:s(formData,"description")||null,createdById:ctx.user.id});await logAction({organizationId:ctx.organization.id,accountId:ctx.account.id,userId:ctx.user.id,projectId,action:"reality_capture.register",detail:`Registered ${provider} spatial capture ${name} (${id})`});revalidatePath(`/projects/${projectId}/reality-capture`);revalidatePath(`/projects/${projectId}/annotations`);}
export async function createSpatialContextLinkAction(projectId:string,formData:FormData){const ctx=await requireAccountRole("MEMBER");const drawingRevisionId=s(formData,"drawingRevisionId"),realityCaptureSpaceId=s(formData,"realityCaptureSpaceId");if(!drawingRevisionId||!realityCaptureSpaceId)throw new Error("Drawing revision and reality capture are required.");const [drawings,captures]=await Promise.all([db.$queryRawUnsafe<Array<{id:string}>>(`SELECT r."id" FROM "DrawingRevision" r JOIN "DrawingSet" ds ON ds."id"=r."drawingSetId" WHERE r."id"=$1 AND r."accountId"=$2 AND ds."projectId"=$3`,drawingRevisionId,ctx.account.id,projectId),db.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "RealityCaptureSpace" WHERE "id"=$1 AND "accountId"=$2 AND "projectId"=$3`,realityCaptureSpaceId,ctx.account.id,projectId)]);if(!drawings[0]||!captures[0])throw new Error("Spatial link targets must belong to this project and account.");const poseRaw=s(formData,"matterportPoseJson");let pose:unknown=null;if(poseRaw){try{pose=JSON.parse(poseRaw);}catch{throw new Error("Matterport pose must be valid JSON.");}}await db.$executeRawUnsafe(`INSERT INTO "SpatialContextLink" ("id","projectId","accountId","drawingRevisionId","realityCaptureSpaceId","label","matterportPoseJson","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8)`,randomUUID(),projectId,ctx.account.id,drawingRevisionId,realityCaptureSpaceId,s(formData,"label")||null,JSON.stringify(pose),ctx.user.id);await logAction({organizationId:ctx.organization.id,accountId:ctx.account.id,userId:ctx.user.id,projectId,action:"spatial.context.link",detail:`Linked drawing ${drawingRevisionId} to capture ${realityCaptureSpaceId}`});revalidatePath(`/projects/${projectId}/reality-capture`);revalidatePath(`/projects/${projectId}/drawings/markup`);}
