"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createAnnotationAction } from "../annotations/actions";

type Space={id:string;name:string;embedUrl:string|null;externalUrl:string;modelId:string|null};
type Annotation={id:string;title:string;body:string|null;priority:string;status:string;matterportPoseJson:unknown;realityCaptureSpaceId:string|null};
type MatterportPose={sweep?:string;rotation?:{x:number;y:number};position?:{x:number;y:number;z:number};mode?:unknown};
type MpSdk={Camera:{pose:{subscribe:(cb:(pose:MatterportPose)=>void)=>unknown}};Sweep:{moveTo:(sweep:string,options:{rotation?:{x:number;y:number};transition?:unknown})=>Promise<unknown>}};

declare global { interface Window { MP_SDK?: {connect:(iframe:HTMLIFrameElement,key:string,unused?:string)=>Promise<MpSdk>} } }

function withKey(url:string,key:string){if(!key)return url;try{const u=new URL(url);u.searchParams.set("applicationKey",key);return u.toString();}catch{return url;}}

export default function MatterportWorkspace({projectId,space,annotations,sdkKey}:{projectId:string;space:Space;annotations:Annotation[];sdkKey:string}){
  const iframeRef=useRef<HTMLIFrameElement|null>(null);const sdkRef=useRef<MpSdk|null>(null);const [pose,setPose]=useState<MatterportPose|null>(null);const [ready,setReady]=useState(false);const [error,setError]=useState<string|null>(null);const [annotating,setAnnotating]=useState(false);
  const spaceAnnotations=useMemo(()=>annotations.filter(a=>a.realityCaptureSpaceId===space.id),[annotations,space.id]);
  useEffect(()=>{if(!sdkKey)return;let cancelled=false;const scriptId="matterport-sdk-bootstrap";let script=document.getElementById(scriptId) as HTMLScriptElement|null;const connect=async()=>{try{if(cancelled||!iframeRef.current||!window.MP_SDK)return;const sdk=await window.MP_SDK.connect(iframeRef.current,sdkKey,"");if(cancelled)return;sdkRef.current=sdk;sdk.Camera.pose.subscribe(p=>{if(!cancelled)setPose({sweep:p.sweep,rotation:p.rotation,position:p.position,mode:p.mode});});setReady(true);}catch(e){setError(e instanceof Error?e.message:"Matterport SDK connection failed.");}};
    if(script){if(window.MP_SDK)void connect();else script.addEventListener("load",connect,{once:true});}
    else{script=document.createElement("script");script.id=scriptId;script.src=`https://static.matterport.com/showcase-sdk/bootstrap/3.0.0-0-g0517b8d76c/sdk.js?applicationKey=${encodeURIComponent(sdkKey)}`;script.async=true;script.onload=()=>void connect();script.onerror=()=>setError("Matterport SDK bootstrap failed to load.");document.head.appendChild(script);}return()=>{cancelled=true;};},[sdkKey]);
  async function reopen(raw:unknown){const p=raw as MatterportPose|null;if(!p?.sweep||!sdkRef.current){setError("This annotation does not have a usable Matterport sweep pose, or the SDK is not connected.");return;}try{await sdkRef.current.Sweep.moveTo(p.sweep,{rotation:p.rotation});setError(null);}catch(e){setError(e instanceof Error?e.message:"Could not reopen Matterport viewpoint.");}}
  const action=createAnnotationAction.bind(null,projectId);
  return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
    <section className="stratum-sheet overflow-hidden"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><div className="cat">Matterport live workspace</div><h2 className="mt-1 text-sm font-semibold text-[#DCEBF5]">{space.name}</h2></div><div className="flex gap-2"><span className={`tag ${ready?"REF":""}`}>{sdkKey?(ready?"SDK CONNECTED":"SDK CONNECTING"):"SDK KEY REQUIRED"}</span><button type="button" className="btn-secondary" onClick={()=>setAnnotating(v=>!v)}>{annotating?"Cancel annotation":"Capture annotation"}</button></div></div>
      <div className="overflow-hidden border border-[#1C3A57] bg-[#07131D]"><iframe ref={iframeRef} src={withKey(space.embedUrl||space.externalUrl,sdkKey)} title={space.name} className="h-[620px] w-full" allow="fullscreen; xr-spatial-tracking" allowFullScreen/></div>
      {error&&<div className="mt-3 border border-[#6A2C2C] bg-[#1A0C0C] p-2 text-xs text-[#F0A0A0]">{error}</div>}
      {!sdkKey&&<div className="mt-3 border border-[#6A5521] bg-[#211B0D] p-3 text-xs text-[#F0D98A]">Set <span className="font-mono">NEXT_PUBLIC_MATTERPORT_SDK_KEY</span> for the deployed domain to enable live pose capture/reopen. The Matterport model remains usable as an embedded viewer without it.</div>}
    </section>
    <aside className="space-y-4">
      {annotating&&<section className="stratum-sheet"><h3 className="text-sm font-semibold text-[#DCEBF5]">New Matterport annotation</h3><p className="cat mt-1">Navigate to the exact viewpoint first. Saving captures the current sweep, camera rotation, position and view mode.</p><form action={action} className="mt-3 space-y-2"><input type="hidden" name="contextType" value="MATTERPORT"/><input type="hidden" name="realityCaptureSpaceId" value={space.id}/><input type="hidden" name="matterportPoseJson" value={pose?JSON.stringify(pose):""}/><div className="grid grid-cols-2 gap-2"><select name="annotationType" defaultValue="NOTE"><option>NOTE</option><option>ISSUE</option><option>QUESTION</option><option>CLASH</option><option>SAFETY</option><option>QUALITY</option><option>CHANGE</option><option>COMMERCIAL</option></select><select name="priority" defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><input name="title" required placeholder="Observation title"/><textarea name="body" placeholder="Observation / instruction"/><button className="btn w-full" disabled={!pose?.sweep}>Save current viewpoint</button>{pose?.sweep?<div className="font-mono text-[10px] text-[#6FD6C9]">Sweep {pose.sweep.slice(0,12)}… · rotation {pose.rotation?`${pose.rotation.x.toFixed(1)}, ${pose.rotation.y.toFixed(1)}`:"—"}</div>:<div className="cat">Waiting for a Matterport camera pose…</div>}</form></section>}
      <section className="stratum-sheet"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-[#DCEBF5]">Viewpoint annotations</h3><span className="tag REF">{spaceAnnotations.length}</span></div>{spaceAnnotations.length===0?<div className="empty-state mt-3">No Matterport annotations for this capture.</div>:<div className="mt-3 space-y-2">{spaceAnnotations.map(a=><button key={a.id} type="button" onClick={()=>void reopen(a.matterportPoseJson)} className="w-full border border-[#1C3A57] bg-[#0B1F32] p-3 text-left hover:border-[#6FD6C9]"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-[#DCEBF5]">{a.title}</span><span className="font-mono text-[9px] text-[#E0954F]">{a.priority}</span></div><div className="mt-1 text-[11px] text-[#9CB2C2]">{a.body||"No details"}</div><div className="mt-2 cat">{a.matterportPoseJson?"Reopen saved viewpoint":"No saved pose"} · {a.status}</div></button>)}</div>}</section>
    </aside>
  </div>;
}
