import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getRealityCaptureSpaces } from "@/lib/spatial-context";
import { registerRealityCaptureAction } from "./actions";

export default async function RealityCapturePage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const spaces=await getRealityCaptureSpaces(projectId,ctx.account.id);const matterport=spaces.filter(s=>s.provider==="MATTERPORT");
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Reality Capture · Matterport</p><h1 className="stratum-sheet-title">{project.name} Spatial Capture</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Register Matterport models and other 360°/reality-capture sources as project spatial context. These records can carry annotations, issues, RFIs, commercial observations, and drawing cross-reference.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/annotations`} className="btn">Annotations</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}`} className="btn-secondary">Project</Link></div></div></section>
    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Register spatial capture</h2><form action={registerRealityCaptureAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><input name="name" required placeholder="Main Building Matterport"/><select name="provider" defaultValue="MATTERPORT"><option>MATTERPORT</option><option>360_CAPTURE</option><option>POINT_CLOUD</option><option>OTHER</option></select><input name="externalUrl" type="url" required placeholder="Matterport / capture URL"/><input name="capturedAt" type="date"/><input name="description" placeholder="Level, area, capture notes" className="xl:col-span-3"/><button className="btn">Register capture</button></form></section>
    <section className="grid gap-4 xl:grid-cols-2">{spaces.length===0?<div className="empty-state xl:col-span-2">No reality-capture spaces registered yet.</div>:spaces.map(space=><div key={space.id} className="stratum-sheet"><div className="flex items-start justify-between gap-3"><div><div className="cat">{space.provider} · {space.status}</div><h2 className="mt-1 text-base font-semibold text-[#DCEBF5]">{space.name}</h2><p className="mt-1 text-xs text-[#9CB2C2]">{space.description||"No description"}</p><div className="mt-2 font-mono text-[10px] text-[#6D8AA0]">{space.modelId?`Model ${space.modelId} · `:""}{space.capturedAt?`Captured ${new Date(space.capturedAt).toISOString().slice(0,10)}`:"Capture date not recorded"}</div></div><a className="btn-secondary" href={space.externalUrl} target="_blank" rel="noreferrer">Open source</a></div>{space.provider==="MATTERPORT"&&space.embedUrl?<div className="mt-3 overflow-hidden border border-[#1C3A57] bg-[#07131D]"><iframe src={space.embedUrl} title={space.name} className="h-[420px] w-full" allow="fullscreen; xr-spatial-tracking" allowFullScreen/></div>:null}<div className="mt-3"><Link href={`/projects/${projectId}/annotations?context=MATTERPORT&spaceId=${space.id}`} className="btn">Annotate this capture</Link></div></div>)}</section>
    {matterport.length>0&&<section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Matterport integration boundary</h2><p className="mt-2 text-sm text-[#9CB2C2]">The current integration securely registers and embeds Matterport links and stores STRATUM Electric-owned annotation/traceability data in Neon. Deeper Matterport SDK pose synchronization can plug into the stored <span className="font-mono text-[#6FD6C9]">matterportPoseJson</span> field without changing the commercial data model.</p></section>}
  </div>;
}
