import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getRealityCaptureSpaces, getSpatialAnnotations } from "@/lib/spatial-context";
import { createSpatialContextLinkAction, registerRealityCaptureAction } from "./actions";
import MatterportWorkspace from "./MatterportWorkspace";

type RevisionRow={id:string;sheetNumber:string;sheetTitle:string|null;revision:string};
type LinkRow={id:string;drawingRevisionId:string;realityCaptureSpaceId:string;label:string|null;sheetNumber:string;revision:string;captureName:string};
export default async function RealityCapturePage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{spaceId?:string}>}){
  const {projectId}=await params;const sp=await searchParams;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const [spaces,annotations,revisions,contextLinks]=await Promise.all([getRealityCaptureSpaces(projectId,ctx.account.id),getSpatialAnnotations(projectId,ctx.account.id),db.$queryRawUnsafe<RevisionRow[]>(`SELECT r."id",r."sheetNumber",r."sheetTitle",r."revision" FROM "DrawingRevision" r JOIN "DrawingSet" ds ON ds."id"=r."drawingSetId" WHERE ds."projectId"=$1 AND r."accountId"=$2 ORDER BY r."createdAt" DESC`,projectId,ctx.account.id),db.$queryRawUnsafe<LinkRow[]>(`SELECT l."id",l."drawingRevisionId",l."realityCaptureSpaceId",l."label",r."sheetNumber",r."revision",c."name" AS "captureName" FROM "SpatialContextLink" l JOIN "DrawingRevision" r ON r."id"=l."drawingRevisionId" JOIN "RealityCaptureSpace" c ON c."id"=l."realityCaptureSpaceId" WHERE l."projectId"=$1 AND l."accountId"=$2 ORDER BY l."createdAt" DESC`,projectId,ctx.account.id)]);const matterport=spaces.filter(s=>s.provider==="MATTERPORT");const active=matterport.find(s=>s.id===sp.spaceId)||matterport[0]||null;const sdkKey=process.env.NEXT_PUBLIC_MATTERPORT_SDK_KEY||"";
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Reality Capture · Matterport</p><h1 className="stratum-sheet-title">{project.name} Spatial Capture</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Matterport and drawing records now share a project spatial graph: viewpoint annotations, formal RFIs, and explicit drawing↔capture cross-links retain their Neon provenance.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/annotations`} className="btn">Annotations</Link><Link href={`/projects/${projectId}/drawings/markup`} className="btn-secondary">Drawing Markup</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link></div></div></section>
    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Register spatial capture</h2><form action={registerRealityCaptureAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><input name="name" required placeholder="Main Building Matterport"/><select name="provider" defaultValue="MATTERPORT"><option>MATTERPORT</option><option>360_CAPTURE</option><option>POINT_CLOUD</option><option>OTHER</option></select><input name="externalUrl" type="url" required placeholder="Matterport / capture URL"/><input name="capturedAt" type="date"/><input name="description" placeholder="Level, area, capture notes" className="xl:col-span-3"/><button className="btn">Register capture</button></form></section>
    {matterport.length>1&&<section className="stratum-sheet"><div className="cat">Matterport spaces</div><div className="mt-2 flex flex-wrap gap-2">{matterport.map(s=><Link key={s.id} href={`/projects/${projectId}/reality-capture?spaceId=${s.id}`} className={active?.id===s.id?"btn":"btn-secondary"}>{s.name}</Link>)}</div></section>}
    {active?<MatterportWorkspace projectId={projectId} space={{id:active.id,name:active.name,embedUrl:active.embedUrl,externalUrl:active.externalUrl,modelId:active.modelId}} annotations={JSON.parse(JSON.stringify(annotations))} sdkKey={sdkKey}/>:<section className="stratum-sheet"><div className="empty-state">No Matterport capture registered yet.</div></section>}
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Drawing ↔ Matterport cross-links</h2><p className="cat">Tie field reality directly to the controlled drawing revision it represents.</p></div><span className="tag REF">{contextLinks.length} links</span></div><form action={createSpatialContextLinkAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-4"><select name="realityCaptureSpaceId" defaultValue={active?.id||""} required><option value="">Capture</option>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="drawingRevisionId" required><option value="">Drawing revision</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision} · {r.sheetTitle||"Untitled"}</option>)}</select><input name="label" placeholder="Area / room / equipment link"/><button className="btn">Create spatial link</button></form>{contextLinks.length>0&&<div className="mt-3 grid gap-2 md:grid-cols-2">{contextLinks.map(l=><div key={l.id} className="border border-[#1C3A57] bg-[#0B1F32] p-3 text-xs"><div className="font-semibold text-[#DCEBF5]">{l.captureName} ↔ {l.sheetNumber} R{l.revision}</div><div className="cat mt-1">{l.label||"Spatial cross-reference"}</div><div className="mt-2 flex gap-2"><Link href={`/projects/${projectId}/reality-capture?spaceId=${l.realityCaptureSpaceId}`} className="btn-secondary">Open capture</Link><Link href={`/projects/${projectId}/drawings/markup?revisionId=${l.drawingRevisionId}`} className="btn-secondary">Open drawing</Link></div></div>)}</div>}</section>
  </div>;
}
