import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getRealityCaptureSpaces, getSpatialAnnotations } from "@/lib/spatial-context";
import { registerRealityCaptureAction } from "./actions";
import MatterportWorkspace from "./MatterportWorkspace";

export default async function RealityCapturePage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{spaceId?:string}>}){
  const {projectId}=await params;const sp=await searchParams;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const [spaces,annotations]=await Promise.all([getRealityCaptureSpaces(projectId,ctx.account.id),getSpatialAnnotations(projectId,ctx.account.id)]);const matterport=spaces.filter(s=>s.provider==="MATTERPORT");const active=matterport.find(s=>s.id===sp.spaceId)||matterport[0]||null;const sdkKey=process.env.NEXT_PUBLIC_MATTERPORT_SDK_KEY||"";
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Reality Capture · Matterport</p><h1 className="stratum-sheet-title">{project.name} Spatial Capture</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Register Matterport models and other 360°/reality-capture sources as project spatial context. Matterport annotations can now capture and reopen the exact sweep and camera orientation when an SDK key is configured for the deployed domain.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/annotations`} className="btn">Annotations</Link><Link href={`/projects/${projectId}/drawings/markup`} className="btn-secondary">Drawing Markup</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}`} className="btn-secondary">Project</Link></div></div></section>
    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Register spatial capture</h2><form action={registerRealityCaptureAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><input name="name" required placeholder="Main Building Matterport"/><select name="provider" defaultValue="MATTERPORT"><option>MATTERPORT</option><option>360_CAPTURE</option><option>POINT_CLOUD</option><option>OTHER</option></select><input name="externalUrl" type="url" required placeholder="Matterport / capture URL"/><input name="capturedAt" type="date"/><input name="description" placeholder="Level, area, capture notes" className="xl:col-span-3"/><button className="btn">Register capture</button></form></section>
    {matterport.length>1&&<section className="stratum-sheet"><div className="cat">Matterport spaces</div><div className="mt-2 flex flex-wrap gap-2">{matterport.map(s=><Link key={s.id} href={`/projects/${projectId}/reality-capture?spaceId=${s.id}`} className={active?.id===s.id?"btn":"btn-secondary"}>{s.name}</Link>)}</div></section>}
    {active?<MatterportWorkspace projectId={projectId} space={{id:active.id,name:active.name,embedUrl:active.embedUrl,externalUrl:active.externalUrl,modelId:active.modelId}} annotations={JSON.parse(JSON.stringify(annotations))} sdkKey={sdkKey}/>:<section className="stratum-sheet"><div className="empty-state">No Matterport capture registered yet.</div></section>}
    {spaces.filter(s=>s.provider!=="MATTERPORT").length>0&&<section className="grid gap-4 xl:grid-cols-2">{spaces.filter(s=>s.provider!=="MATTERPORT").map(space=><div key={space.id} className="stratum-sheet"><div className="cat">{space.provider} · {space.status}</div><h2 className="mt-1 text-base font-semibold text-[#DCEBF5]">{space.name}</h2><p className="mt-1 text-xs text-[#9CB2C2]">{space.description||"No description"}</p><div className="mt-3 flex gap-2"><a className="btn-secondary" href={space.externalUrl} target="_blank" rel="noreferrer">Open source</a><Link href={`/projects/${projectId}/annotations?spaceId=${space.id}`} className="btn">Annotations</Link></div></div>)}</section>}
  </div>;
}
