import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import { matchSpatialRevisions } from "@/lib/revision-matching";

function measure(o:{objectType:string;quantity:number;measurement:number|null}){return o.objectType==="COUNT"?o.quantity:(o.measurement??o.quantity);}

export default async function RevisionDeltaPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const {sets,revisions,layers,objects}=await getDrawingWorkspace(projectId,ctx.account.id);
  const links=await db.$queryRawUnsafe<Array<{spatialObjectId:string;estimateLineId:string;estimateId:string;quantityBasis:number|null;description:string;materialCost:number;laborHoursPerUnit:number;estimateNumber:number}>>(`SELECT l."spatialObjectId",l."estimateLineId",ce."id" AS "estimateId",l."quantityBasis",e."description",e."materialCost",e."laborHoursPerUnit",ce."number" AS "estimateNumber" FROM "SpatialEstimateLink" l JOIN "EstimateLineItem" e ON e."id"=l."estimateLineId" JOIN "CostEstimate" ce ON ce."id"=e."estimateId" WHERE l."accountId"=$1 AND ce."projectId"=$2`,ctx.account.id,projectId);
  const linkByObject=new Map(links.map(l=>[l.spatialObjectId,l]));
  const groups=new Map<string,typeof revisions>();for(const r of revisions){const key=`${r.drawingSetId}|${r.sheetNumber}`;groups.set(key,[...(groups.get(key)||[]),r]);}
  const comparisons=Array.from(groups.values()).filter(g=>g.length>=2).map(g=>{const sorted=[...g].sort((a,b)=>(a.issuedAt?.getTime()||a.createdAt.getTime())-(b.issuedAt?.getTime()||b.createdAt.getTime()));const previous=sorted.at(-2)!;const current=sorted.at(-1)!;const prevObjects=objects.filter(o=>o.drawingRevisionId===previous.id);const curObjects=objects.filter(o=>o.drawingRevisionId===current.id);const result=matchSpatialRevisions(prevObjects,curObjects);const changed=result.matches.filter(m=>m.classification!=="UNCHANGED");const commercialDelta=[...result.added.map(o=>({o,delta:measure(o)})),...result.removed.map(o=>({o,delta:-measure(o)})),...changed.filter(x=>x.classification!=="MOVED").map(x=>({o:x.current,delta:x.measureDelta}))].reduce((sum,x)=>{const l=linkByObject.get(x.o.id);if(!l)return sum;const basis=l.quantityBasis||measure(x.o)||1;return sum+(basis?x.delta/basis:0)*l.materialCost;},0);return{previous,current,...result,changed,commercialDelta};});
  return <div className="space-y-5"><section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Revision Intelligence</p><h1 className="stratum-sheet-title">{project.name} Drawing Delta</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Automated matching separates moved, resized, moved+resized, added, and removed scope using type, layer, normalized naming, geometry proximity, and measured quantity. Matching confidence remains visible for estimator review.</p></div><div className="flex gap-2"><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}/drawings/review`} className="btn-secondary">Review Queue</Link></div></div></section>
    {comparisons.length===0?<section className="stratum-sheet"><div className="empty-state">At least two revisions of the same sheet are required for delta analysis.</div></section>:comparisons.map(c=>{const set=sets.find(s=>s.id===c.current.drawingSetId);const changedCount=c.changed.length;return <section key={c.current.id} className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">{c.current.sheetNumber} · {c.current.sheetTitle||set?.name||"Drawing"}</h2><p className="cat">Rev {c.previous.revision} → Rev {c.current.revision} · {c.matches.length} matched · {c.added.length} added · {c.removed.length} removed · {changedCount} changed</p></div><div className="text-right"><div className="cat">Linked material Δ</div><div className="font-mono text-lg text-[#E0954F]">${c.commercialDelta.toFixed(2)}</div></div></div><div className="table-scroll mt-4"><table className="min-w-[1160px]"><thead><tr><th>Classification</th><th>Object</th><th>Layer</th><th>Type</th><th className="num">Previous</th><th className="num">Current</th><th className="num">Δ</th><th className="num">Move</th><th className="num">Match</th><th>Estimate</th></tr></thead><tbody>
      {c.added.map(o=>{const l=linkByObject.get(o.id);return <tr key={`a-${o.id}`}><td className="text-[#6FD6C9]">ADDED</td><td>{o.name}</td><td>{layers.find(x=>x.id===o.layerId)?.name||"—"}</td><td>{o.objectType}</td><td className="num">0</td><td className="num">{measure(o).toFixed(2)}</td><td className="num text-[#6FD6C9]">+{measure(o).toFixed(2)}</td><td className="num">—</td><td className="num">—</td><td>{l?<Link href={`/costing/estimates/${l.estimateId}/spatial`} className="text-[#6FD6C9]">EST-{String(l.estimateNumber).padStart(4,"0")}</Link>:"—"}</td></tr>})}
      {c.removed.map(o=>{const l=linkByObject.get(o.id);return <tr key={`r-${o.id}`}><td className="text-rose-400">REMOVED</td><td>{o.name}</td><td>{layers.find(x=>x.id===o.layerId)?.name||"—"}</td><td>{o.objectType}</td><td className="num">{measure(o).toFixed(2)}</td><td className="num">0</td><td className="num text-rose-400">-{measure(o).toFixed(2)}</td><td className="num">—</td><td className="num">—</td><td>{l?<Link href={`/costing/estimates/${l.estimateId}/spatial`} className="text-[#6FD6C9]">EST-{String(l.estimateNumber).padStart(4,"0")}</Link>:"—"}</td></tr>})}
      {c.changed.map(x=>{const l=linkByObject.get(x.current.id)||linkByObject.get(x.previous.id);const tone=x.classification==="MOVED"?"text-sky-300":x.classification==="RESIZED"?"text-amber-300":"text-[#E0954F]";return <tr key={`m-${x.current.id}`}><td className={tone}>{x.classification.replace("_"," + ")}</td><td>{x.current.name}</td><td>{layers.find(y=>y.id===x.current.layerId)?.name||"—"}</td><td>{x.current.objectType}</td><td className="num">{measure(x.previous).toFixed(2)}</td><td className="num">{measure(x.current).toFixed(2)}</td><td className={`num ${tone}`}>{x.measureDelta>=0?"+":""}{x.measureDelta.toFixed(2)}</td><td className="num">{x.centroidDistance.toFixed(1)}</td><td className="num">{Math.round(x.confidence*100)}%</td><td>{l?<Link href={`/costing/estimates/${l.estimateId}/spatial`} className="text-[#6FD6C9]">EST-{String(l.estimateNumber).padStart(4,"0")}</Link>:"—"}</td></tr>})}
      {c.changed.length===0&&c.added.length===0&&c.removed.length===0&&<tr><td colSpan={10} className="text-center text-[#6D8AA0]">No material spatial changes detected.</td></tr>}
      </tbody></table></div></section>;})}</div>;
}
