import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import { matchSpatialRevisions } from "@/lib/revision-matching";

function measure(o:{objectType:string;quantity:number;measurement:number|null}){return o.objectType==="COUNT"?o.quantity:(o.measurement??o.quantity);}
type RevisionSourceIntel={drawingRevisionId:string;sourcePageNumber:number|null;documentName:string|null;documentRevision:string|null;sourceUrl:string|null;annotationCount:number;contextLinkCount:number;metadataReviewCount:number;latestMetadataReviewAt:Date|null};

export default async function RevisionDeltaPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const {sets,revisions,layers,objects}=await getDrawingWorkspace(projectId,ctx.account.id);
  const [links,sourceIntel]=await Promise.all([
    db.$queryRawUnsafe<Array<{spatialObjectId:string;estimateLineId:string;estimateId:string;quantityBasis:number|null;description:string;materialCost:number;laborHoursPerUnit:number;estimateNumber:number}>>(`SELECT l."spatialObjectId",l."estimateLineId",ce."id" AS "estimateId",l."quantityBasis",e."description",e."materialCost",e."laborHoursPerUnit",ce."number" AS "estimateNumber" FROM "SpatialEstimateLink" l JOIN "EstimateLineItem" e ON e."id"=l."estimateLineId" JOIN "CostEstimate" ce ON ce."id"=e."estimateId" WHERE l."accountId"=$1 AND ce."projectId"=$2`,ctx.account.id,projectId),
    db.$queryRawUnsafe<RevisionSourceIntel[]>(`SELECT dr."id" AS "drawingRevisionId",dr."sourcePageNumber",d."name" AS "documentName",pr."revision" AS "documentRevision",COALESCE(pr."externalUrl",d."externalUrl",dr."externalUrl") AS "sourceUrl",(SELECT COUNT(*)::int FROM "SpatialAnnotation" a WHERE a."drawingRevisionId"=dr."id" AND a."accountId"=$1) AS "annotationCount",(SELECT COUNT(*)::int FROM "SpatialContextLink" scl WHERE scl."drawingRevisionId"=dr."id" AND scl."accountId"=$1) AS "contextLinkCount",(SELECT COUNT(*)::int FROM "DrawingMetadataRevision" mr WHERE mr."drawingRevisionId"=dr."id" AND mr."accountId"=$1) AS "metadataReviewCount",(SELECT MAX(mr."createdAt") FROM "DrawingMetadataRevision" mr WHERE mr."drawingRevisionId"=dr."id" AND mr."accountId"=$1) AS "latestMetadataReviewAt" FROM "DrawingRevision" dr JOIN "DrawingSet" ds ON ds."id"=dr."drawingSetId" LEFT JOIN "ProjectDocumentRevision" pr ON pr."id"=dr."sourceDocumentRevisionId" LEFT JOIN "ProjectDocument" d ON d."id"=pr."documentId" WHERE dr."accountId"=$1 AND ds."projectId"=$2`,ctx.account.id,projectId),
  ]);
  const sourceByRevision=new Map(sourceIntel.map(x=>[x.drawingRevisionId,x]));const linkByObject=new Map(links.map(l=>[l.spatialObjectId,l]));
  const groups=new Map<string,typeof revisions>();for(const r of revisions){const key=`${r.drawingSetId}|${r.sheetNumber}`;groups.set(key,[...(groups.get(key)||[]),r]);}
  const comparisons=Array.from(groups.values()).filter(g=>g.length>=2).map(g=>{const sorted=[...g].sort((a,b)=>(a.issuedAt?.getTime()||a.createdAt.getTime())-(b.issuedAt?.getTime()||b.createdAt.getTime()));const previous=sorted.at(-2)!;const current=sorted.at(-1)!;const prevObjects=objects.filter(o=>o.drawingRevisionId===previous.id);const curObjects=objects.filter(o=>o.drawingRevisionId===current.id);const result=matchSpatialRevisions(prevObjects,curObjects);const changed=result.matches.filter(m=>m.classification!=="UNCHANGED");const commercialDelta=[...result.added.map(o=>({o,delta:measure(o)})),...result.removed.map(o=>({o,delta:-measure(o)})),...changed.filter(x=>x.classification!=="MOVED").map(x=>({o:x.current,delta:x.measureDelta}))].reduce((sum,x)=>{const l=linkByObject.get(x.o.id);if(!l)return sum;const basis=l.quantityBasis||measure(x.o)||1;return sum+(basis?x.delta/basis:0)*l.materialCost;},0);return{previous,current,previousSource:sourceByRevision.get(previous.id)||null,currentSource:sourceByRevision.get(current.id)||null,...result,changed,commercialDelta};});
  return <div className="space-y-5"><section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Revision Intelligence</p><h1 className="stratum-sheet-title">{project.name} Drawing Delta</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Spatial matching and commercial deltas are reviewed beside controlled PDF source provenance. PDF metadata review history is shown separately so title-block corrections are not confused with physical scope changes.</p></div><div className="flex gap-2"><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}/drawings/review`} className="btn-secondary">Review Queue</Link></div></div></section>
    {comparisons.length===0?<section className="stratum-sheet"><div className="empty-state">At least two revisions of the same sheet are required for delta analysis.</div></section>:comparisons.map(c=>{const set=sets.find(s=>s.id===c.current.drawingSetId);const changedCount=c.changed.length;const pageChanged=(c.previousSource?.sourcePageNumber??1)!==(c.currentSource?.sourcePageNumber??1);const titleChanged=(c.previous.sheetTitle??"").trim()!==(c.current.sheetTitle??"").trim();const sourceRevisionChanged=(c.previousSource?.documentRevision??"")!==(c.currentSource?.documentRevision??"");const metadataChanged=titleChanged||sourceRevisionChanged||pageChanged;return <section key={c.current.id} className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">{c.current.sheetNumber} · {c.current.sheetTitle||set?.name||"Drawing"}</h2><p className="cat">Rev {c.previous.revision} → Rev {c.current.revision} · {c.matches.length} matched · {c.added.length} added · {c.removed.length} removed · {changedCount} changed</p></div><div className="text-right"><div className="cat">Linked material Δ</div><div className="font-mono text-lg text-[#E0954F]">${c.commercialDelta.toFixed(2)}</div></div></div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2">{[{label:`Previous · R${c.previous.revision}`,revision:c.previous,source:c.previousSource},{label:`Current · R${c.current.revision}`,revision:c.current,source:c.currentSource}].map(x=><div key={x.revision.id} className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="cat">{x.label}</div><div className="mt-1 text-sm font-semibold text-[#DCEBF5]">{x.source?.documentName||"Drawing-native source"}{x.source?.documentRevision?` · Doc Rev ${x.source.documentRevision}`:""}</div><div className="mt-1 text-xs text-[#9CB2C2]">Controlled PDF page {x.source?.sourcePageNumber??1}</div></div>{x.source?.sourceUrl&&<a href={x.source.sourceUrl} target="_blank" rel="noreferrer" className="btn-secondary">Open PDF source</a>}</div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div className="border border-[#1C3A57] p-2"><div className="cat">Annotations</div><div className="mt-1 font-mono text-[#DCEBF5]">{x.source?.annotationCount??0}</div></div><div className="border border-[#1C3A57] p-2"><div className="cat">Matterport regions</div><div className="mt-1 font-mono text-[#DCEBF5]">{x.source?.contextLinkCount??0}</div></div><div className="border border-[#1C3A57] p-2"><div className="cat">Metadata reviews</div><div className="mt-1 font-mono text-[#DCEBF5]">{x.source?.metadataReviewCount??0}</div>{x.source?.latestMetadataReviewAt&&<div className="mt-1 text-[10px] text-[#6D8AA0]">{new Date(x.source.latestMetadataReviewAt).toLocaleDateString()}</div>}</div></div></div>)}</div>
      {metadataChanged&&<div className="mt-3 border border-[#365D72] bg-[#0A1822] px-3 py-2 text-xs text-[#B8D5E5]"><div className="font-semibold">PDF metadata delta</div><div className="mt-1">{titleChanged?`Sheet title: “${c.previous.sheetTitle||"—"}” → “${c.current.sheetTitle||"—"}”. `:""}{sourceRevisionChanged?`Controlled document revision: ${c.previousSource?.documentRevision||"—"} → ${c.currentSource?.documentRevision||"—"}. `:""}{pageChanged?`Source page: ${c.previousSource?.sourcePageNumber??1} → ${c.currentSource?.sourcePageNumber??1}.`:""}</div></div>}
      {pageChanged&&<div className="mt-3 border border-[#6A5A2C] bg-[#17150A] px-3 py-2 text-xs text-[#F6C85F]">Controlled PDF source page changed. Confirm title-block/page remapping before accepting spatial delta.</div>}
      <div className="table-scroll mt-4"><table className="min-w-[1160px]"><thead><tr><th>Classification</th><th>Object</th><th>Layer</th><th>Type</th><th className="num">Previous</th><th className="num">Current</th><th className="num">Δ</th><th className="num">Move</th><th className="num">Match</th><th>Estimate</th></tr></thead><tbody>
      {c.added.map(o=>{const l=linkByObject.get(o.id);return <tr key={`a-${o.id}`}><td className="text-[#6FD6C9]">ADDED</td><td>{o.name}</td><td>{layers.find(x=>x.id===o.layerId)?.name||"—"}</td><td>{o.objectType}</td><td className="num">0</td><td className="num">{measure(o).toFixed(2)}</td><td className="num text-[#6FD6C9]">+{measure(o).toFixed(2)}</td><td className="num">—</td><td className="num">—</td><td>{l?<Link href={`/costing/estimates/${l.estimateId}/spatial`} className="text-[#6FD6C9]">EST-{String(l.estimateNumber).padStart(4,"0")}</Link>:"—"}</td></tr>})}
      {c.removed.map(o=>{const l=linkByObject.get(o.id);return <tr key={`r-${o.id}`}><td className="text-rose-400">REMOVED</td><td>{o.name}</td><td>{layers.find(x=>x.id===o.layerId)?.name||"—"}</td><td>{o.objectType}</td><td className="num">{measure(o).toFixed(2)}</td><td className="num">0</td><td className="num text-rose-400">-{measure(o).toFixed(2)}</td><td className="num">—</td><td className="num">—</td><td>{l?<Link href={`/costing/estimates/${l.estimateId}/spatial`} className="text-[#6FD6C9]">EST-{String(l.estimateNumber).padStart(4,"0")}</Link>:"—"}</td></tr>})}
      {c.changed.map(x=>{const l=linkByObject.get(x.current.id)||linkByObject.get(x.previous.id);const tone=x.classification==="MOVED"?"text-sky-300":x.classification==="RESIZED"?"text-amber-300":"text-[#E0954F]";return <tr key={`m-${x.current.id}`}><td className={tone}>{x.classification.replace("_"," + ")}</td><td>{x.current.name}</td><td>{layers.find(y=>y.id===x.current.layerId)?.name||"—"}</td><td>{x.current.objectType}</td><td className="num">{measure(x.previous).toFixed(2)}</td><td className="num">{measure(x.current).toFixed(2)}</td><td className={`num ${tone}`}>{x.measureDelta>=0?"+":""}{x.measureDelta.toFixed(2)}</td><td className="num">{x.centroidDistance.toFixed(1)}</td><td className="num">{Math.round(x.confidence*100)}%</td><td>{l?<Link href={`/costing/estimates/${l.estimateId}/spatial`} className="text-[#6FD6C9]">EST-{String(l.estimateNumber).padStart(4,"0")}</Link>:"—"}</td></tr>})}
      {c.changed.length===0&&c.added.length===0&&c.removed.length===0&&<tr><td colSpan={10} className="text-center text-[#6D8AA0]">No material spatial changes detected.</td></tr>}
      </tbody></table></div></section>;})}</div>;
}
