import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import { calibrateDrawingAction } from "./actions";

export default async function CalibrationPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params; const ctx=await requireTenantContext(); const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}}); if(!project) notFound();
  const {revisions}=await getDrawingWorkspace(projectId,ctx.account.id);
  const calibrations=await db.$queryRawUnsafe<Array<{drawingRevisionId:string;x1:number;y1:number;x2:number;y2:number;realDistance:number;realUnit:string;scaleFactor:number;updatedAt:Date}>>(`SELECT c."drawingRevisionId",c."x1",c."y1",c."x2",c."y2",c."realDistance",c."realUnit",c."scaleFactor",c."updatedAt" FROM "DrawingCalibration" c JOIN "DrawingRevision" r ON r."id"=c."drawingRevisionId" JOIN "DrawingSet" s ON s."id"=r."drawingSetId" WHERE c."accountId"=$1 AND s."projectId"=$2 ORDER BY c."updatedAt" DESC`,ctx.account.id,projectId);
  const byRevision=new Map(calibrations.map(c=>[c.drawingRevisionId,c]));
  return <div className="space-y-5"><section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Measurement Control</p><h1 className="stratum-sheet-title">{project.name} Sheet Calibration</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Define two points in drawing coordinates and the known real-world distance between them. The derived factor is stored by drawing revision and becomes the evidence basis for geometry-derived LF/SF measurement.</p></div><div className="flex gap-2"><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}/drawings`} className="btn-secondary">Workspace</Link></div></div></section>
  <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Calibrate drawing revision</h2>{revisions.length===0?<div className="empty-state mt-3">Register a drawing revision first.</div>:<form action={calibrateDrawingAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-4 xl:grid-cols-8"><select name="drawingRevisionId" required className="md:col-span-2"><option value="">Sheet / revision</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · Rev {r.revision} · {r.sheetTitle||"Untitled"}</option>)}</select><input name="x1" type="number" step="0.001" required placeholder="X1"/><input name="y1" type="number" step="0.001" required placeholder="Y1"/><input name="x2" type="number" step="0.001" required placeholder="X2"/><input name="y2" type="number" step="0.001" required placeholder="Y2"/><input name="realDistance" type="number" step="0.001" min="0.001" required placeholder="Known distance"/><select name="realUnit" defaultValue="FT"><option>FT</option><option>IN</option><option>M</option><option>MM</option></select><button className="btn md:col-span-4 xl:col-span-8">Save calibration</button></form>}</section>
  <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Calibration register</h2>{calibrations.length===0?<div className="empty-state mt-3">No calibrated sheets yet.</div>:<div className="table-scroll mt-3"><table className="min-w-[900px]"><thead><tr><th>Sheet</th><th>Revision</th><th>Control points</th><th className="num">Known distance</th><th className="num">Scale factor</th><th>Updated</th></tr></thead><tbody>{revisions.filter(r=>byRevision.has(r.id)).map(r=>{const c=byRevision.get(r.id)!; return <tr key={r.id}><td>{r.sheetNumber} · {r.sheetTitle||"Untitled"}</td><td>Rev {r.revision}</td><td className="font-mono text-xs">({c.x1},{c.y1}) → ({c.x2},{c.y2})</td><td className="num text-[#6FD6C9]">{c.realDistance} {c.realUnit}</td><td className="num">{c.scaleFactor.toFixed(6)} {c.realUnit}/coord</td><td>{new Date(c.updatedAt).toISOString().slice(0,10)}</td></tr>;})}</tbody></table></div>}</section></div>;
}
