import { requireOrgContext } from "@/lib/session";
import { atLeast } from "@/lib/rbac";
import { NECA_META, NECA_RATES } from "@/lib/costing-data";
import { Card, PageHeader } from "@/components/ui";
import { importNecaRateAction } from "../actions";

export default async function NecaLibraryPage({ searchParams }: { searchParams: Promise<{ q?:string; unit?:string; condition?:string }> }){
  const ctx=await requireOrgContext(); const sp=await searchParams; const q=(sp.q||"").toLowerCase().trim(); const unit=sp.unit||""; const condition=sp.condition||"NORMAL"; const canImport=atLeast(ctx.role,"ADMIN");
  const filtered=NECA_RATES.map((r,index)=>({r,index})).filter(({r})=>(!q || r.description.toLowerCase().includes(q) || String(r.sourcePage).includes(q)) && (!unit || r.unit===unit));
  const units=[...new Set(NECA_RATES.map(r=>r.unit))].sort();
  return <div className="space-y-5"><PageHeader eyebrow={`${ctx.organization.name} · Reference library`} title="NECA Labor Library" subtitle={`${NECA_META.rowCount} conservative source-page-QA rows from the supplied ${NECA_META.edition} scan. The library is global/read-only; importing creates an organization-owned cost item.`}/>
    <Card className="border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>QA policy:</b> only rows retained after direct source-page review are present. This intentionally excludes thousands of uncertain OCR rows rather than allowing questionable labor values into bids.</Card>
    <Card className="p-4"><form className="grid gap-2 sm:grid-cols-[1fr_140px_190px_auto]"><input name="q" defaultValue={sp.q||""} placeholder="Search description or PDF page…" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><select name="unit" defaultValue={unit} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">All units</option>{units.map(u=><option key={u}>{u}</option>)}</select><select name="condition" defaultValue={condition} className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="NORMAL">Normal</option><option value="DIFFICULT">Difficult</option><option value="VERY_DIFFICULT">Very difficult</option></select><button className="rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold">Filter</button></form></Card>
    <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr className="border-b bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-3 py-2.5">PDF page</th><th className="px-3 py-2.5">Description</th><th className="px-3 py-2.5">Unit</th><th className="px-3 py-2.5 text-right">Normal</th><th className="px-3 py-2.5 text-right">Difficult</th><th className="px-3 py-2.5 text-right">Very difficult</th><th className="px-3 py-2.5">QA</th>{canImport&&<th/>}</tr></thead><tbody>{filtered.map(({r,index})=><tr key={`${r.sourcePage}-${index}`} className="border-b border-slate-100 last:border-0"><td className="px-3 py-2.5 font-mono text-xs text-slate-500">{r.sourcePage}</td><td className="px-3 py-2.5 font-medium text-slate-800">{r.description}</td><td className="px-3 py-2.5 font-mono text-xs">{r.unit}</td><td className="px-3 py-2.5 text-right font-mono">{r.normal}</td><td className="px-3 py-2.5 text-right font-mono">{r.difficult}</td><td className="px-3 py-2.5 text-right font-mono">{r.veryDifficult}</td><td className="px-3 py-2.5"><span className="rounded border border-emerald-300 bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">VERIFIED</span></td>{canImport&&<td className="px-3 py-2.5"><form action={importNecaRateAction}><input type="hidden" name="index" value={index}/><input type="hidden" name="condition" value={condition}/><button className="text-xs font-semibold text-signal-600">Import to org</button></form></td>}</tr>)}</tbody></table></div>{filtered.length===0&&<div className="p-10 text-center text-sm text-slate-400">No matching verified rows.</div>}</Card>
  </div>;
}
