import { requireOrgContext } from "@/lib/session";
import { db } from "@/lib/db";
import { atLeast } from "@/lib/rbac";
import { money } from "@/lib/costing";
import { Card, PageHeader } from "@/components/ui";
import { applyQuoteToItemAction, createSupplierQuoteAction } from "../actions";

export default async function QuotesPage(){
  const ctx=await requireOrgContext();
  const [quotes,suppliers,items,projects]=await Promise.all([
    db.supplierQuote.findMany({where:{organizationId:ctx.organization.id},include:{supplier:true,costItem:true,project:true},orderBy:{quoteDate:"desc"},take:250}),
    db.supplier.findMany({where:{organizationId:ctx.organization.id},orderBy:{name:"asc"}}),
    db.costItem.findMany({where:{organizationId:ctx.organization.id},orderBy:{description:"asc"}}),
    db.project.findMany({where:{organizationId:ctx.organization.id,archivedAt:null},orderBy:{name:"asc"}}),
  ]); const canApply=atLeast(ctx.role,"ADMIN");
  return <div className="space-y-5"><PageHeader eyebrow={ctx.organization.name} title="Supplier Quotes" subtitle="Current vendor pricing stays inside the active organization and can calibrate catalog material costs." />
  {atLeast(ctx.role,"MEMBER")&&<Card className="p-4"><form action={createSupplierQuoteAction} className="grid gap-2 md:grid-cols-4"><input name="description" required placeholder="Quoted item / package" className="md:col-span-2 rounded-md border border-slate-300 px-3 py-2 text-sm"/><select name="supplierId" className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">Supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="projectId" className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="costItemId" className="md:col-span-2 rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">No catalog item</option>{items.map(i=><option key={i.id} value={i.id}>{i.description}</option>)}</select><input name="quantity" type="number" step="0.01" defaultValue="1" placeholder="Qty" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="unit" defaultValue="EA" placeholder="Unit" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="unitMaterialCost" type="number" step="0.01" placeholder="Unit material $" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="quoteDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="validUntil" type="date" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="reference" placeholder="Quote # / reference" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><button className="rounded-md bg-signal-600 px-3 py-2 text-xs font-semibold text-white">Log quote</button></form></Card>}
  <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr className="border-b bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-3 py-2.5">Quote</th><th className="px-3 py-2.5">Supplier</th><th className="px-3 py-2.5">Catalog item</th><th className="px-3 py-2.5 text-right">Unit price</th><th className="px-3 py-2.5 text-right">Extended</th><th className="px-3 py-2.5">Valid until</th><th/></tr></thead><tbody>{quotes.map(q=><tr key={q.id} className="border-b border-slate-100 last:border-0"><td className="px-3 py-2.5"><div className="font-medium text-slate-800">{q.description}</div><div className="text-xs text-slate-400">{q.quoteDate.toLocaleDateString()} {q.reference?`· ${q.reference}`:""}</div></td><td className="px-3 py-2.5 text-slate-500">{q.supplier?.name||"—"}</td><td className="px-3 py-2.5 text-slate-500">{q.costItem?.description||"—"}</td><td className="px-3 py-2.5 text-right font-mono">{money(q.unitMaterialCost)}</td><td className="px-3 py-2.5 text-right font-mono font-semibold">{money(q.unitMaterialCost*q.quantity)}</td><td className="px-3 py-2.5 text-xs text-slate-500">{q.validUntil?.toLocaleDateString()||"—"}</td><td className="px-3 py-2.5">{canApply&&q.costItemId&&<form action={applyQuoteToItemAction}><input type="hidden" name="quoteId" value={q.id}/><button className="text-xs font-semibold text-signal-600">Apply price</button></form>}</td></tr>)}</tbody></table></div>{quotes.length===0&&<div className="p-10 text-center text-sm text-slate-400">No supplier quotes logged yet.</div>}</Card>
  </div>;
}
