"use client";

import { useMemo, useState } from "react";
import { createAnnotationAction } from "../../annotations/actions";

type Revision={id:string;sheetNumber:string;sheetTitle:string|null;revision:string;externalUrl:string|null;sourcePageNumber:number|null};
type Annotation={id:string;drawingRevisionId:string|null;title:string;body:string|null;priority:string;status:string;geometryJson:unknown;annotationType:string};
type Point={x:number;y:number};
function pointFrom(raw:unknown):Point|null{if(!raw||typeof raw!=="object")return null;const g=raw as {type?:string;x?:unknown;y?:unknown};return g.type==="Point"&&typeof g.x==="number"&&typeof g.y==="number"?{x:g.x,y:g.y}:null;}

export default function MarkupCanvas({projectId,revisions,annotations,initialRevisionId}:{projectId:string;revisions:Revision[];annotations:Annotation[];initialRevisionId?:string}){
  const [revisionId,setRevisionId]=useState(initialRevisionId&&revisions.some(r=>r.id===initialRevisionId)?initialRevisionId:(revisions[0]?.id||""));const [mode,setMode]=useState(false);const [point,setPoint]=useState<Point|null>(null);const [selected,setSelected]=useState<string|null>(null);
  const rev=revisions.find(r=>r.id===revisionId)||null;const pins=useMemo(()=>annotations.filter(a=>a.drawingRevisionId===revisionId).flatMap(a=>{const p=pointFrom(a.geometryJson);return p?[{...a,p}]:[];}),[annotations,revisionId]);
  const action=createAnnotationAction.bind(null,projectId);
  function place(e:React.MouseEvent<HTMLDivElement>){if(!mode)return;const r=e.currentTarget.getBoundingClientRect();if(!r.width||!r.height)return;setPoint({x:Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),y:Math.min(1,Math.max(0,(e.clientY-r.top)/r.height))});setSelected(null);}
  return <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)_340px]">
    <aside className="stratum-sheet h-fit space-y-4"><div><div className="cat">Drawing revision</div><select className="mt-1 w-full" value={revisionId} onChange={e=>{setRevisionId(e.target.value);setPoint(null);setSelected(null);}}>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select></div><div><div className="cat">Markup mode</div><button type="button" className={mode?"btn mt-2 w-full":"btn-secondary mt-2 w-full"} onClick={()=>{setMode(v=>!v);setPoint(null);}}>{mode?"Markup ON":"Place annotation"}</button><p className="cat mt-2">When markup is on, click the visible drawing page to place a normalized annotation pin.</p></div><div><div className="cat">Pins on sheet</div><div className="mt-1 text-2xl font-semibold text-[#DCEBF5]">{pins.length}</div></div>{rev?.externalUrl&&<a href={rev.externalUrl} target="_blank" rel="noreferrer" className="btn-secondary block text-center">Open source</a>}</aside>
    <section className="stratum-sheet overflow-hidden"><div className="mb-3"><h2 className="text-sm font-semibold text-[#DCEBF5]">{rev?`${rev.sheetNumber} · ${rev.sheetTitle||"Untitled"}`:"No drawing"}</h2><p className="cat">{rev?`Rev ${rev.revision}${rev.sourcePageNumber?` · source page ${rev.sourcePageNumber}`:""}`:"Register/ingest a drawing first"}</p></div>{!rev?<div className="empty-state">No drawing revisions available.</div>:<div className="relative h-[72vh] min-h-[560px] overflow-hidden border border-[#1C3A57] bg-[#07131D]" onClick={place}><iframe src={rev.externalUrl||"about:blank"} title={`${rev.sheetNumber} markup source`} className="absolute inset-0 h-full w-full" style={{pointerEvents:mode?"none":"auto"}}/>{mode&&<div className="absolute inset-0 cursor-crosshair bg-transparent" aria-label="Drawing annotation placement surface"/>}{pins.map(a=><button key={a.id} type="button" onClick={e=>{e.stopPropagation();setSelected(a.id);setPoint(null);}} className="absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-[#07131D] bg-[#E0954F] px-2 py-1 font-mono text-[9px] font-bold text-[#07131D] shadow" style={{left:`${a.p.x*100}%`,top:`${a.p.y*100}%`}} title={a.title}>!</button>)}{point&&<div className="absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-[#6FD6C9] px-2 py-1 font-mono text-[9px] font-bold text-[#07131D]" style={{left:`${point.x*100}%`,top:`${point.y*100}%`}}>+</div>}</div>}</section>
    <aside className="stratum-sheet h-fit">{point&&rev?<form action={action} className="space-y-2"><input type="hidden" name="contextType" value="DRAWING"/><input type="hidden" name="drawingRevisionId" value={rev.id}/><input type="hidden" name="pointX" value={point.x}/><input type="hidden" name="pointY" value={point.y}/><h3 className="text-sm font-semibold text-[#DCEBF5]">New drawing annotation</h3><div className="grid grid-cols-2 gap-2"><select name="annotationType" defaultValue="NOTE"><option>NOTE</option><option>ISSUE</option><option>QUESTION</option><option>CLASH</option><option>SAFETY</option><option>QUALITY</option><option>CHANGE</option><option>COMMERCIAL</option></select><select name="priority" defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><input name="title" required placeholder="Markup title"/><textarea name="body" placeholder="Comment / instruction"/><button className="btn w-full">Save annotation pin</button><div className="cat">Normalized position {(point.x*100).toFixed(1)}%, {(point.y*100).toFixed(1)}%</div></form>:selected?(()=>{const a=pins.find(x=>x.id===selected);return a?<div><div className="flex items-center justify-between gap-2"><span className="tag REF">{a.annotationType}</span><span className="font-mono text-[10px] text-[#E0954F]">{a.priority}</span></div><h3 className="mt-3 text-sm font-semibold text-[#DCEBF5]">{a.title}</h3><p className="mt-2 text-xs text-[#9CB2C2]">{a.body||"No details"}</p><div className="mt-3 cat">{a.status}</div></div>:null})():<div className="empty-state">Turn on markup and click the drawing to place a pin, or select an existing pin.</div>}</aside>
  </div>;
}
