"use client";

import { useMemo, useState } from "react";
import { createAnnotationAction } from "../../annotations/actions";
import PdfPageSurface from "./PdfPageSurface";

type Revision={id:string;sheetNumber:string;sheetTitle:string|null;revision:string;externalUrl:string|null;sourcePageNumber:number|null};
type Annotation={id:string;drawingRevisionId:string|null;title:string;body:string|null;priority:string;status:string;geometryJson:unknown;annotationType:string};
type Point={x:number;y:number};
type Geometry={type:"Point";x:number;y:number}|{type:"Arrow"|"Rectangle"|"Cloud";x1:number;y1:number;x2:number;y2:number};
function geometryFrom(raw:unknown):Geometry|null{if(!raw||typeof raw!=="object")return null;const g=raw as Record<string,unknown>;if(g.type==="Point"&&typeof g.x==="number"&&typeof g.y==="number")return{type:"Point",x:g.x,y:g.y};if((g.type==="Arrow"||g.type==="Rectangle"||g.type==="Cloud")&&[g.x1,g.y1,g.x2,g.y2].every(v=>typeof v==="number"))return{type:g.type as "Arrow"|"Rectangle"|"Cloud",x1:g.x1 as number,y1:g.y1 as number,x2:g.x2 as number,y2:g.y2 as number};return null;}
function center(g:Geometry){return g.type==="Point"?{x:g.x,y:g.y}:{x:(g.x1+g.x2)/2,y:(g.y1+g.y2)/2};}

export default function MarkupCanvas({projectId,revisions,annotations,initialRevisionId}:{projectId:string;revisions:Revision[];annotations:Annotation[];initialRevisionId?:string}){
  const [revisionId,setRevisionId]=useState(initialRevisionId&&revisions.some(r=>r.id===initialRevisionId)?initialRevisionId:(revisions[0]?.id||""));const [tool,setTool]=useState<"SELECT"|"POINT"|"ARROW"|"RECTANGLE"|"CLOUD">("SELECT");const [start,setStart]=useState<Point|null>(null);const [geometry,setGeometry]=useState<Geometry|null>(null);const [selected,setSelected]=useState<string|null>(null);
  const rev=revisions.find(r=>r.id===revisionId)||null;const marks=useMemo(()=>annotations.filter(a=>a.drawingRevisionId===revisionId).flatMap(a=>{const g=geometryFrom(a.geometryJson);return g?[{...a,g,c:center(g)}]:[];}),[annotations,revisionId]);
  const action=createAnnotationAction.bind(null,projectId);
  function click(p:Point){if(tool==="SELECT")return;if(tool==="POINT"){setGeometry({type:"Point",...p});setStart(null);setSelected(null);return;}if(!start){setStart(p);setGeometry(null);setSelected(null);return;}setGeometry({type:tool==="ARROW"?"Arrow":tool==="RECTANGLE"?"Rectangle":"Cloud",x1:start.x,y1:start.y,x2:p.x,y2:p.y});setStart(null);}
  return <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)_340px]">
    <aside className="stratum-sheet h-fit space-y-4"><div><div className="cat">Drawing revision</div><select className="mt-1 w-full" value={revisionId} onChange={e=>{setRevisionId(e.target.value);setStart(null);setGeometry(null);setSelected(null);}}>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select></div><div><div className="cat">Markup tool</div><div className="mt-2 grid grid-cols-2 gap-2">{(["SELECT","POINT","ARROW","RECTANGLE","CLOUD"] as const).map(t=><button key={t} type="button" onClick={()=>{setTool(t);setStart(null);setGeometry(null);}} className={tool===t?"btn":"btn-secondary"}>{t}</button>)}</div><p className="cat mt-2">Point uses one click. Arrow, rectangle and cloud use two clicks.</p></div><div><div className="cat">Marks on sheet</div><div className="mt-1 text-2xl font-semibold text-[#DCEBF5]">{marks.length}</div></div>{rev?.externalUrl&&<a href={rev.externalUrl} target="_blank" rel="noreferrer" className="btn-secondary block text-center">Open source</a>}</aside>
    <section className="stratum-sheet overflow-hidden"><div className="mb-3"><h2 className="text-sm font-semibold text-[#DCEBF5]">{rev?`${rev.sheetNumber} · ${rev.sheetTitle||"Untitled"}`:"No drawing"}</h2><p className="cat">{rev?`Rev ${rev.revision}${rev.sourcePageNumber?` · source page ${rev.sourcePageNumber}`:""}`:"Register/ingest a drawing first"}</p></div>{!rev?<div className="empty-state">No drawing revisions available.</div>:<PdfPageSurface url={rev.externalUrl} pageNumber={rev.sourcePageNumber||1} interactive={tool!=="SELECT"} onPoint={click} marks={marks.map(m=>({id:m.id,title:m.title,geometry:m.g,selected:selected===m.id}))} onSelect={id=>{setSelected(id);setGeometry(null);setStart(null);}} draft={geometry} start={start}/>}</section>
    <aside className="stratum-sheet h-fit">{geometry&&rev?<form action={action} className="space-y-2"><input type="hidden" name="contextType" value="DRAWING"/><input type="hidden" name="drawingRevisionId" value={rev.id}/><input type="hidden" name="geometryJson" value={JSON.stringify(geometry)}/><h3 className="text-sm font-semibold text-[#DCEBF5]">New drawing annotation</h3><div className="cat">{geometry.type} markup</div><div className="grid grid-cols-2 gap-2"><select name="annotationType" defaultValue="NOTE"><option>NOTE</option><option>ISSUE</option><option>QUESTION</option><option>CLASH</option><option>SAFETY</option><option>QUALITY</option><option>CHANGE</option><option>COMMERCIAL</option></select><select name="priority" defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><input name="title" required placeholder="Markup title"/><textarea name="body" placeholder="Comment / instruction"/><button className="btn w-full">Save markup</button></form>:selected?(()=>{const a=marks.find(x=>x.id===selected);return a?<div><div className="flex items-center justify-between gap-2"><span className="tag REF">{a.annotationType}</span><span className="font-mono text-[10px] text-[#E0954F]">{a.priority}</span></div><h3 className="mt-3 text-sm font-semibold text-[#DCEBF5]">{a.title}</h3><p className="mt-2 text-xs text-[#9CB2C2]">{a.body||"No details"}</p><div className="mt-3 cat">{a.status} · {a.g.type}</div></div>:null})():start?<div className="empty-state">Choose the second point to finish the {tool.toLowerCase()} markup.</div>:<div className="empty-state">Choose a markup tool and place it on the rendered PDF page, or select an existing markup.</div>}</aside>
  </div>;
}
