"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createAnnotationAction } from "../../annotations/actions";
import { saveDrawingViewAction } from "./actions";
import PdfPageSurface,{type Geometry,type Point} from "./PdfPageSurface";

type Revision={id:string;sheetNumber:string;sheetTitle:string|null;revision:string;externalUrl:string|null;sourcePageNumber:number|null;rotationDegrees:number;cropJson:unknown};
type Annotation={id:string;drawingRevisionId:string|null;title:string;body:string|null;priority:string;status:string;geometryJson:unknown;annotationType:string;assignedToId?:string|null;linkedEntityType?:string|null};
type Tool="SELECT"|"POINT"|"ARROW"|"RECTANGLE"|"CLOUD"|"POLYGON"|"FREEHAND"|"TEXT";
function validPoint(v:unknown):v is Point{return !!v&&typeof v==="object"&&typeof (v as Point).x==="number"&&typeof (v as Point).y==="number";}
function geometryFrom(raw:unknown):Geometry|null{if(!raw||typeof raw!=="object")return null;const g=raw as Record<string,unknown>;if(g.type==="Point"&&typeof g.x==="number"&&typeof g.y==="number")return{type:"Point",x:g.x,y:g.y};if(g.type==="Text"&&typeof g.x==="number"&&typeof g.y==="number")return{type:"Text",x:g.x,y:g.y};if((g.type==="Arrow"||g.type==="Rectangle"||g.type==="Cloud")&&[g.x1,g.y1,g.x2,g.y2].every(v=>typeof v==="number"))return{type:g.type as "Arrow"|"Rectangle"|"Cloud",x1:g.x1 as number,y1:g.y1 as number,x2:g.x2 as number,y2:g.y2 as number};if((g.type==="Polygon"||g.type==="Freehand")&&Array.isArray(g.points)&&g.points.every(validPoint))return{type:g.type as "Polygon"|"Freehand",points:g.points as Point[]};return null;}

export default function MarkupCanvas({projectId,revisions,annotations,initialRevisionId,contextGeometry=null,contextLabel=null}:{projectId:string;revisions:Revision[];annotations:Annotation[];initialRevisionId?:string;contextGeometry?:unknown;contextLabel?:string|null}){
  const router=useRouter();const [viewPending,startViewTransition]=useTransition();
  const initialId=initialRevisionId&&revisions.some(r=>r.id===initialRevisionId)?initialRevisionId:(revisions[0]?.id||"");
  const [revisionId,setRevisionId]=useState(initialId);const initialRevision=revisions.find(r=>r.id===initialId)||null;const [rotationChoice,setRotationChoice]=useState(initialRevision?.rotationDegrees||0);const [viewError,setViewError]=useState<string|null>(null);
  const [tool,setTool]=useState<Tool>("SELECT");const [start,setStart]=useState<Point|null>(null);const [geometry,setGeometry]=useState<Geometry|null>(null);const [polygonPoints,setPolygonPoints]=useState<Point[]>([]);const [selected,setSelected]=useState<string|null>(null);
  const [statusFilter,setStatusFilter]=useState("ACTIVE");const [priorityFilter,setPriorityFilter]=useState("ALL");const [typeFilter,setTypeFilter]=useState("ALL");const [rfiOnly,setRfiOnly]=useState(false);
  const rev=revisions.find(r=>r.id===revisionId)||null;const linkedRegion=useMemo(()=>geometryFrom(contextGeometry),[contextGeometry]);
  const marks=useMemo(()=>annotations.filter(a=>a.drawingRevisionId===revisionId).filter(a=>statusFilter==="ALL"||(statusFilter==="ACTIVE"?(a.status==="OPEN"||a.status==="IN_REVIEW"):a.status===statusFilter)).filter(a=>priorityFilter==="ALL"||a.priority===priorityFilter).filter(a=>typeFilter==="ALL"||a.annotationType===typeFilter).filter(a=>!rfiOnly||a.linkedEntityType==="RFI").flatMap(a=>{const g=geometryFrom(a.geometryJson);return g?[{...a,g}]:[];}),[annotations,revisionId,statusFilter,priorityFilter,typeFilter,rfiOnly]);const action=createAnnotationAction.bind(null,projectId);
  function resetDraft(){setStart(null);setGeometry(null);setPolygonPoints([]);setSelected(null);}
  function choose(t:Tool){setTool(t);resetDraft();}
  function click(p:Point){if(tool==="SELECT"||tool==="FREEHAND")return;if(tool==="POINT"){setGeometry({type:"Point",...p});setSelected(null);return;}if(tool==="TEXT"){setGeometry({type:"Text",...p});setSelected(null);return;}if(tool==="POLYGON"){setPolygonPoints(v=>[...v,p]);setGeometry(null);setSelected(null);return;}if(!start){setStart(p);setGeometry(null);setSelected(null);return;}setGeometry({type:tool==="ARROW"?"Arrow":tool==="RECTANGLE"?"Rectangle":"Cloud",x1:start.x,y1:start.y,x2:p.x,y2:p.y});setStart(null);}
  function finishPolygon(){if(polygonPoints.length<3)return;setGeometry({type:"Polygon",points:polygonPoints});setPolygonPoints([]);}
  function selectRevision(nextId:string){setRevisionId(nextId);const next=revisions.find(r=>r.id===nextId);setRotationChoice(next?.rotationDegrees||0);setViewError(null);resetDraft();}
  function saveCanonicalRotation(){if(!rev)return;setViewError(null);startViewTransition(()=>{saveDrawingViewAction(projectId,rev.id,{rotationDegrees:rotationChoice,cropJson:rev.cropJson}).then(()=>router.refresh()).catch(e=>setViewError(e instanceof Error?e.message:"Unable to save canonical drawing view."));});}
  const visibleDraft=geometry||(polygonPoints.length>=2?{type:"Freehand",points:polygonPoints} as Geometry:null)||linkedRegion;
  return <div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)_340px]">
    <aside className="stratum-sheet h-fit space-y-4 xl:sticky xl:top-4"><div><div className="cat">Drawing revision</div><select className="mt-1 w-full min-h-11" value={revisionId} onChange={e=>selectRevision(e.target.value)}>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select></div>
      {rev&&<div className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="cat">Canonical sheet rotation</div><div className="mt-2 grid grid-cols-4 gap-2">{([0,90,180,270] as const).map(deg=><button key={deg} type="button" disabled={viewPending} onClick={()=>setRotationChoice(deg)} className={`${rotationChoice===deg?"btn":"btn-secondary"} min-h-11`}>{deg}°</button>)}</div><button type="button" disabled={viewPending||rotationChoice===rev.rotationDegrees} onClick={saveCanonicalRotation} className="btn mt-2 w-full min-h-11">{viewPending?"Saving…":"Save canonical rotation"}</button><p className="cat mt-2">Rotation is locked after spatial annotations, takeoff geometry, or Matterport regions exist. Use a new controlled revision instead of invalidating evidence.</p>{viewError&&<div className="mt-2 border border-[#6A2C2C] bg-[#1A0C0C] p-2 text-xs text-[#F0A0A0]">{viewError}</div>}</div>}
      {linkedRegion&&<div className="border border-[#2B776F] bg-[#0B2827] p-3 text-xs text-[#A8E5DC]"><div className="font-semibold">Linked field region</div><div className="mt-1">{contextLabel||"Matterport spatial context"}</div><div className="mt-1 font-mono text-[10px]">Shown as the active teal drawing region until you begin a new markup.</div></div>}
      <div><div className="cat">Field visibility</div><div className="mt-2 grid grid-cols-2 gap-2"><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="min-h-11"><option value="ACTIVE">Active</option><option value="ALL">All status</option><option>OPEN</option><option>IN_REVIEW</option><option>RESOLVED</option><option>VOID</option></select><select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)} className="min-h-11"><option value="ALL">All priority</option><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} className="min-h-11 col-span-2"><option value="ALL">All annotation types</option><option>NOTE</option><option>ISSUE</option><option>QUESTION</option><option>CLASH</option><option>SAFETY</option><option>QUALITY</option><option>CHANGE</option><option>COMMERCIAL</option></select><button type="button" onClick={()=>setRfiOnly(v=>!v)} className={rfiOnly?"btn col-span-2 min-h-11":"btn-secondary col-span-2 min-h-11"}>RFI-linked only</button></div></div>
      <div><div className="cat">Markup tool</div><div className="mt-2 grid grid-cols-2 gap-2">{(["SELECT","POINT","ARROW","RECTANGLE","CLOUD","POLYGON","FREEHAND","TEXT"] as Tool[]).map(t=><button key={t} type="button" onClick={()=>choose(t)} className={`${tool===t?"btn":"btn-secondary"} min-h-12`}>{t}</button>)}</div>{tool==="POLYGON"&&<button type="button" className="btn mt-2 w-full min-h-12" disabled={polygonPoints.length<3} onClick={finishPolygon}>Finish polygon ({polygonPoints.length})</button>}</div><div><div className="cat">Visible marks</div><div className="mt-1 text-2xl font-semibold text-[#DCEBF5]">{marks.length}</div></div>{rev?.externalUrl&&<a href={rev.externalUrl} target="_blank" rel="noreferrer" className="btn-secondary block min-h-11 text-center">Open source</a>}</aside>
    <section className="stratum-sheet overflow-hidden"><div className="mb-3"><h2 className="text-sm font-semibold text-[#DCEBF5]">{rev?`${rev.sheetNumber} · ${rev.sheetTitle||"Untitled"}`:"No drawing"}</h2><p className="cat">{rev?`Rev ${rev.revision}${rev.sourcePageNumber?` · source page ${rev.sourcePageNumber}`:""} · canonical rotation ${rev.rotationDegrees||0}°`:"Register/ingest a drawing first"}</p></div>{!rev?<div className="empty-state">No drawing revisions available.</div>:<PdfPageSurface url={rev.externalUrl} pageNumber={rev.sourcePageNumber||1} initialRotation={((rev.rotationDegrees||0)%360) as 0|90|180|270} interactive={tool!=="SELECT"} freehandMode={tool==="FREEHAND"} onFreehand={points=>{setGeometry({type:"Freehand",points});setSelected(null);}} onPoint={click} marks={marks.map(m=>({id:m.id,title:m.title,geometry:m.g,selected:selected===m.id}))} onSelect={id=>{setSelected(id);setGeometry(null);setStart(null);setPolygonPoints([]);}} draft={visibleDraft} start={start}/>}</section>
    <aside className="stratum-sheet h-fit max-xl:fixed max-xl:inset-x-3 max-xl:bottom-3 max-xl:z-40 max-xl:max-h-[46vh] max-xl:overflow-auto xl:sticky xl:top-4">{geometry&&rev?<form action={action} className="space-y-2"><input type="hidden" name="contextType" value="DRAWING"/><input type="hidden" name="drawingRevisionId" value={rev.id}/><input type="hidden" name="geometryJson" value={JSON.stringify(geometry)}/><h3 className="text-sm font-semibold text-[#DCEBF5]">New drawing annotation</h3><div className="cat">{geometry.type} markup</div><div className="grid grid-cols-2 gap-2"><select name="annotationType" defaultValue="NOTE" className="min-h-11"><option>NOTE</option><option>ISSUE</option><option>QUESTION</option><option>CLASH</option><option>SAFETY</option><option>QUALITY</option><option>CHANGE</option><option>COMMERCIAL</option></select><select name="priority" defaultValue="NORMAL" className="min-h-11"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></div><input name="title" required placeholder={geometry.type==="Text"?"Text callout":"Markup title"} className="min-h-11"/><textarea name="body" placeholder="Comment / instruction"/><button className="btn w-full min-h-12">Save markup</button></form>:selected?(()=>{const a=marks.find(x=>x.id===selected);return a?<div><div className="flex items-center justify-between gap-2"><span className="tag REF">{a.annotationType}</span><span className="font-mono text-[10px] text-[#E0954F]">{a.priority}</span></div><h3 className="mt-3 text-sm font-semibold text-[#DCEBF5]">{a.title}</h3><p className="mt-2 text-xs text-[#9CB2C2]">{a.body||"No details"}</p><div className="mt-3 cat">{a.status} · {a.g.type}{a.linkedEntityType==="RFI"?" · RFI LINKED":""}</div></div>:null})():polygonPoints.length?<div className="empty-state">Polygon has {polygonPoints.length} points. Add more, then Finish.</div>:start?<div className="empty-state">Choose the second point to finish the {tool.toLowerCase()} markup.</div>:linkedRegion?<div className="empty-state">Linked Matterport region is highlighted. Select an existing annotation or choose a markup tool to add field intelligence.</div>:<div className="empty-state">Choose a markup tool and place it on the rendered PDF page, or select an existing markup.</div>}</aside>
  </div>;
}