"use client";

import { useEffect, useRef, useState } from "react";

type Point={x:number;y:number};
type Geometry={type:"Point";x:number;y:number}|{type:"Arrow"|"Rectangle"|"Cloud";x1:number;y1:number;x2:number;y2:number};
type Mark={id:string;title:string;geometry:Geometry;selected:boolean};

function center(g:Geometry){return g.type==="Point"?{x:g.x,y:g.y}:{x:(g.x1+g.x2)/2,y:(g.y1+g.y2)/2};}
export default function PdfPageSurface({url,pageNumber,interactive,onPoint,marks,onSelect,draft,start}:{url:string|null;pageNumber:number;interactive:boolean;onPoint:(p:Point)=>void;marks:Mark[];onSelect:(id:string)=>void;draft:Geometry|null;start:Point|null}){
  const canvasRef=useRef<HTMLCanvasElement|null>(null);const [state,setState]=useState<"LOADING"|"READY"|"FALLBACK"|"EMPTY">(url?"LOADING":"EMPTY");const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!url){setState("EMPTY");return;}let cancelled=false;let task:{destroy?:()=>void}|null=null;(async()=>{try{const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc="https://unpkg.com/pdfjs-dist@6.3.289/build/pdf.worker.min.mjs";const loading=pdfjs.getDocument(url);task=loading;const pdf=await loading.promise;const page=await pdf.getPage(Math.min(Math.max(1,pageNumber),pdf.numPages));const base=page.getViewport({scale:1});const host=canvasRef.current?.parentElement;const target=Math.max(640,host?.clientWidth||1200);const viewport=page.getViewport({scale:target/base.width});const canvas=canvasRef.current;if(!canvas||cancelled)return;const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(viewport.width*ratio);canvas.height=Math.floor(viewport.height*ratio);canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas context unavailable.");await page.render({canvasContext:ctx,viewport,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]}).promise;if(!cancelled){setState("READY");setError(null);}}catch(e){if(!cancelled){setState("FALLBACK");setError(e instanceof Error?e.message:"PDF render failed.");}}})();return()=>{cancelled=true;task?.destroy?.();};},[url,pageNumber]);
  function click(e:React.MouseEvent<HTMLDivElement>){if(!interactive)return;const r=e.currentTarget.getBoundingClientRect();if(!r.width||!r.height)return;onPoint({x:Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),y:Math.min(1,Math.max(0,(e.clientY-r.top)/r.height))});}
  const all=[...marks.map(m=>({key:m.id,g:m.geometry,selected:m.selected,title:m.title,id:m.id})),...(draft?[{key:"draft",g:draft,selected:true,title:"Draft",id:null as string|null}]:[]),...(start?[{key:"start",g:{type:"Point",x:start.x,y:start.y} as Geometry,selected:true,title:"Start",id:null as string|null}]:[])];
  return <div className="space-y-2">{state==="FALLBACK"&&url&&<div className="border border-[#6A5521] bg-[#211B0D] p-2 text-xs text-[#F0D98A]">PDF.js could not read this source directly{error?`: ${error}`:""}. Browser fallback remains available below.</div>}<div className="relative max-h-[76vh] min-h-[560px] overflow-auto border border-[#1C3A57] bg-white" onClick={click}>{state==="FALLBACK"&&url?<iframe src={`${url}#page=${pageNumber}`} title="Drawing PDF fallback" className="h-[72vh] w-full" style={{pointerEvents:interactive?"none":"auto"}}/>:<canvas ref={canvasRef} className="block max-w-none"/>}<svg className={`absolute inset-0 h-full w-full ${interactive?"cursor-crosshair":"pointer-events-none"}`} viewBox="0 0 1000 1000" preserveAspectRatio="none">{all.map(m=>{const g=m.g;const stroke=m.selected?"#0E7490":"#D97706";if(g.type==="Point"){return <g key={m.key} onClick={e=>{if(m.id){e.stopPropagation();onSelect(m.id);}}} className={m.id?"pointer-events-auto cursor-pointer":""}><circle cx={g.x*1000} cy={g.y*1000} r="10" fill="#F59E0B" stroke="#07131D" strokeWidth="4"/><title>{m.title}</title></g>;}const x1=g.x1*1000,y1=g.y1*1000,x2=g.x2*1000,y2=g.y2*1000;if(g.type==="Arrow")return <g key={m.key} onClick={e=>{if(m.id){e.stopPropagation();onSelect(m.id);}}} className={m.id?"pointer-events-auto cursor-pointer":""}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={stroke} strokeWidth="6"/><circle cx={x2} cy={y2} r="8" fill={stroke}/><title>{m.title}</title></g>;const x=Math.min(x1,x2),y=Math.min(y1,y2),w=Math.abs(x2-x1),h=Math.abs(y2-y1);return <g key={m.key} onClick={e=>{if(m.id){e.stopPropagation();onSelect(m.id);}}} className={m.id?"pointer-events-auto cursor-pointer":""}><rect x={x} y={y} width={w} height={h} fill="none" stroke={stroke} strokeWidth="6" strokeDasharray={g.type==="Cloud"?"18 10":"0"} rx={g.type==="Cloud"?18:0}/><title>{m.title}</title></g>;})}</svg>{state==="LOADING"&&<div className="absolute inset-0 grid place-items-center bg-white/70 text-sm text-slate-600">Rendering PDF page…</div>}{state==="EMPTY"&&<div className="absolute inset-0 grid place-items-center text-sm text-slate-500">No source PDF URL registered.</div>}</div><div className="cat">PDF.js page {pageNumber} · normalized markup coordinates · {state}</div></div>;
}
