import { Building2, Plus, ShieldCheck } from "lucide-react";
import { requireOrgContext } from "@/lib/session";
import { Card, PageHeader } from "@/components/ui";
import { createOrganizationAction, switchOrgAction } from "../actions";

export default async function OrganizationsPage(){
  const ctx=await requireOrgContext();
  return <div className="space-y-6 max-w-4xl"><PageHeader eyebrow="Multi-organization workspace" title="Organizations" subtitle="One account can belong to multiple companies, divisions, joint ventures or client workspaces. Each organization has isolated projects, estimating data, suppliers, RFIs, RFQs and audit history." />
    <div className="grid gap-3 md:grid-cols-2">{ctx.memberships.map(m=><Card key={m.id} className={`p-4 ${m.organizationId===ctx.organization.id?"border-signal-300 ring-1 ring-signal-100":""}`}><div className="flex items-start justify-between"><div className="flex gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><Building2 className="h-4 w-4"/></span><div><h3 className="font-semibold text-slate-800">{m.organization.name}</h3><p className="text-xs text-slate-400">/{m.organization.slug}</p></div></div><span className="flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-500"><ShieldCheck className="h-3 w-3"/>{m.role}</span></div>{m.organizationId===ctx.organization.id?<div className="mt-4 text-xs font-semibold text-emerald-600">Active organization</div>:<form action={switchOrgAction} className="mt-4"><input type="hidden" name="organizationId" value={m.organizationId}/><button className="rounded-md border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700">Switch here</button></form>}</Card>)}</div>
    <Card className="p-5"><div className="flex items-center gap-2"><Plus className="h-4 w-4 text-signal-600"/><h2 className="font-semibold text-slate-800">Create another organization</h2></div><p className="mt-1 text-sm text-slate-500">You become Owner. The new tenant gets its own costing catalog, settings and market-intelligence baseline.</p><form action={createOrganizationAction} className="mt-4 flex gap-2"><input name="name" required placeholder="Organization / division name" className="flex-1 rounded-md border border-slate-300 px-3 py-2 text-sm"/><button className="rounded-md bg-signal-600 px-4 py-2 text-xs font-semibold text-white">Create</button></form></Card>
  </div>;
}
