import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import { getRealityCaptureSpaces, getSpatialAnnotations } from "@/lib/spatial-context";
import { addAnnotationCommentAction, assignAnnotationAction, createAnnotationAction, createRfiFromAnnotationAction, setAnnotationStatusAction } from "./actions";

type CommentRow={id:string;annotationId:string;body:string;createdAt:Date;authorName:string|null;authorEmail:string|null};
type MemberRow={id:string;name:string|null;email:string};
export default async function AnnotationPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{context?:string;spaceId?:string;drawingRevisionId?:string}>}){
  const {projectId}=await params;const sp=await searchParams;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const [{revisions,objects},spaces,annotations,members,comments]=await Promise.all([getDrawingWorkspace(projectId,ctx.account.id),getRealityCaptureSpaces(projectId,ctx.account.id),getSpatialAnnotations(projectId,ctx.account.id),db.$queryRawUnsafe<MemberRow[]>(`SELECT u."id",u."name",u."email" FROM "User" u JOIN "AccountMembership" am ON am."userId"=u."id" WHERE am."accountId"=$1 ORDER BY COALESCE(u."name",u."email")`,ctx.account.id),db.$queryRawUnsafe<CommentRow[]>(`SELECT c."id",c."annotationId",c."body",c."createdAt",u."name" AS "authorName",u."email" AS "authorEmail" FROM "SpatialAnnotationComment" c LEFT JOIN "User" u ON u."id"=c."createdById" JOIN "SpatialAnnotation" a ON a."id"=c."annotationId" WHERE c."accountId"=$1 AND a."projectId"=$2 ORDER BY c."createdAt" ASC`,ctx.account.id,projectId)]);
  const defaultContext=sp.context==="MATTERPORT"?"MATTERPORT":sp.context==="DRAWING"?"DRAWING":"PROJECT";const open=annotations.filter(a=>a.status!=="RESOLVED"&&a.status!=="VOID");
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Spatial Intelligence · Annotations</p><h1 className="stratum-sheet-title">{project.name} Annotation Register</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">One annotation workflow for drawing markups, Matterport observations, assignment, discussion and escalation into formal RFIs.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/reality-capture`} className="btn">Matterport</Link><Link href={`/projects/${projectId}/drawings/markup`} className="btn-secondary">Drawing Markup</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link></div></div></section>
    <section className="grid gap-4 md:grid-cols-4">{[["Open",open.length],["Drawing",annotations.filter(a=>a.contextType==="DRAWING").length],["Matterport",annotations.filter(a=>a.contextType==="MATTERPORT").length],["Resolved",annotations.filter(a=>a.status==="RESOLVED").length]].map(([k,v])=><div key={String(k)} className="stratum-sheet"><div className="cat">{k}</div><div className="mt-1 text-2xl font-semibold text-[#DCEBF5]">{v}</div></div>)}</section>
    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Create annotation</h2><form action={createAnnotationAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><select name="contextType" defaultValue={defaultContext}><option>PROJECT</option><option>DRAWING</option><option>MATTERPORT</option></select><select name="annotationType" defaultValue="NOTE"><option>NOTE</option><option>ISSUE</option><option>QUESTION</option><option>CLASH</option><option>SAFETY</option><option>QUALITY</option><option>CHANGE</option><option>COMMERCIAL</option></select><select name="priority" defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select><input name="title" required placeholder="Annotation title"/><select name="drawingRevisionId" defaultValue={sp.drawingRevisionId||""}><option value="">Drawing revision</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select><select name="realityCaptureSpaceId" defaultValue={sp.spaceId||""}><option value="">Matterport/capture</option>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="spatialObjectId"><option value="">No takeoff object</option>{objects.map(o=><option key={o.id} value={o.id}>{o.name} · {o.objectType}</option>)}</select><div/><textarea name="body" placeholder="Comment, instruction, observation" className="md:col-span-2"/><textarea name="matterportPoseJson" placeholder="Optional Matterport pose JSON" className="md:col-span-2"/><button className="btn md:col-span-2">Create annotation</button></form></section>
    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Annotation register</h2>{annotations.length===0?<div className="empty-state mt-3">No annotations yet.</div>:<div className="mt-3 space-y-3">{annotations.map(a=>{const rev=revisions.find(r=>r.id===a.drawingRevisionId);const space=spaces.find(s=>s.id===a.realityCaptureSpaceId);const thread=comments.filter(c=>c.annotationId===a.id);return <div key={a.id} className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="tag REF">{a.contextType}</span><span className="tag">{a.annotationType}</span><span className="font-mono text-[10px] text-[#E0954F]">{a.priority}</span></div><h3 className="mt-2 text-sm font-semibold text-[#DCEBF5]">{a.title}</h3><p className="mt-1 text-xs text-[#9CB2C2]">{a.body||"No body"}</p><div className="mt-2 cat">{rev?`${rev.sheetNumber} · R${rev.revision}`:space?`${space.name} · ${space.provider}`:"Project context"}</div></div><span className="tag REF">{a.status}</span></div>
      <div className="mt-3 grid gap-2 lg:grid-cols-3"><form action={assignAnnotationAction.bind(null,projectId)} className="flex gap-2"><input type="hidden" name="annotationId" value={a.id}/><select name="assignedToId" defaultValue={a.assignedToId||""} className="min-w-0 flex-1"><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.name||m.email}</option>)}</select><button className="btn-secondary">Assign</button></form><form action={setAnnotationStatusAction.bind(null,projectId)} className="flex gap-2"><input type="hidden" name="annotationId" value={a.id}/><select name="status" defaultValue={a.status}><option>OPEN</option><option>IN_REVIEW</option><option>RESOLVED</option><option>VOID</option></select><button className="btn-secondary">Status</button></form>{a.linkedEntityType==="RFI"&&a.linkedEntityId?<Link href={`/projects/${projectId}`} className="btn-secondary text-center">Linked RFI</Link>:<form action={createRfiFromAnnotationAction.bind(null,projectId)}><input type="hidden" name="annotationId" value={a.id}/><button className="btn w-full">Create RFI</button></form>}</div>
      <div className="mt-3 border-t border-[#1C3A57] pt-3"><div className="cat">Discussion · {thread.length}</div>{thread.length>0&&<div className="mt-2 space-y-2">{thread.map(c=><div key={c.id} className="border border-[#1C3A57] px-2 py-1.5 text-xs text-[#9CB2C2]"><span className="font-semibold text-[#DCEBF5]">{c.authorName||c.authorEmail||"User"}</span> · {c.body}</div>)}</div>}<form action={addAnnotationCommentAction.bind(null,projectId)} className="mt-2 flex gap-2"><input type="hidden" name="annotationId" value={a.id}/><input name="body" required placeholder="Add comment" className="min-w-0 flex-1"/><button className="btn-secondary">Comment</button></form></div></div>;})}</div>}</section>
  </div>;
}
