import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import { getRealityCaptureSpaces, getSpatialAnnotations } from "@/lib/spatial-context";
import { createAnnotationAction, createRfiFromAnnotationAction, setAnnotationStatusAction } from "./actions";

export default async function AnnotationPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{context?:string;spaceId?:string;drawingRevisionId?:string}>}){
  const {projectId}=await params;const sp=await searchParams;const ctx=await requireTenantContext();const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}});if(!project)notFound();
  const [{revisions,objects},spaces,annotations]=await Promise.all([getDrawingWorkspace(projectId,ctx.account.id),getRealityCaptureSpaces(projectId,ctx.account.id),getSpatialAnnotations(projectId,ctx.account.id)]);
  const defaultContext=sp.context==="MATTERPORT"?"MATTERPORT":sp.context==="DRAWING"?"DRAWING":"PROJECT";const open=annotations.filter(a=>a.status!=="RESOLVED"&&a.status!=="VOID");
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Spatial Intelligence · Annotations</p><h1 className="stratum-sheet-title">{project.name} Annotation Register</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">One annotation model for drawing markups, Matterport/360° observations, project notes and takeoff-linked issues. Annotations retain status history and can now promote directly into the formal RFI workflow without losing their spatial source.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/drawings/markup`} className="btn">Drawing Markup</Link><Link href={`/projects/${projectId}/reality-capture`} className="btn-secondary">Matterport</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}`} className="btn-secondary">Project</Link></div></div></section>
    <section className="grid gap-4 md:grid-cols-4">{[["Open",open.length],["Drawing",annotations.filter(a=>a.contextType==="DRAWING").length],["Matterport",annotations.filter(a=>a.contextType==="MATTERPORT").length],["Resolved",annotations.filter(a=>a.status==="RESOLVED").length]].map(([k,v])=><div key={String(k)} className="stratum-sheet"><div className="cat">{k}</div><div className="mt-1 text-2xl font-semibold text-[#DCEBF5]">{v}</div></div>)}</section>
    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Create annotation</h2><form action={createAnnotationAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4"><select name="contextType" defaultValue={defaultContext}><option>PROJECT</option><option>DRAWING</option><option>MATTERPORT</option></select><select name="annotationType" defaultValue="NOTE"><option>NOTE</option><option>ISSUE</option><option>QUESTION</option><option>CLASH</option><option>SAFETY</option><option>QUALITY</option><option>CHANGE</option><option>COMMERCIAL</option></select><select name="priority" defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select><input name="title" required placeholder="Annotation title"/><select name="drawingRevisionId" defaultValue={sp.drawingRevisionId||""}><option value="">Drawing revision (if drawing)</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision} · {r.sheetTitle||"Untitled"}</option>)}</select><select name="realityCaptureSpaceId" defaultValue={sp.spaceId||""}><option value="">Matterport/capture (if applicable)</option>{spaces.map(s=><option key={s.id} value={s.id}>{s.name} · {s.provider}</option>)}</select><select name="spatialObjectId"><option value="">No takeoff object</option>{objects.map(o=><option key={o.id} value={o.id}>{o.name} · {o.objectType} · {o.quantity.toFixed(2)} {o.unit}</option>)}</select><div className="grid grid-cols-2 gap-2"><input name="pointX" type="number" step="any" placeholder="X"/><input name="pointY" type="number" step="any" placeholder="Y"/></div><textarea name="body" placeholder="Comment, instruction, observation, markup note" className="md:col-span-2"/><textarea name="matterportPoseJson" placeholder='Optional Matterport pose JSON for SDK synchronization' className="md:col-span-2"/><select name="linkedEntityType"><option value="">No downstream link</option><option>RFI</option><option>ESTIMATE</option><option>RFQ</option><option>QUOTE</option><option>TAKEOFF</option><option>PROJECT</option></select><input name="linkedEntityId" placeholder="Linked entity ID"/><button className="btn md:col-span-2">Create annotation</button></form></section>
    <section className="stratum-sheet"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Annotation register</h2><p className="cat">{annotations.length} total · {open.length} active</p></div></div>{annotations.length===0?<div className="empty-state mt-3">No annotations yet.</div>:<div className="mt-3 space-y-3">{annotations.map(a=>{const rev=revisions.find(r=>r.id===a.drawingRevisionId);const space=spaces.find(s=>s.id===a.realityCaptureSpaceId);const linkedRfi=a.linkedEntityType==="RFI"&&a.linkedEntityId;return <div key={a.id} className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="tag REF">{a.contextType}</span><span className="tag">{a.annotationType}</span><span className="font-mono text-[10px] text-[#E0954F]">{a.priority}</span></div><h3 className="mt-2 text-sm font-semibold text-[#DCEBF5]">{a.title}</h3><p className="mt-1 text-xs text-[#9CB2C2]">{a.body||"No body"}</p><div className="mt-2 cat">{rev?`${rev.sheetNumber} · R${rev.revision}`:space?`${space.name} · ${space.provider}`:"Project context"}{linkedRfi?` · linked RFI ${a.linkedEntityId}`:a.linkedEntityType&&a.linkedEntityId?` · linked ${a.linkedEntityType}:${a.linkedEntityId}`:""}</div></div><span className="tag REF">{a.status}</span></div><div className="mt-3 flex flex-wrap gap-2">{!linkedRfi&&a.status!=="VOID"&&<form action={createRfiFromAnnotationAction.bind(null,projectId)}><input type="hidden" name="annotationId" value={a.id}/><button className="btn">Create RFI from annotation</button></form>}<form action={setAnnotationStatusAction.bind(null,projectId)} className="flex min-w-[360px] flex-1 flex-wrap gap-2"><input type="hidden" name="annotationId" value={a.id}/><select name="status" defaultValue={a.status}><option>OPEN</option><option>IN_REVIEW</option><option>RESOLVED</option><option>VOID</option></select><input name="reason" placeholder="Status change reason" className="min-w-[180px] flex-1"/><button className="btn-secondary">Update status</button></form></div></div>;})}</div>}</section>
  </div>;
}
