import { requireOrgContext } from "@/lib/session";
import { db } from "@/lib/db";
import { atLeast } from "@/lib/rbac";
import { money } from "@/lib/costing";
import { Card, PageHeader } from "@/components/ui";
import { applyJobCostToItemAction, createJobCostAction } from "../actions";

export default async function JobCostsPage() {
  const ctx=await requireOrgContext();
  const [entries,items,projects]=await Promise.all([
    db.jobCostEntry.findMany({where:{organizationId:ctx.organization.id},include:{costItem:true,project:true,createdBy:{select:{name:true,email:true}}},orderBy:{date:"desc"},take:250}),
    db.costItem.findMany({where:{organizationId:ctx.organization.id},orderBy:{description:"asc"}}),
    db.project.findMany({where:{organizationId:ctx.organization.id,archivedAt:null},orderBy:{name:"asc"}}),
  ]);
  const canApply=atLeast(ctx.role,"ADMIN");
  return <div className="space-y-5"><PageHeader eyebrow={ctx.organization.name} title="Job Cost History" subtitle="Capture actual installed labor and material, then calibrate organization rates from completed work." />
    {atLeast(ctx.role,"MEMBER")&&<Card className="p-4"><form action={createJobCostAction} className="grid gap-2 md:grid-cols-4"><input name="jobName" required placeholder="Completed work / job name" className="md:col-span-2 rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><select name="projectId" className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="costItemId" className="md:col-span-2 rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="">No catalog item</option>{items.map(i=><option key={i.id} value={i.id}>{i.description}</option>)}</select><input name="quantity" type="number" step="0.01" defaultValue="1" placeholder="Quantity" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="actualLaborHours" type="number" step="0.01" defaultValue="0" placeholder="Actual labor hours" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="actualMaterialCost" type="number" step="0.01" defaultValue="0" placeholder="Actual material total $" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="notes" placeholder="Notes" className="md:col-span-2 rounded-md border border-slate-300 px-3 py-2 text-sm"/><button className="rounded-md bg-signal-600 px-3 py-2 text-xs font-semibold text-white">Log actual</button></form></Card>}
    <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr className="border-b bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-3 py-2.5">Date / work</th><th className="px-3 py-2.5">Catalog item</th><th className="px-3 py-2.5 text-right">Qty</th><th className="px-3 py-2.5 text-right">Labor/unit</th><th className="px-3 py-2.5 text-right">Material/unit</th><th className="px-3 py-2.5">Project</th><th/></tr></thead><tbody>{entries.map(e=>{const lh=e.quantity?e.actualLaborHours/e.quantity:0;const mat=e.quantity?e.actualMaterialCost/e.quantity:0;return <tr key={e.id} className="border-b border-slate-100 last:border-0"><td className="px-3 py-2.5"><div className="font-medium text-slate-800">{e.jobName}</div><div className="text-xs text-slate-400">{e.date.toLocaleDateString()} · {e.createdBy?.name||e.createdBy?.email||"—"}</div></td><td className="px-3 py-2.5 text-slate-500">{e.costItem?.description||"—"}</td><td className="px-3 py-2.5 text-right font-mono">{e.quantity}</td><td className="px-3 py-2.5 text-right font-mono">{lh.toFixed(3)} hr</td><td className="px-3 py-2.5 text-right font-mono">{money(mat)}</td><td className="px-3 py-2.5 text-slate-500">{e.project?.name||"—"}</td><td className="px-3 py-2.5">{canApply&&e.costItemId&&<form action={applyJobCostToItemAction}><input type="hidden" name="entryId" value={e.id}/><button className="text-xs font-semibold text-signal-600">Apply to item</button></form>}</td></tr>})}</tbody></table></div>{entries.length===0&&<div className="p-10 text-center text-sm text-slate-400">No job-cost actuals logged yet.</div>}</Card>
  </div>;
}
