"use server";

import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { logAction } from "@/lib/audit";
import { requireAccountRole } from "@/lib/session";
import { addPlanRoomRevision, associatePlanRoomDocument, createPlanRoomDocument, createPlanRoomFolder } from "@/lib/plan-room";

async function requireProject(projectId:string, accountId:string){ const project=await db.project.findFirst({where:{id:projectId,accountId}}); if(!project) throw new Error("Project not found in this account."); return project; }
async function requireFolder(folderId:string,projectId:string,accountId:string){const rows=await db.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "ProjectDocumentFolder" WHERE "id"=$1 AND "projectId"=$2 AND "accountId"=$3`,folderId,projectId,accountId);if(!rows[0])throw new Error("Folder not found in this project/account.");}
async function requireDocument(documentId:string,projectId:string,accountId:string){const rows=await db.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "ProjectDocument" WHERE "id"=$1 AND "projectId"=$2 AND "accountId"=$3`,documentId,projectId,accountId);if(!rows[0])throw new Error("Document not found in this project/account.");}
async function requireAssociationTarget(entityType:string,entityId:string,projectId:string,accountId:string){
  if(entityType==="PROJECT"){await requireProject(entityId,accountId);if(entityId!==projectId)throw new Error("Association target must belong to the current project.");return;}
  let rows:Array<{id:string}>=[];
  if(entityType==="ESTIMATE") rows=await db.$queryRawUnsafe(`SELECT "id" FROM "CostEstimate" WHERE "id"=$1 AND "projectId"=$2 AND "accountId"=$3`,entityId,projectId,accountId);
  else if(entityType==="RFI") rows=await db.$queryRawUnsafe(`SELECT r."id" FROM "Rfi" r JOIN "Project" p ON p."id"=r."projectId" WHERE r."id"=$1 AND r."projectId"=$2 AND p."accountId"=$3`,entityId,projectId,accountId);
  else if(entityType==="RFQ") rows=await db.$queryRawUnsafe(`SELECT r."id" FROM "Rfq" r JOIN "Project" p ON p."id"=r."projectId" WHERE r."id"=$1 AND r."projectId"=$2 AND p."accountId"=$3`,entityId,projectId,accountId);
  else if(entityType==="QUOTE") rows=await db.$queryRawUnsafe(`SELECT "id" FROM "SupplierQuote" WHERE "id"=$1 AND "projectId"=$2 AND "accountId"=$3`,entityId,projectId,accountId);
  else if(entityType==="DRAWING_REVISION") rows=await db.$queryRawUnsafe(`SELECT r."id" FROM "DrawingRevision" r JOIN "DrawingSet" s ON s."id"=r."drawingSetId" WHERE r."id"=$1 AND s."projectId"=$2 AND r."accountId"=$3`,entityId,projectId,accountId);
  else if(entityType==="TAKEOFF"||entityType==="SPATIAL_OBJECT") rows=await db.$queryRawUnsafe(`SELECT o."id" FROM "SpatialTakeoffObject" o JOIN "DrawingRevision" r ON r."id"=o."drawingRevisionId" JOIN "DrawingSet" s ON s."id"=r."drawingSetId" WHERE o."id"=$1 AND s."projectId"=$2 AND o."accountId"=$3`,entityId,projectId,accountId);
  else throw new Error("Unsupported association target type.");
  if(!rows[0]) throw new Error("Association target not found in this project/account.");
}
const s=(fd:FormData,k:string)=>String(fd.get(k)??"").trim();

export async function createFolderAction(projectId:string, formData:FormData){ const ctx=await requireAccountRole("MEMBER"); await requireProject(projectId,ctx.account.id); const name=s(formData,"name"); const parentId=s(formData,"parentId")||null;if(!name) throw new Error("Folder name is required."); if(parentId)await requireFolder(parentId,projectId,ctx.account.id); await createPlanRoomFolder({projectId,accountId:ctx.account.id,parentId,name,createdById:ctx.user.id}); await logAction({organizationId:ctx.organization.id,accountId:ctx.account.id,userId:ctx.user.id,projectId,action:"plan_room.folder.create",detail:`Created folder ${name}`}); revalidatePath(`/projects/${projectId}/plan-room`); }

export async function registerDocumentAction(projectId:string, formData:FormData){ const ctx=await requireAccountRole("MEMBER"); await requireProject(projectId,ctx.account.id); const name=s(formData,"name"); const folderId=s(formData,"folderId")||null;if(!name) throw new Error("Document name is required."); if(folderId)await requireFolder(folderId,projectId,ctx.account.id); const id=await createPlanRoomDocument({projectId,accountId:ctx.account.id,folderId,name,documentType:s(formData,"documentType")||"GENERAL",externalUrl:s(formData,"externalUrl")||null,mimeType:s(formData,"mimeType")||null,description:s(formData,"description")||null,createdById:ctx.user.id}); await logAction({organizationId:ctx.organization.id,accountId:ctx.account.id,userId:ctx.user.id,projectId,action:"plan_room.document.register",detail:`Registered ${name} (${id})`}); revalidatePath(`/projects/${projectId}/plan-room`); }

export async function addDocumentRevisionAction(projectId:string, formData:FormData){ const ctx=await requireAccountRole("MEMBER"); await requireProject(projectId,ctx.account.id); const documentId=s(formData,"documentId"); const revision=s(formData,"revision"); if(!documentId||!revision) throw new Error("Document and revision are required."); await requireDocument(documentId,projectId,ctx.account.id); await addPlanRoomRevision({documentId,accountId:ctx.account.id,revision,externalUrl:s(formData,"externalUrl")||null,changeSummary:s(formData,"changeSummary")||null,issuedAt:s(formData,"issuedAt")?new Date(`${s(formData,"issuedAt")}T12:00:00`):null,createdById:ctx.user.id}); await logAction({organizationId:ctx.organization.id,accountId:ctx.account.id,userId:ctx.user.id,projectId,action:"plan_room.revision.add",detail:`Added document revision ${revision}`}); revalidatePath(`/projects/${projectId}/plan-room`); }

export async function associateDocumentAction(projectId:string, formData:FormData){ const ctx=await requireAccountRole("MEMBER"); await requireProject(projectId,ctx.account.id); const documentId=s(formData,"documentId"); const entityType=s(formData,"entityType"); const entityId=s(formData,"entityId"); if(!documentId||!entityType||!entityId) throw new Error("Document, entity type and entity ID are required."); await requireDocument(documentId,projectId,ctx.account.id); await requireAssociationTarget(entityType,entityId,projectId,ctx.account.id); await associatePlanRoomDocument({documentId,accountId:ctx.account.id,entityType,entityId,label:s(formData,"label")||null}); await logAction({organizationId:ctx.organization.id,accountId:ctx.account.id,userId:ctx.user.id,projectId,action:"plan_room.document.associate",detail:`Associated document to ${entityType}:${entityId}`}); revalidatePath(`/projects/${projectId}/plan-room`); }