import Link from "next/link";
import { notFound } from "next/navigation";
import { requireTenantContext } from "@/lib/session";
import { db } from "@/lib/db";
import { getPlanRoom } from "@/lib/plan-room";
import { addDocumentRevisionAction, associateDocumentAction, createFolderAction, registerDocumentAction } from "./actions";

const TYPES=["CONTRACT","ARCHITECTURAL","ELECTRICAL","MECHANICAL","PLUMBING","CIVIL","STRUCTURAL","SPECIFICATION","ADDENDUM","RFI","SUBMITTAL","QUOTE","CHANGE_ORDER","AS_BUILT","GENERAL"];

export default async function PlanRoomPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params; const ctx=await requireTenantContext();
  const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}}); if(!project) notFound();
  const {folders,documents}=await getPlanRoom(projectId,ctx.account.id);
  const docsByFolder=new Map<string|null,typeof documents>(); for(const d of documents){const k=d.folderId??null; docsByFolder.set(k,[...(docsByFolder.get(k)||[]),d]);}
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Project Data · Digital Plan Room</p><h1 className="stratum-sheet-title">{project.name} Plan Room</h1><p className="mt-2 text-sm text-[#9CB2C2]">Controlled project document hierarchy with revisions, drawing intake, and links to estimates, RFIs, RFQs, quotes, takeoffs, and spatial objects.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/plan-room/drawing-ingestion`} className="btn">Drawing Intake</Link><Link href={`/projects/${projectId}/drawings/viewer`} className="btn-secondary">Spatial Viewer</Link><Link href={`/projects/${projectId}`} className="btn-secondary">Back to project</Link></div></div></section>

    <section className="grid gap-4 xl:grid-cols-2"><div className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Create folder</h2><form action={createFolderAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input name="name" required placeholder="Electrical, Addenda, As-Builts…"/><select name="parentId"><option value="">Top level</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button className="btn">Add folder</button></form></div><div className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Register document</h2><form action={registerDocumentAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2"><input name="name" required placeholder="E-101 Power Plan.pdf"/><select name="documentType">{TYPES.map(t=><option key={t}>{t}</option>)}</select><select name="folderId"><option value="">No folder</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input name="externalUrl" type="url" placeholder="Storage URL / source URL"/><input name="mimeType" placeholder="application/pdf"/><input name="description" placeholder="Description / purpose"/><button className="btn md:col-span-2">Register document</button></form></div></section>

    <section className="stratum-sheet"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Project documents</h2><p className="cat">{documents.length} document{documents.length===1?"":"s"} · {folders.length} folder{folders.length===1?"":"s"}</p></div></div><div className="mt-4 space-y-4">{[null,...folders.map(f=>f.id)].map(folderId=>{const folder=folderId?folders.find(f=>f.id===folderId):null; const docs=docsByFolder.get(folderId)||[]; if(!docs.length&&folderId===null)return null; return <div key={folderId||"root"} className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="mb-2 font-mono text-[10px] uppercase tracking-[0.08em] text-[#6FD6C9]">{folder?.name||"Unfiled"}</div>{docs.length===0?<div className="cat">Empty folder</div>:<div className="space-y-2">{docs.map(d=><div key={d.id} className="border border-[#183247] p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-sm font-semibold text-[#DCEBF5]">{d.name}</div><div className="cat">{d.documentType} · {d.status} · updated {new Date(d.updatedAt).toISOString().slice(0,10)}</div></div><div className="flex gap-2">{["ELECTRICAL","ARCHITECTURAL","MECHANICAL","PLUMBING","CIVIL","STRUCTURAL","GENERAL","AS_BUILT","ADDENDUM"].includes(d.documentType)&&<Link href={`/projects/${projectId}/plan-room/drawing-ingestion`} className="btn-secondary">Queue drawing</Link>}{d.externalUrl&&<a href={d.externalUrl} target="_blank" rel="noreferrer" className="btn-secondary">Open</a>}</div></div><details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-[#9CB2C2]">Revision / association controls</summary><div className="mt-3 grid gap-3 xl:grid-cols-2"><form action={addDocumentRevisionAction.bind(null,projectId)} className="grid gap-2 md:grid-cols-2"><input type="hidden" name="documentId" value={d.id}/><input name="revision" required placeholder="Rev 1 / Addendum 2"/><input name="issuedAt" type="date"/><input name="externalUrl" type="url" placeholder="Revision source URL"/><input name="changeSummary" placeholder="Change summary"/><button className="btn md:col-span-2">Add revision</button></form><form action={associateDocumentAction.bind(null,projectId)} className="grid gap-2 md:grid-cols-2"><input type="hidden" name="documentId" value={d.id}/><select name="entityType"><option>ESTIMATE</option><option>RFI</option><option>RFQ</option><option>QUOTE</option><option>TAKEOFF</option><option>PROJECT</option><option>SPATIAL_OBJECT</option><option>DRAWING_REVISION</option></select><input name="entityId" required placeholder="Entity ID"/><input name="label" placeholder="Sheet/source/context"/><button className="btn">Associate</button></form></div></details></div>)}</div>}</div>})}{documents.length===0&&folders.length===0&&<div className="empty-state">No Plan Room content yet.</div>}</div></section>
  </div>;
}
