import { requireOrgContext } from "@/lib/session";
import { db } from "@/lib/db";
import { atLeast } from "@/lib/rbac";
import { Card, PageHeader } from "@/components/ui";
import { createMarketFactorAction, deleteMarketFactorAction } from "../actions";

export default async function MarketIntelPage(){
  const ctx=await requireOrgContext(); const canManage=atLeast(ctx.role,"ADMIN");
  const factors=await db.marketFactor.findMany({where:{organizationId:ctx.organization.id},orderBy:[{asOf:"desc"},{createdAt:"desc"}]});
  return <div className="space-y-5"><PageHeader eyebrow={ctx.organization.name} title="Market Intelligence" subtitle="Organization-specific pricing signals used as estimating context; they do not silently modify rates or bids." />
    {canManage&&<Card className="p-4"><form action={createMarketFactorAction} className="grid gap-2 md:grid-cols-4"><input name="description" required placeholder="Signal description" className="md:col-span-2 rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="category" placeholder="Category" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="asOf" type="date" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><select name="direction" className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="INCREASE">Increase</option><option value="DECREASE">Decrease</option></select><input name="magnitude" type="number" step="0.01" placeholder="Magnitude %" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><select name="affects" className="rounded-md border border-slate-300 px-3 py-2 text-sm"><option value="ALL">All cost</option><option value="MATERIAL">Material</option><option value="LABOR">Labor</option></select><input name="source" placeholder="Source / citation" className="rounded-md border border-slate-300 px-3 py-2 text-sm"/><input name="url" placeholder="https://…" className="md:col-span-3 rounded-md border border-slate-300 px-3 py-2 text-sm"/><button className="rounded-md bg-signal-600 px-3 py-2 text-xs font-semibold text-white">Add signal</button></form></Card>}
    <div className="grid gap-3 md:grid-cols-2">{factors.map(f=><Card key={f.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{f.category} · {f.affects}</div><h3 className="mt-1 font-semibold text-slate-800">{f.description}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${f.direction==="INCREASE"?"bg-rose-50 text-rose-600":"bg-emerald-50 text-emerald-600"}`}>{f.direction==="INCREASE"?"+":"−"}{f.magnitude}%</span></div><p className="mt-3 text-xs leading-5 text-slate-500">{f.source||"No source note"}</p><div className="mt-3 flex items-center justify-between text-xs"><span className="text-slate-400">As of {f.asOf?.toLocaleDateString()||"—"}</span><div className="flex gap-3">{f.url&&<a href={f.url} target="_blank" rel="noreferrer" className="font-semibold text-signal-600">Source ↗</a>}{canManage&&<form action={deleteMarketFactorAction}><input type="hidden" name="id" value={f.id}/><button className="font-semibold text-rose-600">Delete</button></form>}</div></div></Card>)}{factors.length===0&&<Card className="p-10 text-center text-sm text-slate-400 md:col-span-2">No market signals configured.</Card>}</div>
  </div>;
}
