import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getAssemblies, getDrawingWorkspace } from "@/lib/drawing-native";
import { applyAssemblyToEstimateAction, createDrawingLayerAction, createDrawingRevisionAction, createDrawingSetAction, createTakeoffObjectAction, linkSpatialEstimateAction, verifyTakeoffObjectAction } from "./actions";

const OBJECT_TYPES=["COUNT","LINEAR","AREA"];

export default async function DrawingsPage({params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params; const ctx=await requireTenantContext();
  const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}}); if(!project) notFound();
  const [{sets,revisions,layers,objects},estimates,{assemblies}]=await Promise.all([
    getDrawingWorkspace(projectId,ctx.account.id),
    db.costEstimate.findMany({where:{projectId,accountId:ctx.account.id},include:{lineItems:{orderBy:{sortOrder:"asc"}}},orderBy:{updatedAt:"desc"}}),
    getAssemblies(ctx.account.id),
  ]);
  const editableEstimates=estimates.filter(e=>e.status==="DRAFT"||e.status==="REVIEW");
  const revBySet=new Map<string,typeof revisions>(); for(const r of revisions) revBySet.set(r.drawingSetId,[...(revBySet.get(r.drawingSetId)||[]),r]);
  const objectTotals={COUNT:objects.filter(o=>o.objectType==="COUNT").reduce((n,o)=>n+o.quantity,0),LINEAR:objects.filter(o=>o.objectType==="LINEAR").reduce((n,o)=>n+(o.measurement??o.quantity),0),AREA:objects.filter(o=>o.objectType==="AREA").reduce((n,o)=>n+(o.measurement??o.quantity),0)};
  return <div className="space-y-5">
    <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Drawing-Native Preconstruction</p><h1 className="stratum-sheet-title">{project.name} Drawing Workspace</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Register drawing revisions, organize construction layers, capture Count / Linear / Area takeoff, verify spatial objects, and convert verified measurements into traceable estimate scope.</p></div><div className="flex flex-wrap gap-2"><Link href={`/projects/${projectId}/drawings/revision-delta`} className="btn-secondary">Revision Delta</Link><Link href={`/projects/${projectId}/plan-room`} className="btn-secondary">Plan Room</Link><Link href={`/projects/${projectId}`} className="btn-secondary">Project</Link></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="stratum-sheet"><span className="cat">Drawing sets</span><div className="mt-2 text-2xl font-semibold text-[#DCEBF5]">{sets.length}</div></div><div className="stratum-sheet"><span className="cat">Count</span><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{objectTotals.COUNT}</div></div><div className="stratum-sheet"><span className="cat">Linear</span><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{objectTotals.LINEAR.toFixed(1)} LF</div></div><div className="stratum-sheet"><span className="cat">Area</span><div className="mt-2 text-2xl font-semibold text-[#6FD6C9]">{objectTotals.AREA.toFixed(1)} SF</div></div></section>

    <section className="grid gap-4 xl:grid-cols-3">
      <div className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Drawing set</h2><form action={createDrawingSetAction.bind(null,projectId)} className="mt-3 grid gap-2"><input name="name" required placeholder="Issued for Bid · Electrical"/><select name="discipline" defaultValue="ELECTRICAL"><option>ELECTRICAL</option><option>ARCHITECTURAL</option><option>MECHANICAL</option><option>PLUMBING</option><option>CIVIL</option><option>STRUCTURAL</option><option>GENERAL</option></select><input name="description" placeholder="Set description"/><button className="btn">Create set</button></form></div>
      <div className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Sheet / revision</h2><form action={createDrawingRevisionAction.bind(null,projectId)} className="mt-3 grid gap-2 md:grid-cols-2"><select name="drawingSetId" required className="md:col-span-2"><option value="">Drawing set</option>{sets.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="sheetNumber" required placeholder="E-101"/><input name="revision" defaultValue="0" placeholder="Revision"/><input name="sheetTitle" className="md:col-span-2" placeholder="Power Plan - Level 1"/><input name="issuedAt" type="date"/><input name="externalUrl" type="url" placeholder="Drawing URL"/><input name="scaleLabel" placeholder={'1/8" = 1\'-0"'}/><div className="grid grid-cols-2 gap-2"><input name="scaleNumerator" type="number" step="0.001" placeholder="Scale num"/><input name="scaleDenominator" type="number" step="0.001" placeholder="Scale den"/></div><button className="btn md:col-span-2">Register sheet</button></form></div>
      <div className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Layer</h2><form action={createDrawingLayerAction.bind(null,projectId)} className="mt-3 grid gap-2"><input name="name" required placeholder="Branch Power / Lighting / Feeders"/><select name="category"><option>CONSTRUCTION</option><option>DEMOLITION</option><option>EXISTING</option><option>ALTERNATE</option><option>RFI</option><option>REVISION</option></select><input name="systemCode" placeholder="System / spec code"/><button className="btn">Create layer</button></form></div>
    </section>

    <section className="stratum-sheet"><div className="mb-3"><h2 className="text-sm font-semibold text-[#DCEBF5]">Capture spatial takeoff</h2><p className="cat">Manual geometry capture now; coordinates are stored as structured JSON so a graphical viewer can edit/render them later without changing commercial lineage.</p></div>{revisions.length===0?<div className="empty-state">Register a drawing sheet before taking off scope.</div>:<form action={createTakeoffObjectAction.bind(null,projectId)} className="grid gap-2 md:grid-cols-3 xl:grid-cols-6"><select name="drawingRevisionId" required className="xl:col-span-2"><option value="">Sheet / revision</option>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · Rev {r.revision} · {r.sheetTitle||"Untitled"}</option>)}</select><select name="objectType">{OBJECT_TYPES.map(t=><option key={t}>{t}</option>)}</select><select name="layerId"><option value="">No layer</option>{layers.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><input name="name" required placeholder="Duplex receptacle / conduit run" className="xl:col-span-2"/><input name="quantity" type="number" step="0.01" defaultValue="1" placeholder="Count qty"/><input name="measurement" type="number" step="0.01" placeholder="Linear / area measurement"/><input name="unit" placeholder="EA / LF / SF"/><input name="x" type="number" step="0.01" placeholder="X1"/><input name="y" type="number" step="0.01" placeholder="Y1"/><input name="x2" type="number" step="0.01" placeholder="X2"/><input name="y2" type="number" step="0.01" placeholder="Y2"/><input name="description" className="xl:col-span-4" placeholder="Description / installation context"/><button className="btn xl:col-span-2">Add takeoff object</button></form>}</section>

    <section className="stratum-sheet"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Spatial takeoff register</h2><p className="cat">{objects.length} object{objects.length===1?"":"s"} · {objects.filter(o=>o.verifiedAt).length} verified · verified objects can be converted through an assembly</p></div><Link href="/costing/assemblies" className="btn-secondary">Assembly Library</Link></div>{objects.length===0?<div className="empty-state">No drawing takeoff objects yet.</div>:<div className="table-scroll"><table className="min-w-[1550px]"><thead><tr><th>Object</th><th>Sheet</th><th>Layer</th><th>Type</th><th className="num">Quantity / measure</th><th>Verification</th><th>Assembly → Estimate</th><th>Existing estimate link</th></tr></thead><tbody>{objects.map(o=>{const rev=revisions.find(r=>r.id===o.drawingRevisionId); const layer=layers.find(l=>l.id===o.layerId); const basis=o.objectType==="COUNT"?o.quantity:(o.measurement??o.quantity); return <tr key={o.id}><td className="desc-cell">{o.name}<span className="cat">{o.description||o.source}</span></td><td>{rev?`${rev.sheetNumber} · R${rev.revision}`:"—"}</td><td>{layer?.name||"—"}</td><td><span className="tag REF">{o.objectType}</span></td><td className="num text-[#6FD6C9]">{o.objectType==="COUNT"?`${o.quantity} ${o.unit}`:`${basis.toFixed(2)} ${o.unit}`}</td><td>{o.verifiedAt?<span className="text-xs font-semibold text-[#6FD6C9]">Verified</span>:<form action={verifyTakeoffObjectAction.bind(null,projectId)}><input type="hidden" name="objectId" value={o.id}/><button className="btn small">Verify</button></form>}</td><td>{o.verifiedAt?<form action={applyAssemblyToEstimateAction.bind(null,projectId)} className="grid min-w-[420px] grid-cols-[1fr_1fr_auto] gap-2"><input type="hidden" name="spatialObjectId" value={o.id}/><select name="assemblyId" required><option value="">Assembly</option>{assemblies.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="estimateId" required><option value="">Editable estimate</option>{editableEstimates.map(e=><option key={e.id} value={e.id}>EST-{String(e.number).padStart(4,"0")} · {e.name}</option>)}</select><button className="btn small" disabled={!assemblies.length||!editableEstimates.length}>Apply</button></form>:<span className="cat">Verify first</span>}</td><td><form action={linkSpatialEstimateAction.bind(null,projectId)} className="flex min-w-[330px] gap-2"><input type="hidden" name="spatialObjectId" value={o.id}/><select name="estimateLineId" required className="min-w-[230px]"><option value="">Estimate line</option>{estimates.flatMap(e=>e.lineItems.map(l=><option key={l.id} value={l.id}>EST-{String(e.number).padStart(4,"0")} · {l.description}</option>))}</select><input name="quantityBasis" type="number" step="0.01" defaultValue={basis} className="w-20"/><button className="btn small">Link</button></form></td></tr>;})}</tbody></table></div>}</section>

    <section className="stratum-sheet"><h2 className="text-sm font-semibold text-[#DCEBF5]">Drawing register</h2><div className="mt-3 space-y-3">{sets.map(s=><div key={s.id} className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold text-[#DCEBF5]">{s.name}</div><div className="cat">{s.discipline} · {(revBySet.get(s.id)||[]).length} sheet revision{(revBySet.get(s.id)||[]).length===1?"":"s"}</div></div></div><div className="mt-2 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{(revBySet.get(s.id)||[]).map(r=><div key={r.id} className="border border-[#183247] p-2 text-xs"><div className="font-semibold text-[#DCEBF5]">{r.sheetNumber} · Rev {r.revision}</div><div className="cat">{r.sheetTitle||"Untitled"}{r.scaleLabel?` · ${r.scaleLabel}`:""}</div>{r.externalUrl&&<a href={r.externalUrl} target="_blank" rel="noreferrer" className="mt-1 inline-block text-[#6FD6C9]">Open drawing</a>}</div>)}</div></div>)}{sets.length===0&&<div className="empty-state">No drawing sets registered.</div>}</div></section>
  </div>;
}
