import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import SpatialViewer from "./SpatialViewer";

type SourceRow={drawingRevisionId:string;sourcePageNumber:number|null;documentName:string;documentRevision:string|null;documentUrl:string|null;revisionUrl:string|null};

export default async function ViewerPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{revisionId?:string}>}){
  const {projectId}=await params; const query=await searchParams; const ctx=await requireTenantContext(); const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}}); if(!project) notFound();
  const {revisions,layers,objects}=await getDrawingWorkspace(projectId,ctx.account.id);
  const requested=query.revisionId&&revisions.some(r=>r.id===query.revisionId)?query.revisionId:null;
  const orderedRevisions=requested?[...revisions].sort((a,b)=>a.id===requested?-1:b.id===requested?1:0):revisions;
  const [costLinks,sources]=await Promise.all([
    db.$queryRawUnsafe<Array<{spatialObjectId:string;estimateLineId:string;estimateId:string;description:string;estimateNumber:number;quantityBasis:number|null}>>(`SELECT l."spatialObjectId",l."estimateLineId",e."id" AS "estimateId",i."description",e."number" AS "estimateNumber",l."quantityBasis" FROM "SpatialEstimateLink" l JOIN "EstimateLineItem" i ON i."id"=l."estimateLineId" JOIN "CostEstimate" e ON e."id"=i."estimateId" WHERE l."accountId"=$1 AND e."projectId"=$2`,ctx.account.id,projectId),
    requested?db.$queryRawUnsafe<SourceRow[]>(`SELECT dr."id" AS "drawingRevisionId",dr."sourcePageNumber",d."name" AS "documentName",pr."revision" AS "documentRevision",d."externalUrl" AS "documentUrl",pr."externalUrl" AS "revisionUrl" FROM "DrawingRevision" dr JOIN "DrawingSet" ds ON ds."id"=dr."drawingSetId" LEFT JOIN "ProjectDocument" d ON d."id"=dr."sourceDocumentId" LEFT JOIN "ProjectDocumentRevision" pr ON pr."id"=dr."sourceDocumentRevisionId" WHERE dr."id"=$1 AND dr."accountId"=$2 AND ds."projectId"=$3`,requested,ctx.account.id,projectId):Promise.resolve([] as SourceRow[]),
  ]);
  const source=sources[0]??null; const sourceUrl=source?.revisionUrl||source?.documentUrl||null; const annotationHref=requested?`/projects/${projectId}/annotations?context=DRAWING&drawingRevisionId=${requested}`:`/projects/${projectId}/annotations`;const markupHref=requested?`/projects/${projectId}/drawings/markup?revisionId=${requested}`:`/projects/${projectId}/drawings/markup`;
  return <div className="space-y-5"><section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Spatial Viewer</p><h1 className="stratum-sheet-title">{project.name} Drawing Intelligence</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Draw Count / Linear / Area takeoff directly on the sheet, move existing objects, compare revisions, annotate drawing context, and preserve calibrated commercial provenance in Neon.</p>{source&&<div className="mt-3 border border-[#1C3A57] bg-[#0B1F32] px-3 py-2 text-xs text-[#9CB2C2]"><span className="font-semibold text-[#DCEBF5]">Plan Room source:</span> {source.documentName}{source.documentRevision?` · Rev ${source.documentRevision}`:""} · page {source.sourcePageNumber??1}{sourceUrl&&<> · <a href={sourceUrl} target="_blank" rel="noreferrer" className="text-[#6FD6C9]">Open source</a></>}</div>}</div><div className="flex flex-wrap gap-2"><Link href={markupHref} className="btn">Markup</Link><Link href={annotationHref} className="btn-secondary">Register</Link><Link href={`/projects/${projectId}/reality-capture`} className="btn-secondary">Matterport</Link><Link href={`/projects/${projectId}/plan-room/drawing-ingestion`} className="btn-secondary">Drawing Intake</Link><Link href={`/projects/${projectId}/drawings/commercial-review`} className="btn-secondary">Commercial Review</Link><Link href={`/projects/${projectId}/drawings/review`} className="btn-secondary">Review Queue</Link><Link href={`/projects/${projectId}/drawings/calibration`} className="btn-secondary">Calibration</Link><Link href={`/projects/${projectId}/drawings/revision-delta`} className="btn-secondary">Revision Delta</Link><Link href={`/projects/${projectId}/drawings`} className="btn-secondary">Workspace</Link></div></div></section><SpatialViewer projectId={projectId} revisions={JSON.parse(JSON.stringify(orderedRevisions))} layers={JSON.parse(JSON.stringify(layers))} objects={JSON.parse(JSON.stringify(objects))} costLinks={JSON.parse(JSON.stringify(costLinks))}/></div>;
}
