import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireTenantContext } from "@/lib/session";
import { getDrawingWorkspace } from "@/lib/drawing-native";
import SpatialViewer from "./SpatialViewer";

type SourceRow={drawingRevisionId:string;sourcePageNumber:number|null;documentName:string;documentRevision:string|null;documentUrl:string|null;revisionUrl:string|null};
type ContextLinkRow={id:string;drawingRevisionId:string;realityCaptureSpaceId:string;label:string|null;drawingGeometryJson:unknown;matterportPoseJson:unknown;captureName:string;sheetNumber:string;revision:string};

export default async function ViewerPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{revisionId?:string;contextLinkId?:string}>}){
  const {projectId}=await params; const query=await searchParams; const ctx=await requireTenantContext(); const project=await db.project.findFirst({where:{id:projectId,accountId:ctx.account.id}}); if(!project) notFound();
  const {revisions,layers,objects}=await getDrawingWorkspace(projectId,ctx.account.id);
  const requested=query.revisionId&&revisions.some(r=>r.id===query.revisionId)?query.revisionId:null;
  const orderedRevisions=requested?[...revisions].sort((a,b)=>a.id===requested?-1:b.id===requested?1:0):revisions;
  const [costLinks,sources,contextLinks]=await Promise.all([
    db.$queryRawUnsafe<Array<{spatialObjectId:string;estimateLineId:string;estimateId:string;description:string;estimateNumber:number;quantityBasis:number|null}>>(`SELECT l."spatialObjectId",l."estimateLineId",e."id" AS "estimateId",i."description",e."number" AS "estimateNumber",l."quantityBasis" FROM "SpatialEstimateLink" l JOIN "EstimateLineItem" i ON i."id"=l."estimateLineId" JOIN "CostEstimate" e ON e."id"=i."estimateId" WHERE l."accountId"=$1 AND e."projectId"=$2`,ctx.account.id,projectId),
    requested?db.$queryRawUnsafe<SourceRow[]>(`SELECT dr."id" AS "drawingRevisionId",dr."sourcePageNumber",d."name" AS "documentName",pr."revision" AS "documentRevision",d."externalUrl" AS "documentUrl",pr."externalUrl" AS "revisionUrl" FROM "DrawingRevision" dr JOIN "DrawingSet" ds ON ds."id"=dr."drawingSetId" LEFT JOIN "ProjectDocumentRevision" pr ON pr."id"=dr."sourceDocumentRevisionId" LEFT JOIN "ProjectDocument" d ON d."id"=pr."documentId" WHERE dr."id"=$1 AND dr."accountId"=$2 AND ds."projectId"=$3`,requested,ctx.account.id,projectId):Promise.resolve([] as SourceRow[]),
    db.$queryRawUnsafe<ContextLinkRow[]>(`SELECT l."id",l."drawingRevisionId",l."realityCaptureSpaceId",l."label",l."drawingGeometryJson",l."matterportPoseJson",c."name" AS "captureName",r."sheetNumber",r."revision" FROM "SpatialContextLink" l JOIN "RealityCaptureSpace" c ON c."id"=l."realityCaptureSpaceId" JOIN "DrawingRevision" r ON r."id"=l."drawingRevisionId" JOIN "DrawingSet" ds ON ds."id"=r."drawingSetId" WHERE l."projectId"=$1 AND l."accountId"=$2 AND ds."projectId"=$1 ORDER BY l."createdAt" DESC`,projectId,ctx.account.id),
  ]);
  const source=sources[0]??null; const sourceUrl=source?.revisionUrl||source?.documentUrl||null; const annotationHref=requested?`/projects/${projectId}/annotations?context=DRAWING&drawingRevisionId=${requested}`:`/projects/${projectId}/annotations`;const markupHref=requested?`/projects/${projectId}/drawings/markup?revisionId=${requested}`:`/projects/${projectId}/drawings/markup`;
  const relevantLinks=requested?contextLinks.filter(l=>l.drawingRevisionId===requested):contextLinks;const focused=query.contextLinkId?contextLinks.find(l=>l.id===query.contextLinkId)||null:null;
  return <div className="space-y-5"><section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#6D8AA0]">Spatial Viewer</p><h1 className="stratum-sheet-title">{project.name} Drawing Intelligence</h1><p className="mt-2 max-w-4xl text-sm text-[#9CB2C2]">Draw Count / Linear / Area takeoff directly on the sheet, move existing objects, compare revisions, annotate drawing context, and preserve calibrated commercial provenance in Neon.</p>{source&&<div className="mt-3 border border-[#1C3A57] bg-[#0B1F32] px-3 py-2 text-xs text-[#9CB2C2]"><span className="font-semibold text-[#DCEBF5]">Plan Room source:</span> {source.documentName}{source.documentRevision?` · Rev ${source.documentRevision}`:""} · page {source.sourcePageNumber??1}{sourceUrl&&<> · <a href={sourceUrl} target="_blank" rel="noreferrer" className="text-[#6FD6C9]">Open source</a></>}</div>}</div><div className="flex flex-wrap gap-2"><Link href={markupHref} className="btn">Markup</Link><Link href={annotationHref} className="btn-secondary">Register</Link><Link href={`/projects/${projectId}/reality-capture`} className="btn-secondary">Matterport</Link><Link href={`/projects/${projectId}/plan-room/drawing-ingestion`} className="btn-secondary">Drawing Intake</Link><Link href={`/projects/${projectId}/drawings/commercial-review`} className="btn-secondary">Commercial Review</Link><Link href={`/projects/${projectId}/drawings/review`} className="btn-secondary">Review Queue</Link><Link href={`/projects/${projectId}/drawings/calibration`} className="btn-secondary">Calibration</Link><Link href={`/projects/${projectId}/drawings/revision-delta`} className="btn-secondary">Revision Delta</Link><Link href={`/projects/${projectId}/drawings`} className="btn-secondary">Workspace</Link></div></div></section>
    {relevantLinks.length>0&&<section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Field reality cross-links</h2><p className="cat">Matterport viewpoints mapped to controlled drawing regions for this {requested?"revision":"project"}.</p></div><span className="tag REF">{relevantLinks.length} links</span></div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{relevantLinks.map(l=><div key={l.id} className={`border bg-[#0B1F32] p-3 text-xs ${focused?.id===l.id?"border-[#6FD6C9]":"border-[#1C3A57]"}`}><div className="font-semibold text-[#DCEBF5]">{l.captureName} ↔ {l.sheetNumber} R{l.revision}</div><div className="cat mt-1">{l.label||"Spatial cross-reference"}</div><div className="mt-2 flex flex-wrap gap-2"><span className={`tag ${l.matterportPoseJson?"REF":""}`}>{l.matterportPoseJson?"VIEWPOINT":"NO VIEWPOINT"}</span><span className={`tag ${l.drawingGeometryJson?"REF":""}`}>{l.drawingGeometryJson?"REGION":"NO REGION"}</span></div><div className="mt-3 flex flex-wrap gap-2"><Link href={`/projects/${projectId}/drawings/viewer?revisionId=${l.drawingRevisionId}&contextLinkId=${l.id}`} className="btn">Focus viewer</Link><Link href={`/projects/${projectId}/reality-capture?spaceId=${l.realityCaptureSpaceId}&linkId=${l.id}`} className="btn-secondary">Open Matterport</Link><Link href={`/projects/${projectId}/drawings/markup?revisionId=${l.drawingRevisionId}&contextLinkId=${l.id}`} className="btn-secondary">Open region</Link></div></div>)}</div></section>}
    <SpatialViewer projectId={projectId} revisions={JSON.parse(JSON.stringify(orderedRevisions))} layers={JSON.parse(JSON.stringify(layers))} objects={JSON.parse(JSON.stringify(objects))} costLinks={JSON.parse(JSON.stringify(costLinks))}/></div>;
}
