"use client";

import { useMemo, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createViewerTakeoffAction, updateViewerGeometryAction } from "./actions";

type Revision={id:string;sheetNumber:string;sheetTitle:string|null;revision:string;externalUrl:string|null;scaleLabel:string|null;width:number|null;height:number|null};
type Layer={id:string;name:string;category:string;isVisibleDefault:boolean};
type Point={x:number;y:number};
type Geometry={type:"Point";x:number;y:number}|{type:"LineString"|"Polygon";points:Point[]};
type Obj={id:string;drawingRevisionId:string;layerId:string|null;objectType:string;name:string;description:string|null;quantity:number;unit:string;measurement:number|null;rawMeasurement:number|null;calibrationId:string|null;calibrationScaleFactor:number|null;calibrationUnit:string|null;confidence:number|null;geometryJson:unknown;verifiedAt:string|null};
type CostLink={spatialObjectId:string;estimateLineId:string;estimateId:string;description:string;estimateNumber:number;quantityBasis:number|null};
type Tool="SELECT"|"MOVE"|"COUNT"|"LINEAR"|"AREA";

function geometryFrom(g:unknown):Geometry|null{if(!g||typeof g!=="object")return null;const x=g as {type?:string;x?:unknown;y?:unknown;points?:unknown};if(x.type==="Point"&&typeof x.x==="number"&&typeof x.y==="number")return{type:"Point",x:x.x,y:x.y};if((x.type==="LineString"||x.type==="Polygon")&&Array.isArray(x.points)){const pts=x.points.flatMap(p=>p&&typeof p==="object"&&typeof (p as Point).x==="number"&&typeof (p as Point).y==="number"?[p as Point]:[]);return{type:x.type,points:pts};}return null;}
function pointsFrom(g:unknown):Point[]{const x=geometryFrom(g);return !x?[]:x.type==="Point"?[{x:x.x,y:x.y}]:x.points;}
function shiftGeometry(g:Geometry,dx:number,dy:number):Geometry{return g.type==="Point"?{type:"Point",x:g.x+dx,y:g.y+dy}:{type:g.type,points:g.points.map(p=>({x:p.x+dx,y:p.y+dy}))};}

export default function SpatialViewer({projectId,revisions,layers,objects,costLinks}:{projectId:string;revisions:Revision[];layers:Layer[];objects:Obj[];costLinks:CostLink[]}){
  const router=useRouter(); const svgRef=useRef<SVGSVGElement|null>(null); const [pending,startTransition]=useTransition();
  const [revisionId,setRevisionId]=useState(revisions[0]?.id||""); const [overlayRevisionId,setOverlayRevisionId]=useState(""); const [visible,setVisible]=useState<Set<string>>(()=>new Set(layers.filter(l=>l.isVisibleDefault).map(l=>l.id))); const [selected,setSelected]=useState<string|null>(null); const [zoom,setZoom]=useState(1); const [overlayOpacity,setOverlayOpacity]=useState(.55);
  const [tool,setTool]=useState<Tool>("SELECT"); const [drawName,setDrawName]=useState("Takeoff"); const [drawLayer,setDrawLayer]=useState(""); const [draftPoints,setDraftPoints]=useState<Point[]>([]); const [drag,setDrag]=useState<{objectId:string;start:Point;original:Geometry}|null>(null); const [editGeometry,setEditGeometry]=useState<Geometry|null>(null); const [error,setError]=useState<string|null>(null);
  const rev=revisions.find(r=>r.id===revisionId); const overlayRev=revisions.find(r=>r.id===overlayRevisionId);
  const shown=useMemo(()=>objects.filter(o=>o.drawingRevisionId===revisionId&&(!o.layerId||visible.has(o.layerId))),[objects,revisionId,visible]); const overlayShown=useMemo(()=>objects.filter(o=>o.drawingRevisionId===overlayRevisionId&&(!o.layerId||visible.has(o.layerId))),[objects,overlayRevisionId,visible]);
  const allPts=[...shown,...overlayShown].flatMap(o=>pointsFrom(o.id===selected&&editGeometry?editGeometry:o.geometryJson)); const minX=Math.min(0,...allPts.map(p=>p.x)),minY=Math.min(0,...allPts.map(p=>p.y)); const maxX=Math.max(rev?.width||overlayRev?.width||100,...allPts.map(p=>p.x),100),maxY=Math.max(rev?.height||overlayRev?.height||100,...allPts.map(p=>p.y),100); const pad=Math.max(5,Math.max(maxX-minX,maxY-minY)*.05),vw=maxX-minX+pad*2,vh=maxY-minY+pad*2;
  const active=objects.find(o=>o.id===selected)||null; const activeLinks=costLinks.filter(l=>l.spatialObjectId===selected);
  function toggleLayer(id:string){setVisible(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next;});}
  function svgPoint(clientX:number,clientY:number){const svg=svgRef.current;if(!svg)return null;const p=svg.createSVGPoint();p.x=clientX;p.y=clientY;const m=svg.getScreenCTM();if(!m)return null;const q=p.matrixTransform(m.inverse());return{x:q.x,y:q.y};}
  function resetTool(next:Tool=tool){setTool(next);setDraftPoints([]);setDrag(null);setEditGeometry(null);setError(null);}
  function run<T>(fn:()=>Promise<T>){setError(null);startTransition(()=>{fn().then(()=>{setDraftPoints([]);setDrag(null);setEditGeometry(null);router.refresh();}).catch(e=>setError(e instanceof Error?e.message:"Action failed."));});}
  function createGeometry(objectType:"COUNT"|"LINEAR"|"AREA",geometry:Geometry){if(!rev)return;run(()=>createViewerTakeoffAction(projectId,{drawingRevisionId:rev.id,layerId:drawLayer||null,objectType,name:drawName.trim()||objectType,geometry}));}
  function onCanvasClick(e:React.MouseEvent<SVGSVGElement>){if(tool==="SELECT"||tool==="MOVE"||pending)return;const p=svgPoint(e.clientX,e.clientY);if(!p)return;if(tool==="COUNT"){createGeometry("COUNT",{type:"Point",x:p.x,y:p.y});return;}if(tool==="LINEAR"){if(draftPoints.length===0)setDraftPoints([p]);else{const a=draftPoints[0];if(a)createGeometry("LINEAR",{type:"LineString",points:[a,p]});}return;}setDraftPoints(prev=>[...prev,p]);}
  function finishArea(){if(draftPoints.length>=3)createGeometry("AREA",{type:"Polygon",points:draftPoints});}
  function pointerDown(e:React.PointerEvent,object:Obj){setSelected(object.id);if(tool!=="MOVE"||pending)return;e.stopPropagation();const start=svgPoint(e.clientX,e.clientY);const original=geometryFrom(object.geometryJson);if(!start||!original)return;setDrag({objectId:object.id,start,original});setEditGeometry(original);(e.currentTarget as Element).setPointerCapture?.(e.pointerId);}
  function pointerMove(e:React.PointerEvent<SVGSVGElement>){if(!drag||tool!=="MOVE")return;const p=svgPoint(e.clientX,e.clientY);if(!p)return;setEditGeometry(shiftGeometry(drag.original,p.x-drag.start.x,p.y-drag.start.y));}
  function pointerUp(){if(!drag||!editGeometry)return;const id=drag.objectId;const geometry=editGeometry;run(()=>updateViewerGeometryAction(projectId,{objectId:id,geometry,reason:"Pointer move in Spatial Viewer"}));}
  function drawObject(o:Obj,overlay=false){const geometry=o.id===selected&&editGeometry&&!overlay?editGeometry:o.geometryJson;const pts=pointsFrom(geometry);const isActive=o.id===selected;const base=overlay?"text-[#E0954F]":isActive?"text-[#E0954F]":"text-[#6FD6C9]";const opacity=overlay?overlayOpacity:1;const handlers=overlay?{}:{onPointerDown:(e:React.PointerEvent)=>pointerDown(e,o),onClick:(e:React.MouseEvent)=>{e.stopPropagation();setSelected(o.id);}};
    if(o.objectType==="COUNT"&&pts[0])return <g key={`${overlay?"overlay":"current"}-${o.id}`} opacity={opacity} className={`${base} ${overlay?"":"cursor-pointer"}`} {...handlers}><circle cx={pts[0].x} cy={pts[0].y} r={Math.max(vw,vh)*.012} fill="currentColor"/><text x={pts[0].x+Math.max(vw,vh)*.015} y={pts[0].y} fontSize={Math.max(vw,vh)*.018} fill="currentColor">{overlay?`Δ ${o.name}`:o.name}</text></g>;
    if(o.objectType==="LINEAR"&&pts.length>=2)return <polyline key={`${overlay?"overlay":"current"}-${o.id}`} points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="currentColor" strokeWidth={Math.max(vw,vh)*.008} strokeDasharray={overlay?`${Math.max(vw,vh)*.018} ${Math.max(vw,vh)*.012}`:undefined} opacity={opacity} className={`${base} ${overlay?"":"cursor-pointer"}`} {...handlers}/>;
    if(o.objectType==="AREA"&&pts.length>=3)return <polygon key={`${overlay?"overlay":"current"}-${o.id}`} points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="currentColor" fillOpacity={overlay?.08:isActive?.32:.14} stroke="currentColor" strokeWidth={Math.max(vw,vh)*.006} strokeDasharray={overlay?`${Math.max(vw,vh)*.018} ${Math.max(vw,vh)*.012}`:undefined} opacity={opacity} className={`${base} ${overlay?"":"cursor-pointer"}`} {...handlers}/>;return null;}
  return <div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)_330px]">
    <aside className="stratum-sheet h-fit space-y-4"><div><div className="cat">Current sheet / revision</div><select className="mt-1 w-full" value={revisionId} onChange={e=>{setRevisionId(e.target.value);setOverlayRevisionId("");setSelected(null);resetTool("SELECT");}}>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select></div>
      <div><div className="cat">Viewer tool</div><div className="mt-2 grid grid-cols-2 gap-2">{(["SELECT","MOVE","COUNT","LINEAR","AREA"] as Tool[]).map(t=><button key={t} type="button" disabled={pending} onClick={()=>resetTool(t)} className={tool===t?"btn small":"btn-secondary"}>{t}</button>)}</div>{tool!=="SELECT"&&tool!=="MOVE"&&<div className="mt-2 space-y-2"><input value={drawName} onChange={e=>setDrawName(e.target.value)} placeholder="Takeoff name"/><select value={drawLayer} onChange={e=>setDrawLayer(e.target.value)}><option value="">No layer</option>{layers.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select>{tool==="AREA"&&<button className="btn small w-full" disabled={draftPoints.length<3||pending} onClick={finishArea}>Finish area ({draftPoints.length} pts)</button>}<p className="cat">{tool==="COUNT"?"Click once to place.":tool==="LINEAR"?draftPoints.length?"Click endpoint.":"Click start point.":"Click polygon vertices, then Finish area."}</p></div>}</div>
      <div><div className="cat">Revision overlay</div><select className="mt-1 w-full" value={overlayRevisionId} onChange={e=>setOverlayRevisionId(e.target.value)}><option value="">None</option>{revisions.filter(r=>r.id!==revisionId&&(rev?r.sheetNumber===rev.sheetNumber:true)).map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select>{overlayRevisionId&&<input type="range" min="0.1" max="1" step="0.05" value={overlayOpacity} onChange={e=>setOverlayOpacity(Number(e.target.value))} className="mt-2 w-full"/>}</div>
      <div><div className="cat">Layers</div><div className="mt-2 space-y-2">{layers.map(l=><label key={l.id} className="flex items-center gap-2 text-xs text-[#DCEBF5]"><input type="checkbox" checked={visible.has(l.id)} onChange={()=>toggleLayer(l.id)}/><span>{l.name}</span><span className="ml-auto font-mono text-[9px] text-[#6D8AA0]">{l.category}</span></label>)}</div></div><div><div className="cat">Zoom</div><div className="mt-2 flex gap-2"><button className="btn small" onClick={()=>setZoom(z=>Math.max(.5,z-.25))}>−</button><div className="min-w-16 self-center text-center font-mono text-xs text-[#9CB2C2]">{Math.round(zoom*100)}%</div><button className="btn small" onClick={()=>setZoom(z=>Math.min(4,z+.25))}>+</button></div></div>{rev?.externalUrl&&<a href={rev.externalUrl} target="_blank" rel="noreferrer" className="btn-secondary block text-center">Open source drawing</a>}</aside>

    <section className="stratum-sheet overflow-hidden"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">{rev?`${rev.sheetNumber} · ${rev.sheetTitle||"Untitled"}`:"No sheet"}</h2><p className="cat">{rev?`Rev ${rev.revision}${rev.scaleLabel?` · ${rev.scaleLabel}`:""}${overlayRev?` · overlay R${overlayRev.revision}`:""}`:"Register a drawing revision first"}</p></div><div className="cat">{pending?"Saving…":`${shown.length} current · ${overlayShown.length} overlay`}</div></div>{error&&<div className="mb-3 border border-[#6A2C2C] bg-[#1A0C0C] p-2 text-xs text-[#F0A0A0]">{error}</div>}{!rev?<div className="empty-state">No drawing revisions available.</div>:<div className="overflow-auto border border-[#1C3A57] bg-[#07131D]" style={{maxHeight:"72vh"}}><div style={{width:`${zoom*100}%`,minWidth:"100%"}}><svg ref={svgRef} viewBox={`${minX-pad} ${minY-pad} ${vw} ${vh}`} className={`block h-auto w-full ${tool==="COUNT"||tool==="LINEAR"||tool==="AREA"?"cursor-crosshair":tool==="MOVE"?"cursor-move":""}`} role="img" aria-label="Spatial takeoff drawing overlay" onClick={onCanvasClick} onPointerMove={pointerMove} onPointerUp={pointerUp}><rect x={minX-pad} y={minY-pad} width={vw} height={vh} fill="transparent" stroke="currentColor" className="text-[#183247]"/>{overlayShown.map(o=>drawObject(o,true))}{shown.map(o=>drawObject(o,false))}{draftPoints.length>0&&<g className="text-[#F6C85F]">{draftPoints.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={Math.max(vw,vh)*.008} fill="currentColor"/>)}{draftPoints.length>1&&<polyline points={draftPoints.map(p=>`${p.x},${p.y}`).join(" ")} fill={tool==="AREA"?"currentColor":"none"} fillOpacity={tool==="AREA"?.08:0} stroke="currentColor" strokeDasharray="3 2" strokeWidth={Math.max(vw,vh)*.004}/>}</g>}</svg></div></div>}</section>

    <aside className="stratum-sheet h-fit">{!active?<div className="empty-state">Select a current-revision takeoff object. Use MOVE to drag it; any geometry change resets verification.</div>:<div className="space-y-4"><div><div className="cat">Selected object</div><h3 className="mt-1 text-sm font-semibold text-[#DCEBF5]">{active.name}</h3><p className="mt-1 text-xs text-[#9CB2C2]">{active.description||"No description"}</p></div><div className="grid grid-cols-2 gap-3"><div><div className="cat">Type</div><div className="mt-1 text-sm text-[#DCEBF5]">{active.objectType}</div></div><div><div className="cat">Quantity</div><div className="mt-1 font-mono text-sm text-[#6FD6C9]">{active.objectType==="COUNT"?active.quantity:(active.measurement??active.quantity)} {active.unit}</div></div><div><div className="cat">Layer</div><div className="mt-1 text-xs text-[#DCEBF5]">{layers.find(l=>l.id===active.layerId)?.name||"—"}</div></div><div><div className="cat">Status</div><div className="mt-1 text-xs text-[#DCEBF5]">{active.verifiedAt?"VERIFIED":"UNVERIFIED"}</div></div><div><div className="cat">Confidence</div><div className="mt-1 text-xs text-[#DCEBF5]">{active.confidence==null?"—":`${Math.round(active.confidence*100)}%`}</div></div><div><div className="cat">Measurement basis</div><div className="mt-1 text-xs text-[#DCEBF5]">{active.calibrationId?`CALIBRATED · ${active.calibrationUnit}`:active.objectType==="COUNT"?"COUNT":"MANUAL"}</div></div></div>{active.rawMeasurement!=null&&<div className="border border-[#1C3A57] p-2 text-xs"><div className="cat">Calibration provenance</div><div className="mt-1 text-[#9CB2C2]">Raw geometry: {active.rawMeasurement.toFixed(3)} drawing units</div><div className="text-[#9CB2C2]">Scale snapshot: {active.calibrationScaleFactor?.toFixed(6)??"—"} {active.calibrationUnit??""}/drawing unit</div></div>}<div><div className="cat">Commercial trace</div><div className="mt-2 space-y-2">{activeLinks.map(l=><Link key={l.estimateLineId} href={`/costing/estimates/${l.estimateId}/spatial`} className="block border border-[#1C3A57] p-2 text-xs hover:border-[#6FD6C9]"><div className="font-semibold text-[#DCEBF5]">EST-{String(l.estimateNumber).padStart(4,"0")}</div><div className="text-[#9CB2C2]">{l.description}</div><div className="cat">Basis {l.quantityBasis??"—"} · Open spatial trace</div></Link>)}{activeLinks.length===0&&<div className="cat">Not linked to estimate scope yet.</div>}</div></div></div>}</aside>
  </div>;
}
