"use client";

import { useMemo, useState } from "react";

type Revision={id:string;sheetNumber:string;sheetTitle:string|null;revision:string;externalUrl:string|null;scaleLabel:string|null;width:number|null;height:number|null};
type Layer={id:string;name:string;category:string;isVisibleDefault:boolean};
type Obj={id:string;drawingRevisionId:string;layerId:string|null;objectType:string;name:string;description:string|null;quantity:number;unit:string;measurement:number|null;rawMeasurement:number|null;calibrationId:string|null;calibrationScaleFactor:number|null;calibrationUnit:string|null;confidence:number|null;geometryJson:unknown;verifiedAt:string|null};
type CostLink={spatialObjectId:string;estimateLineId:string;description:string;estimateNumber:number;quantityBasis:number|null};
type Point={x:number;y:number};

function pointsFrom(g:unknown):Point[]{
  if(!g||typeof g!=="object")return [];
  const x=g as {type?:string;x?:unknown;y?:unknown;points?:unknown};
  if(x.type==="Point"&&typeof x.x==="number"&&typeof x.y==="number")return [{x:x.x,y:x.y}];
  if(Array.isArray(x.points))return x.points.flatMap(p=>p&&typeof p==="object"&&typeof (p as Point).x==="number"&&typeof (p as Point).y==="number"?[p as Point]:[]);
  return [];
}

export default function SpatialViewer({revisions,layers,objects,costLinks}:{revisions:Revision[];layers:Layer[];objects:Obj[];costLinks:CostLink[]}){
  const [revisionId,setRevisionId]=useState(revisions[0]?.id||"");
  const [overlayRevisionId,setOverlayRevisionId]=useState("");
  const [visible,setVisible]=useState<Set<string>>(()=>new Set(layers.filter(l=>l.isVisibleDefault).map(l=>l.id)));
  const [selected,setSelected]=useState<string|null>(null);
  const [zoom,setZoom]=useState(1);
  const [overlayOpacity,setOverlayOpacity]=useState(.55);
  const rev=revisions.find(r=>r.id===revisionId);
  const overlayRev=revisions.find(r=>r.id===overlayRevisionId);
  const shown=useMemo(()=>objects.filter(o=>o.drawingRevisionId===revisionId&&(!o.layerId||visible.has(o.layerId))),[objects,revisionId,visible]);
  const overlayShown=useMemo(()=>objects.filter(o=>o.drawingRevisionId===overlayRevisionId&&(!o.layerId||visible.has(o.layerId))),[objects,overlayRevisionId,visible]);
  const allPts=[...shown,...overlayShown].flatMap(o=>pointsFrom(o.geometryJson));
  const minX=Math.min(0,...allPts.map(p=>p.x)), minY=Math.min(0,...allPts.map(p=>p.y));
  const maxX=Math.max(rev?.width||overlayRev?.width||100,...allPts.map(p=>p.x),100), maxY=Math.max(rev?.height||overlayRev?.height||100,...allPts.map(p=>p.y),100);
  const pad=Math.max(5,(Math.max(maxX-minX,maxY-minY))*0.05); const vw=maxX-minX+pad*2; const vh=maxY-minY+pad*2;
  const active=objects.find(o=>o.id===selected)||null; const activeLinks=costLinks.filter(l=>l.spatialObjectId===selected);
  function toggleLayer(id:string){setVisible(prev=>{const next=new Set(prev); next.has(id)?next.delete(id):next.add(id); return next;});}
  function drawObject(o:Obj,overlay=false){
    const pts=pointsFrom(o.geometryJson); const isActive=o.id===selected; const base=overlay?"text-[#E0954F]":isActive?"text-[#E0954F]":"text-[#6FD6C9]"; const opacity=overlay?overlayOpacity:1;
    if(o.objectType==="COUNT"&&pts[0])return <g key={`${overlay?"overlay":"current"}-${o.id}`} opacity={opacity} onClick={()=>!overlay&&setSelected(o.id)} className={`${base} ${overlay?"":"cursor-pointer"}`}><circle cx={pts[0].x} cy={pts[0].y} r={Math.max(vw,vh)*0.012} fill="currentColor" stroke={overlay?"currentColor":"none"} strokeDasharray={overlay?"2 2":undefined}/><text x={pts[0].x+Math.max(vw,vh)*0.015} y={pts[0].y} fontSize={Math.max(vw,vh)*0.018} fill="currentColor">{overlay?`Δ ${o.name}`:o.name}</text></g>;
    if(o.objectType==="LINEAR"&&pts.length>=2)return <polyline key={`${overlay?"overlay":"current"}-${o.id}`} points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="currentColor" strokeWidth={Math.max(vw,vh)*0.008} strokeDasharray={overlay?`${Math.max(vw,vh)*.018} ${Math.max(vw,vh)*.012}`:undefined} opacity={opacity} className={`${base} ${overlay?"":"cursor-pointer"}`} onClick={()=>!overlay&&setSelected(o.id)}/>;
    if(o.objectType==="AREA"&&pts.length>=3)return <polygon key={`${overlay?"overlay":"current"}-${o.id}`} points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="currentColor" fillOpacity={overlay?.08:isActive?.32:.14} stroke="currentColor" strokeWidth={Math.max(vw,vh)*0.006} strokeDasharray={overlay?`${Math.max(vw,vh)*.018} ${Math.max(vw,vh)*.012}`:undefined} opacity={opacity} className={`${base} ${overlay?"":"cursor-pointer"}`} onClick={()=>!overlay&&setSelected(o.id)}/>;
    return null;
  }
  return <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)_320px]">
    <aside className="stratum-sheet h-fit space-y-4"><div><div className="cat">Current sheet / revision</div><select className="mt-1 w-full" value={revisionId} onChange={e=>{setRevisionId(e.target.value);setOverlayRevisionId("");setSelected(null);}}>{revisions.map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select></div><div><div className="cat">Revision overlay</div><select className="mt-1 w-full" value={overlayRevisionId} onChange={e=>setOverlayRevisionId(e.target.value)}><option value="">None</option>{revisions.filter(r=>r.id!==revisionId&&(rev?r.sheetNumber===rev.sheetNumber:true)).map(r=><option key={r.id} value={r.id}>{r.sheetNumber} · R{r.revision}</option>)}</select>{overlayRevisionId&&<div className="mt-2"><div className="flex justify-between font-mono text-[9px] uppercase text-[#6D8AA0]"><span>Overlay opacity</span><span>{Math.round(overlayOpacity*100)}%</span></div><input type="range" min="0.1" max="1" step="0.05" value={overlayOpacity} onChange={e=>setOverlayOpacity(Number(e.target.value))} className="mt-1 w-full"/></div>}</div><div><div className="cat">Layers</div><div className="mt-2 space-y-2">{layers.map(l=><label key={l.id} className="flex items-center gap-2 text-xs text-[#DCEBF5]"><input type="checkbox" checked={visible.has(l.id)} onChange={()=>toggleLayer(l.id)}/><span>{l.name}</span><span className="ml-auto font-mono text-[9px] text-[#6D8AA0]">{l.category}</span></label>)}</div></div><div><div className="cat">Zoom</div><div className="mt-2 flex gap-2"><button className="btn small" onClick={()=>setZoom(z=>Math.max(.5,z-.25))}>−</button><div className="min-w-16 self-center text-center font-mono text-xs text-[#9CB2C2]">{Math.round(zoom*100)}%</div><button className="btn small" onClick={()=>setZoom(z=>Math.min(4,z+.25))}>+</button></div></div>{rev?.externalUrl&&<a href={rev.externalUrl} target="_blank" rel="noreferrer" className="btn-secondary block text-center">Open source drawing</a>}</aside>

    <section className="stratum-sheet overflow-hidden"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">{rev?`${rev.sheetNumber} · ${rev.sheetTitle||"Untitled"}`:"No sheet"}</h2><p className="cat">{rev?`Rev ${rev.revision}${rev.scaleLabel?` · ${rev.scaleLabel}`:""}${overlayRev?` · overlay R${overlayRev.revision}`:""}`:"Register a drawing revision first"}</p></div><div className="cat">{shown.length} current · {overlayShown.length} overlay</div></div>{!rev?<div className="empty-state">No drawing revisions available.</div>:<div className="overflow-auto border border-[#1C3A57] bg-[#07131D]" style={{maxHeight:"72vh"}}><div style={{width:`${zoom*100}%`,minWidth:"100%"}}><svg viewBox={`${minX-pad} ${minY-pad} ${vw} ${vh}`} className="block h-auto w-full" role="img" aria-label="Spatial takeoff drawing overlay"><rect x={minX-pad} y={minY-pad} width={vw} height={vh} fill="transparent" stroke="currentColor" className="text-[#183247]"/>{overlayShown.map(o=>drawObject(o,true))}{shown.map(o=>drawObject(o,false))}</svg></div></div>}</section>

    <aside className="stratum-sheet h-fit">{!active?<div className="empty-state">Select a current-revision takeoff object on the drawing.</div>:<div className="space-y-4"><div><div className="cat">Selected object</div><h3 className="mt-1 text-sm font-semibold text-[#DCEBF5]">{active.name}</h3><p className="mt-1 text-xs text-[#9CB2C2]">{active.description||"No description"}</p></div><div className="grid grid-cols-2 gap-3"><div><div className="cat">Type</div><div className="mt-1 text-sm text-[#DCEBF5]">{active.objectType}</div></div><div><div className="cat">Quantity</div><div className="mt-1 font-mono text-sm text-[#6FD6C9]">{active.objectType==="COUNT"?active.quantity:(active.measurement??active.quantity)} {active.unit}</div></div><div><div className="cat">Layer</div><div className="mt-1 text-xs text-[#DCEBF5]">{layers.find(l=>l.id===active.layerId)?.name||"—"}</div></div><div><div className="cat">Status</div><div className="mt-1 text-xs text-[#DCEBF5]">{active.verifiedAt?"VERIFIED":"UNVERIFIED"}</div></div><div><div className="cat">Confidence</div><div className="mt-1 text-xs text-[#DCEBF5]">{active.confidence==null?"—":`${Math.round(active.confidence*100)}%`}</div></div><div><div className="cat">Measurement basis</div><div className="mt-1 text-xs text-[#DCEBF5]">{active.calibrationId?`CALIBRATED · ${active.calibrationUnit}`:active.objectType==="COUNT"?"COUNT":"MANUAL"}</div></div></div>{active.rawMeasurement!=null&&<div className="border border-[#1C3A57] p-2 text-xs"><div className="cat">Calibration provenance</div><div className="mt-1 text-[#9CB2C2]">Raw geometry: {active.rawMeasurement.toFixed(3)} drawing units</div><div className="text-[#9CB2C2]">Scale snapshot: {active.calibrationScaleFactor?.toFixed(6)??"—"} {active.calibrationUnit??""}/drawing unit</div></div>}<div><div className="cat">Commercial trace</div><div className="mt-2 space-y-2">{activeLinks.map(l=><div key={l.estimateLineId} className="border border-[#1C3A57] p-2 text-xs"><div className="font-semibold text-[#DCEBF5]">EST-{String(l.estimateNumber).padStart(4,"0")}</div><div className="text-[#9CB2C2]">{l.description}</div><div className="cat">Basis {l.quantityBasis??"—"}</div></div>)}{activeLinks.length===0&&<div className="cat">Not linked to estimate scope yet.</div>}</div></div></div>}</aside>
  </div>;
}
