import Link from "next/link";
import { db } from "@/lib/db";

type Row={id:string;title:string;contextType:string;annotationType:string;priority:string;status:string;dueAt:Date|null;assignedToId:string|null;linkedEntityType:string|null;linkedEntityId:string|null};

export default async function SpatialRiskPanel({projectId,accountId}:{projectId:string;accountId:string}){
  const rows=await db.$queryRawUnsafe<Row[]>(`SELECT "id","title","contextType","annotationType","priority","status","dueAt","assignedToId","linkedEntityType","linkedEntityId" FROM "SpatialAnnotation" WHERE "projectId"=$1 AND "accountId"=$2 AND "status" NOT IN ('RESOLVED','VOID') ORDER BY CASE "priority" WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,"dueAt" ASC NULLS LAST`,projectId,accountId);
  const now=new Date();const critical=rows.filter(r=>r.priority==="CRITICAL");const high=rows.filter(r=>r.priority==="HIGH");const overdue=rows.filter(r=>r.dueAt&&r.dueAt<now);const unassigned=rows.filter(r=>!r.assignedToId);const linkedRfis=rows.filter(r=>r.linkedEntityType==="RFI"&&r.linkedEntityId);
  const points=critical.length*12+high.length*7+overdue.length*8+Math.min(unassigned.length*2,20);const label=points>=40?"HIGH":points>=15?"MEDIUM":"LOW";
  return <section className="stratum-sheet"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-[#DCEBF5]">Spatial annotation commercial exposure</h2><p className="cat">Drawing + Matterport observations contributing to preconstruction risk</p></div><div className="text-right"><div className={`text-xl font-semibold ${label==="HIGH"?"text-rose-400":label==="MEDIUM"?"text-amber-300":"text-[#6FD6C9]"}`}>{label}</div><div className="cat">{points} spatial exposure points</div></div></div><div className="mt-3 grid gap-3 sm:grid-cols-5">{[["Active",rows.length],["Critical",critical.length],["High",high.length],["Overdue",overdue.length],["Unassigned",unassigned.length]].map(([k,v])=><div key={String(k)} className="border border-[#1C3A57] bg-[#0B1F32] p-3"><div className="cat">{k}</div><div className="mt-1 text-xl font-semibold text-[#DCEBF5]">{v}</div></div>)}</div>{rows.length===0?<div className="empty-state mt-3">No active spatial annotations.</div>:<div className="table-scroll mt-3"><table className="min-w-[850px]"><thead><tr><th>Spatial issue</th><th>Context</th><th>Priority</th><th>Due</th><th>Owner</th><th>Workflow</th></tr></thead><tbody>{rows.slice(0,20).map(r=><tr key={r.id}><td>{r.title}<span className="cat">{r.annotationType}</span></td><td>{r.contextType}</td><td className={r.priority==="CRITICAL"||r.priority==="HIGH"?"text-rose-400":""}>{r.priority}</td><td className={r.dueAt&&r.dueAt<now?"text-rose-400":""}>{r.dueAt?r.dueAt.toISOString().slice(0,10):"—"}</td><td>{r.assignedToId?"Assigned":"Unassigned"}</td><td>{r.linkedEntityType==="RFI"?"RFI linked":r.status}</td></tr>)}</tbody></table></div>}<div className="mt-3 flex flex-wrap gap-2"><Link href={`/projects/${projectId}/annotations`} className="btn">Review annotations</Link><Link href={`/projects/${projectId}/drawings/markup`} className="btn-secondary">Drawing markup</Link><Link href={`/projects/${projectId}/reality-capture`} className="btn-secondary">Matterport</Link>{linkedRfis.length>0&&<span className="tag REF self-center">{linkedRfis.length} linked RFI{linkedRfis.length===1?"":"s"}</span>}</div></section>;
}
